### ISSUE TITLE
Xcode 10.2: typealias declarations do not reference the associatedtype they define.

### ISSUE THREAD

**Issue by ileitch** [peripheryapp/periphery#10]
http://openradar.appspot.com/radar?id=4983139243917312

**Comment by booiiing** [comment]
I'm getting false positives for generic types. Is this related or should I open a new issue?

Example code:
```
protocol MyDelegateProtocol {
    func doSomething() // this is reported as unused
}

class MyClass <Delegate: MyDelegateProtocol> {
    weak var delegate: Delegate?
    func doSomething() {
        delegate?.doStuff()
    }
}
```
Environment is XCode 10.3, aggregate target, workspace with multiple targets/schemes.
