### ISSUE TITLE
Can I use periphery with iOS Simulator?

### ISSUE THREAD

**Issue by muratmusic** [peripheryapp/periphery#100]
I cannot find any option to use periphery with iOS Simulator flag, for example:

xcodebuild -workspace PeripheryTest.xcworkspace -scheme PeripheryTest -destination 'platform=iOS Simulator,name=iPhone 8'

or just simple

xcodebuild -configuration Debug -sdk iphonesimulator

What option can I use to set sdk iphonesimulator when I use 'periphery scan' command?

**Comment by ileitch** [comment]
What's the issue you're having? `xcodebuild` should already automatically select the appropriate destination for your scheme.

**Comment by ileitch** [comment]
You can also pass whichever arguments you need to`xcodebuild` with the `--xcargs` option.
