### ISSUE TITLE
Seg fault parsing SwiftUI view

### ISSUE THREAD

**Issue by jhaungs** [peripheryapp/periphery#101]
I found a false positive in some SwiftUI code, so I tried to create a sample project to demonstrate, but instead periphery gets a seg fault on the sample. Once you get past that, in my production code, it says foo is unused.

If you try to run this, you need to add the environment object in SceneDelegate: 

```
    let contentView = ContentView().environmentObject(Foo())
``` 

```
import SwiftUI

class Foo :ObservableObject {
  @Published var text = "Hello World"
}

struct ContentView: View {
  @EnvironmentObject var foo: Foo

  var body: some View {
    Text(foo.text)
  }
}
```

**Comment by ileitch** [comment]
Can you please try version 2.0.1?

**Comment by ileitch** [comment]
Unable to reproduce this in 2.1.1.
