### ISSUE TITLE
PreviewProvider False Positives

### ISSUE THREAD

**Issue by SeanMcTex** [peripheryapp/periphery#102]
SwiftUI relies upon `PreviewProvider` implementations to define how to display previews of SwiftUI code. Periphery flags these as unused, since nothing in the project code ever calls them. But of course Xcode makes use of them, and they don't need to be flagged.

I would suggest that any struct that implements `PreviewProvider` be excluded from the results.

**Comment by jonnyijapan** [comment]
I often use shared types etc from several previewproviders. Periphery reports those types as unused = false positives 🙁

**Comment by ileitch** [comment]
@jonnyijapan can you please open a new issue with an example?
