### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by xanderdunn** [peripheryapp/periphery#104]
There is a small and growing group of developers using [Swift on Linux](https://github.com/tensorflow/swift/blob/master/Installation.md) to develop machine learning libraries.

I believe periphery could be Linux-compatible with some reasonably small changes. When I attempted to build the project on Ubuntu, I saw a few issues:
- Tests/LinuxMain.swift is missing. It's a very simple test runner:
```swift
import XCTest
import MyTests

var tests = [XCTestCaseEntry]()
tests += MyTests.allTests()
XCTMain(tests)
```
- One of the dependencies, AEXML, needs to be updated to version 4.5.0 to be Linux-compatible. See [here](https://github.com/tadija/AEXML/blob/8623e73b193386909566a9ca20203e33a09af142/CHANGELOG.md). However, I don't know which dependency in the Package.swift is pulling it in, so not sure which version to bump.
- `Error: Failed to find .xcworkspace or .xcodeproj in current directory. Please refer to the documentation for instructions on configuring Periphery manually - https://peripheryapp.com/documentation/using-periphery`
  - I believe this link is outdated
  - Most Swift projects on Linux won't have XCWorkspaces. I wasn't able to find instructions for manual configuration. What information is taken fro the .xcodeproj or .xcworkspace? Could it be manually filled in instead?

There may be further issues beyond this. This is as far as I got.

**Comment by ileitch** [comment]
Sorry for the slow response, but this is on my TODO list. A big part of this will be to support SPM projects, which I'll be working on soon.

**Comment by ileitch** [comment]
This is now supported in version 2.0.1.

**Comment by xanderdunn** [comment]
Incredible, thank you @ileitch! It works marvelously!

**Comment by ileitch** [comment]
That was quick! Glad to hear it 💯

**Comment by xanderdunn** [comment]
Note that Homebrew only supports installing casks on macOS, so Homebrew for Linux is not an installation option here:
```
Error: Installing casks is supported only on macOS
```

**Comment by ileitch** [comment]
Oh, I wasn't even aware that Homebrew supported Linux. Thanks, I'll update the README.
