### ISSUE TITLE
Make available through Swift Package Manager (SPM) and Xcode 11.6

### ISSUE THREAD

**Issue by ProfessorTom** [peripheryapp/periphery#105]
As a programmer, I would like to add this dependency to my project via Swift Package Manager so I can migrate away from CocoaPods.

If this tool is already available through SPM, please update `README.md` to indicate the correct way to install in Xcode 11.6 via spm.

**Comment by ProfessorTom** [comment]
![image](https://user-images.githubusercontent.com/3181296/91102559-03cf7380-e62f-11ea-9176-e5b8ed7065ae.png)

**Comment by ileitch** [comment]
This is fixed in master, will be released soon as 2.0.0.

**Comment by ProfessorTom** [comment]
And now that time has passed, is there any word on whether or not 2.0.0 is compatible with both iOS 13 & iOS 14?

**Comment by ileitch** [comment]
The iOS version doesn't really matter, it's more a question of the Xcode & Swift versions. So hopefully this answers your question - yes, Periphery supports Xcode 12.
