### ISSUE TITLE
Segmentation fault after ProtocolExtensionReferenceBuilder step

### ISSUE THREAD

**Issue by QuentinArnault** [peripheryapp/periphery#106]
Thanks for the tool, it helps me a lot in my day to day work.

I have an issue with one of my project. It is a quite complex project with lot of dependencies (Pods, internal frameworks built with a target from the workspace). And I have a segmentation fault with one of this target, just after the ProtocolExtensionReferenceBuilder step.

Last console logs are:
```
...
[analyze:visit] ObjcMembersAttributeBuilder (0.000s)
[analyze:visit] ExtensionAccessibilityCascader (0.000s)
[analyze:visit] CodingKeyEnumReferenceBuilder (0.000s)
[analyze:visit] UnknownTypeExtensionRetainer (0.000s)
[analyze:visit] GenericClassConstructorReferenceBuilder (0.001s)
[analyze:visit] ExtensionReferenceBuilder (0.004s)
[analyze:visit] ProtocolExtensionReferenceBuilder (0.001s)
Resources/periphery: line 8: 80540 Segmentation fault: 11  XXXXXXX
```

The `Resources/periphery` is my script which runs the periphery scan command. With all other targets of my workspace, it works correctly but for one of the target (which builds a framework), this segmentation fault is systematic.

I run the command with quiet mode disabled and verbose mode enabled. How could I investigate this issue further?

**Comment by ileitch** [comment]
What version of Periphery and Xcode are you using?

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this crash.
