### ISSUE TITLE
Unknown argument: '-enforce-exclusivity\=checked' on Xcode 12

### ISSUE THREAD

**Issue by OdNairy** [peripheryapp/periphery#107]
Periphery works nice on Xcode 11.7 but produces an error with Xcode 12 GM during Indexing step:

    Error: SourceKit index request failed for file '<REDACTED>/File.swift': error: unknown argument: '-enforce-exclusivity\=checked'

**Comment by Servus7** [comment]
I still get `error: unknown argument: '-enforce-exclusivity\=checked'` using Periphery 1.8.0 and Xcode 12.0.1 (12A7300).

**Comment by bovillaios** [comment]
Did anyone have a turnaround for this solution?

**Comment by ileitch** [comment]
@bovillaios Periphery 2.4.1 no longer uses SourceKit, so this error should not be possible. Can you describe your situation?

**Comment by bovillaios** [comment]
Hi @ileitch , When we run the project either from Xcode (12.3) or Terminal. I am getting this error. Earlier with Xcode 11.x it was working fine for us. Can u plz help us?

**Comment by ileitch** [comment]
This error exact error is not possible with 2.4.1, are you sure this is exactly what you're seeing? Can you please provide the full output of running Periphery with the `--verbose` option.

**Comment by bovillaios** [comment]
@ileitch, I am extremely sorry. I was referring to the periphery Pod version. Now released about the brew Package version also. I have updated the brew package. Now it is working fine. Thanks a lot. Made my day!!

**Comment by ileitch** [comment]
No worries, glad it’s working now.
