### ISSUE TITLE
Fails on project containing App Clip target

### ISSUE THREAD

**Issue by dhoskins** [peripheryapp/periphery#110]
When running `periphery scan` on a project containing an App Clip target I get the error:

```error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "productType", intValue: nil)], debugDescription: "Cannot initialize PBXProductType from invalid String value com.apple.product-type.application.on-demand-install-capable", underlyingError: nil))```

**Comment by ileitch** [comment]
I've updated the XcodeProj dependency in master, could you give it a try?

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this.
