### ISSUE TITLE
Already update to 1.8.0, but the log shows 1.7.1

### ISSUE THREAD

**Issue by YiYiZheng** [peripheryapp/periphery#113]
I have already update to 1.8.0, but when I periphery scan, the log showed "[version] 1.7.1".

Why? Anything I missed?

**Comment by ileitch** [comment]
How did you upgrade?

**Comment by YiYiZheng** [comment]
> How did you upgrade?

pod install

**Comment by YiYiZheng** [comment]
I have fixed it.
Forgot to 'brew reinstall periphery'.
