### ISSUE TITLE
Parameters from functions annotated with @IBAction should be ignored

### ISSUE THREAD

**Issue by ileitch** [peripheryapp/periphery#131]
Seeing similar things here for a number of parameters that are required for delegate conformance but that we don't actually use (and which we're correctly indicating are unusued with an underscore). E.g.:

```
    @IBAction func tapGestureRecognized(_ sender: UITapGestureRecognizer) {
        view.endEditing(true)
    }
```

…results in…

`ViewController.swift:140:41: warning: Parameter 'sender' is unused`

_Originally posted by @SeanMcTex in https://github.com/peripheryapp/periphery/issues/108#issuecomment-703869739_

**Comment by SeanMcTex** [comment]
Thanks, @ileitch !

**Comment by tyler-lu** [comment]
@ileitch: Another case of `@IBAction` is when you programmatically addTarget to your buttons, gestures,... using `#selector`. This should be ignore too.

**Comment by ileitch** [comment]
@tyler-lu The `sender` parameter isn't required for a #selector. You can simply remove the parameter if it's unused.
