### ISSUE TITLE
Xcode integration

### ISSUE THREAD

**Issue by taher-mosbah** [peripheryapp/periphery#15]
Thanks a lot for open sourcing periphery !
Do you think that it is possible to integrate scan results into Xcode as warnings (like Swiftlint does) ?
Or even better as an Xcode plugin ? (not likely IMHO)
Is this something that we can help with ?

**Comment by ileitch** [comment]
Yes that's quite easy to do. I haven't copied the guide to this repo yet, but it's still available here: https://peripheryapp.com/documentation/xcode-integration/
