### ISSUE TITLE
Error: Unknown option '--setup'

### ISSUE THREAD

**Issue by melgu** [peripheryapp/periphery#179]
Running the command `periphery scan --setup` as described in the README results in the aforementioned error.

_Version 1.8.0, installed via Homebrew on macOS 10.15.7 Catalina_

**Comment by ileitch** [comment]
I was just in the process of cutting a new release, please run `brew upgrade periphery` to get version 2.0.1.

**Comment by melgu** [comment]
Thank you! That was quick 😃
