### ISSUE TITLE
Request For Information: use of CODE_SIGNING_ALLOWED="NO"

### ISSUE THREAD

**Issue by QuentinArnault** [peripheryapp/periphery#191]
Hi,

Not an issue, more a request for information concerning the environment setting `CODE _SIGNING_ALLOWED` forced to `"NO"`. This setting makes my project build failing (to sum up: Batch SDK do no like it) and I would like to understand why this setting was forced to NO? If it's not the right place to have this discussion, do not hesitate to tell me. 🙇

Regards,
Quentin

**Comment by ileitch** [comment]
It was disabled as some projects would also fail to build, since the certs
& prov profiles need to be in place. Periphery doesn’t actually need code
signing to be performed for it to function.

Can you share the error you’re getting? Perhaps we can find a workaround.

**Comment by QuentinArnault** [comment]
According to me the problem is not with Periphery but Batch SDK.

When I run the command

```
./Pods/Periphery/periphery scan
```

I have this error:
```
...
/bin/sh -c /Users/Me/Library/Caches/com.github.peripheryapp/DerivedData-MyProject-MyProject/Build/Intermediates.noindex/MyProject.build/Debug-iphoneos/MyProject.build/Script-44A1B5B722946A6C00AF05FC.sh
: no identity found
Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution Strip\ Batch\ Framework /Users/Me/Library/Caches/com.github.peripheryapp/DerivedData-MyProject-MyProject/Build/Intermediates.noindex/MyProject.build/Debug-iphoneos/MyProject.build/Script-44A1B5B722946A6C00AF05FC.sh
(1 failure)
```

I have verified the content of the script located at `/Users/Me/Library/Caches/com.github.peripheryapp/DerivedData-MyProject-MyProject/Build/Intermediates.noindex/MyProject.build/Debug-iphoneos/MyProject.build/Script-44A1B5B722946A6C00AF05FC.sh`:
```
#!/bin/sh
# This step is required to work around a Xcode App Store submission bug with universal frameworks.
# See https://batch.com/doc/ios/sdk-integration/rich-notifications-setup.html
bash “${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/BatchExtension.framework/strip-frameworks.sh”
```

And I have investigated what is the command run by periphery before building and it's:
```
xcodebuild -workspace ‘/Users/Me/workingCopies/my-repo/MyProject.xcworkspace’ -scheme ‘MyProject’ -parallelizeTargets -derivedDataPath ‘/Users/Me/Library/Caches/com.github.peripheryapp/DerivedData-MyProject-MyProject’ build CODE_SIGNING_ALLOWED=“NO” ENABLE_BITCODE=“NO” DEBUG_INFORMATION_FORMAT=“dwarf”
```

I reproduced the same error when I run directly this command line. But if I remove the `CODE_SIGNING_ALLOWED=“NO”` setting, the command finishes successfully.
This is why I was asking why this setting was set.

**Comment by ileitch** [comment]
It looks like you're using an old version of the Batch SDK, is that correct?

This page indicates that there are two versions of Batch extension SDK, the old close-source one, and a new [open-source](https://github.com/BatchLabs/Batch-iOS-SDK-Extension) version:
> https://help.batch.com/en/articles/4519661-xcode-12-fails-to-build-a-project-containing-batch
> BatchExtension was originally distributed as a closed source dynamic framework. It may cause bitcode issues when submitted using Xcode 12.
>
> New integrations should be made using the open-source version of the extension, using Swift Package Manager.

The upgrade steps explicitly mention removing the `strip-frameworks.sh` script phase.

**Comment by QuentinArnault** [comment]
Thanks a lot for your response. As expected, after replacing the Batch Extension SDK, the periphery scan command works perfectly.
Thanks again.
