### ISSUE TITLE
IBaction connected to subclass triggers error 

### ISSUE THREAD

**Issue by otusweb** [peripheryapp/periphery#192]
I have 
```
class A : UIViewController {
@IBAction func action(_ sender: UIButton)
{...}
}

class B : A
{...}
```
In a storyboard, `action` is connected to a button on an instance of class `B`

=> when I run periphery, it says:  `warning: Function 'action(_:)' is unused`

Periphery version 2.1.0

**Comment by ileitch** [comment]
This should now be resolved in 2.1.1.
