### ISSUE TITLE
Enum cases reported as unused

### ISSUE THREAD

**Issue by baldarama** [peripheryapp/periphery#194]
it is reporting all the cases in a custom enum as unused.
```
enum LocalizedStrings: String, CaseIterable {
 case mainTitle = "main_title"
 }
```
i have a custom function that returns the localized string like this
```
extension String {
    static func localizedText(_ forLocalizedString: LocalizedStrings) -> String {
        return NSLocalizedString(forLocalizedString.rawValue, comment: "")
    }
}
```
and i usually call that function like this:
```
titleLabel.text = .localizedText(.mainTitle)
```

**Comment by ileitch** [comment]
This certainly isn't expected behavior. I'm also unable to reproduce this, and there's already test coverage for enums. What version of Swift are you using? Are you sure that the files that use `LocalizedStrings` are members of the targets you've passed to `--targets`?

**Comment by aisohaikens** [comment]
I get something likewise:

```
enum Foo {
    static let foo = "foo"
}

class Bar {
    func bar() -> [String: Int] {
        var s: [String: Int] = [:]
        s[Foo.foo] = 3
        return s
    }
}

let b = Bar()
print(b.bar())

```
gives me 
```
main.swift:2:16: warning: Property 'foo' is assigned, but never used
```
This file is a member of the target I pass to `--targets`. swift version is 5.3.1

**Comment by ileitch** [comment]
Closing due to lack of feedback. Issue by @aisohaikens is addressed in https://github.com/peripheryapp/periphery/issues/252.
