### ISSUE TITLE
Enum "Key" is unused

### ISSUE THREAD

**Issue by mpdifran** [peripheryapp/periphery#195]
Hi!

I use enums as a form of name spacing constants like so:

```
enum Key {
    static let email = "Key.email"
}

...

userDefaults.set(email, forKey: Key.email)
```

Periphery marks the enum `Key` as unused. This is probably expected behaviour, but just wanted to bring this pattern to your attention in case you'd like to make an exception for it!

**Comment by ileitch** [comment]
This certainly isn't expected behavior. I'm also unable to reproduce this, and there's already test coverage. What version of Swift are you using? Are you sure that the files that use `Key.email` are members of the targets you've passed to `--targets`?

**Comment by mpdifran** [comment]
Ah interesting. Could potentially be related to being embedded in another class?

```
final class MyClass {
    fileprivate enum Key {
        static let email = "Key.email"
    }
}
```

Also make note that enum is not a case, but a static constant! The enum itself is actually empty.

**Comment by ileitch** [comment]
I'm still unable to reproduce - I've created a test case here: https://github.com/peripheryapp/periphery/pull/196/commits/79e40a04d95955c71cb63cedd1713da01efb7d21

Are you able to create a simple reproduction your own project? What version of Periphery & Swift are you using?

**Comment by mpdifran** [comment]
periphery version: 2.1.1
Xcode: Version 12.2 (12B45b)
Swift: 5.3.1

This might be more similar to our current setup:

```
final class Issue195 {
    fileprivate enum Key {
        static let email = "Key.email"
    }
}

extension Issue195 {
    func someFunc() {
        print(Key.email)
    }
}
```

**Comment by ileitch** [comment]
Hmm, sill not able to reproduce: https://github.com/peripheryapp/periphery/commit/f1c2c814e3beb4d850ecb9c9f99aba969bf2373b

Can you please try to reproduce this in your project using this example?

**Comment by mpdifran** [comment]
I'll try and get to this by next week!

**Comment by ileitch** [comment]
Is the file containing the enum a member of multiple build targets?

**Comment by mpdifran** [comment]
Nope, just a single build target.

**Comment by ileitch** [comment]
Have you had a chance yet to investigate this issue using the example I provided?

**Comment by mpdifran** [comment]
Sorry, haven't found time to dig into this yet. Should have time next week!

**Comment by mpdifran** [comment]
Struggling to find time. Maybe we just close this issue and I'll reopen it if I encounter it again.

**Comment by ileitch** [comment]
ok, sgtm 👍
