### ISSUE TITLE
Mixed Xcode and SwiftPM projects support

### ISSUE THREAD

**Issue by paulofaria** [peripheryapp/periphery#197]
Hello, 

I have an iOS Xcode Project which I use in conjunction with SwiftPM to run Komondor git hooks. I want to run periphery against my Xcode project, but periphery won't let me since it thinks the project is a SwiftPM project. I haven't checked the code, but I guess it looks for a `Package.swift` file and if it finds one it assumes it is a SwiftPM project. I would like to be able to force scan as an Xcode project instead of a SwiftPM project. Is there any specific reason this isn't supported? Thank you.

**Comment by paulofaria** [comment]
To be more specific, I'm also using SwiftPM to install periphery. So I have a `Package.swift` file which I use to install periphery and a MyXcodeProject.xcodeproj which I want to scan. Then when I run the following command:

```sh
swift run periphery scan --project MyXcodeProject.xcodeproj --schemes MyScheme --targets MyTarget --verbose
```

I get the following output:

```sh
Error: The --project option has no effect with Swift Package Manager projects.
```

**Comment by ileitch** [comment]
This is now supported in 2.2.0, thanks for reporting!

**Comment by paulofaria** [comment]
Thank you!
