### ISSUE TITLE
Wildy incorrect results, but only for a single file

### ISSUE THREAD

**Issue by dalemyers** [peripheryapp/periphery#203]
I'm evaluating periphery just now to see if it would be helpful for my team and so far the results are looking good. However, there is a problem with one particular file where periphery just goes haywire. It generates a bunch of false positives in places that don't even make sense (things like finding an unused method, but the position is in the middle of a totally different one). 

It's literally just this one single file. There's nothing special about it at all. I can't get a minimal repro due to the entire projects context being required, nor can I share the code here unfortunately. 

Is there any logging I can turn on to generate more info about what is happening here?

**Comment by ileitch** [comment]
The `--verbose` flag will print some details about the step taken, but it doesn't provide any great insight into the generated results.

* What version of Periphery are you using?
* How did you install Periphery?
* What version of Xcode and/or Swift are you using?
* Is your project Xcode or SwiftPM?
* Is it always the exact same file?
* Are the erroneous results consistent?
* Is the file a member of multiple build targets? If so, were more than one of those targets passed to the `--targets` option?
* Does the file contain any macros, e.g `#if`?

**Comment by dalemyers** [comment]
I'm on 2.1.0 (but will try again with 2.2.2)
Installation is via Homebrew
Xcode is 12.1 with Swift 5
It's an Xcode project
Always the same file
Always the same errors
It's only a member of a single target
No macros

**Comment by ileitch** [comment]
* Are all of the results incorrect, or just some of them?
* Are the results nonsense, or are just the file positions incorrect?
* Is there any discernible pattern to the incorrect results, i.e are the file positions all off by the same amount?
* Do the results only become incorrect after a certain position in the file? I.e results from line 1-100 are correct, but anything after 101 is incorrect?

**Comment by dalemyers** [comment]
One of the results is correct, but the others are all wrong. The correct one is an unused property.  The incorrect ones are all unused functions, despite half of them being used in the very same file. The line numbers appear to be almost random. 

And they are wrong all over the file. The correct result is the second result for that particular file.

**Comment by ileitch** [comment]
* Are any of the functions deeply nested?, e.g
```swift
func outer() {
   func inner() { }
}
```
* Are any of the functions named, or referenced with backquotes? e.g
```swift
func `class`() {}
func other() {
    `class`()
}
```

* Do any of the functions share the same name across different structs/classes? e.g
```swift
class A {
    func foo() {}
}

class B {
    func foo() {}
}
```

**Comment by ileitch** [comment]
Also, possibly not an issue here, but in this scenario Periphery will report both `a()` and `b()` as unused, which could be a little confusing as at first glance `a()` may appear to be used, though `b()` is also unused. This doesn't of course explain the incorrect positions, though it could help you whittle down the number of results to help hone in on the problem.

```swift
class Foo {
    func a() {}
    func b() {
        a()
    }
}
```

**Comment by dalemyers** [comment]
Nope, no nesting or backticks. No shared names across classes/files either. The only thing of interest is that we use multiple extensions to group functions together, but this is all in the same file, and we do this literally everywhere without problems. 

Looking at it closer though, some of the things it is detecting are unused in the traditional sense when you trace them back up the chain as they are called by NotificationCenter via `#selector(whatever)`. However, we've got many other examples like this that aren't flagged as false positives. 

To clarify, we've got something like:

```swift
class Whatever {
    init() {
        NotificationCenter.default.addObserver(self, selector: #selector(myFunc), name: "something", object: nil)
    }

    @objc func myFunc() {
        doThing()
    }

    func doThing() {
        // pass
    }
}
```

In this case, `doThing` is being flagged as unused, but `myFunc` isn't. But the line number here would be totally different.

**Comment by dalemyers** [comment]
2.2.2 shows the same results

**Comment by ileitch** [comment]
Can you try running with `--verbose` and see if you get any warnings beginning with 'Expected declaration at' for this file?

**Comment by dalemyers** [comment]
Yes. Dozens. One for basically every declaration in the file as far as I can see.

**Comment by dalemyers** [comment]
I see this for one other file as well, but that one has a bunch of  `#if os(iOS)` in it. This one doesn't have any `#if` statements. There are no special flags assigned to it for compilation either.

**Comment by ileitch** [comment]
OK, at least we now have a lead.

Do the warnings print the correct locations? If so, that means that SwiftSyntax is able to correctly parse the file, yet the results being returned from the index store do not match up. When this happens the declaration's accessibility, attribute and modifier metadata can't be applied and thus factored into the analysis.

**Comment by dalemyers** [comment]
Yes, these appear to all be correct locations.

**Comment by dalemyers** [comment]
(By correct, I mean that they are all declarations, not that they are necessarily unused)

**Comment by ileitch** [comment]
I wonder if perhaps the file was modified somehow during the initial Periphery build, resulting in an incorrect index. Can you try removing DerivedData (🙄 ) and re-run Periphery: `rm -rf ~/Library/Caches/com.github.peripheryapp/DerivedData-*`

**Comment by dalemyers** [comment]
Yup, that fixed it. It's all behaving exactly as expected now. 

As for _why_ it was broken, I did cancel a run of periphery this morning, so I wonder if that's what got it stuck in the bad state? 

Either way, this particular issue seems to be resolved for now. Thanks for the help!

**Comment by ileitch** [comment]
> As for why it was broken, I did cancel a run of periphery this morning, so I wonder if that's what got it stuck in the bad state?

Sounds like a reasonable explanation to me.

> Either way, this particular issue seems to be resolved for now. Thanks for the help!

You're welcome.
