### ISSUE TITLE
File included in several targets 

### ISSUE THREAD

**Issue by sdc-78** [peripheryapp/periphery#204]
Hi,

To begin with, thank you very much for your responsiveness to correct the bugs that I am reporting!

I've got a file defining some properties (in an `enum` namespace) that is included in two targets that I give to Periphery. If a property is used in one target and not in the other, Periphery reports it as being "unused". I would have expected that it was enough for each property to be used in at least one target so that it would not be reported as unused.

**Comment by ileitch** [comment]
> To begin with, thank you very much for your responsiveness to correct the bugs that I am reporting!

Being unemployed has its benefits 😆

I've reproduced this, fix might take a while though, possibility not until tomorrow.

**Comment by tyler-lu** [comment]
I am still experiencing this when I have a Widget target in my project. Is this commit merged to the 2.2.2 release?

**Comment by ileitch** [comment]
It's not released yet, though hopefully I'll be releasing 2.3.0 today or tomorrow.

**Comment by ileitch** [comment]
2.3.0 is now released.
