### ISSUE TITLE
Unused parameter for protocols

### ISSUE THREAD

**Issue by dalemyers** [peripheryapp/periphery#206]
It's not clear if this is a false positive or not. I've got some code like this:

```swift

public protocol DispatchQueueProtocol {
  func sync<T>(execute work: () throws -> T) rethrows -> T
  func async(execute work: @escaping @convention(block) () -> Void)
  func doDelayed(_ seconds: TimeInterval, _ block: @escaping @convention(block) () -> Void)
}

extension DispatchQueue: DispatchQueueProtocol {
  public func async(execute work: @escaping @convention(block) () -> Void) {
    async(execute: DispatchWorkItem(block: work))
  }

  public func doDelayed(_ seconds: TimeInterval, _ block: @escaping @convention(block) () -> Void) {
    doDelayed(seconds, qos: .unspecified, flags: [], block)
  }
}
```

Periphery is flagging each parameter in the protocol as unused. I understand that this may just be a naming thing, however, I'd have guessed that it should be accepted as used in that case? Or am I just misunderstanding something here (the more likely option)? 

Thanks!

**Comment by dalemyers** [comment]
Ah, this file is in multiple targets, so that most likely explains this one.

**Comment by ileitch** [comment]
These shouldn't be reported as unused, as they're actually used in the implementation. I'm currently working on fixing multi-target files for #204. Let's revisit this once that work is completed.

**Comment by dalemyers** [comment]
That would be great if it was the case. We've got files that basically have to be in multiple targets (used in watchOS and iOS versions of the same framework).

**Comment by ileitch** [comment]
OK, so the multi-target fix is now in master.

In your example, it's correct that the `sync` method is unused. The implementation is provided by `DispatchQueue` however its presence in the protocol is redundant unless referenced via a value type for that protocol, e.g:

```swift
let q: DispatchQueueProtocol = DispatchQueue(label: "")
q.sync {} // sync in protocol is used
```

```swift
let q = DispatchQueue(label: "")
q.sync {} // sync in protocol is unused
```

Could you try Periphery from master, and see if that improves the situation? A simple `swift build` after checkout should work, and then you can point directly to the binary in `.build/debug/periphery`.

**Comment by dalemyers** [comment]
Just checked and it's happier with that. There's still one entry which may be a false positive. Looking into it now.

**Comment by dalemyers** [comment]
So the one which it still finds is your second example there. 

Side note: Is there a recommended way of handling unused parameters for protocol conformance? As an example, the protocol above exists so we can mock for tests. The implementation of `doDelayed` looks like this:

```swift
  public func doDelayed(_ seconds: TimeInterval, _ block: @escaping @convention(block) () -> Void) {
    block()
  }
```

Here `seconds` isn't used. We can use a `// periphery:ignore` comment on the function, but this happens probably hundreds, if not thousands, of times across our codebase.

**Comment by ileitch** [comment]
To make sure we're on the same page here, this is what I'm testing with:

```swift
protocol DispatchQueueProtocol {
    func doDelayed(_ seconds: TimeInterval, _ block: @escaping @convention(block) () -> Void)
}

extension DispatchQueue: DispatchQueueProtocol {
    func doDelayed(_ seconds: TimeInterval, _ block: @escaping @convention(block) () -> Void) {
        block()
    }
}

let queue = DispatchQueue(label: "")
queue.doDelayed(1) {}
```

for which Periphery will give the following results:

```
foo.swift:2:10: warning: Function 'doDelayed(_:_:)' is unused
foo.swift:6:21: warning: Parameter 'seconds' is unused
```

These results are actually correct. The `DispatchQueueProtocol` protocol is completely redundant, since it's never used as a value type. Thus the call do `doDelayed()` doesn't involve a protocol witness table, it's just a direct call to the method declared in the extension.

Does this describe what you're seeing?

**Comment by dalemyers** [comment]
Yes, I completely agree with you. That's exactly what is happening (and what should be happening).

**Comment by ileitch** [comment]
OK great, so is that everything resolved in this issue?

**Comment by dalemyers** [comment]
Yup! If you have an answer to my unused parameter question that would be great, but for actual issues it's all sorted.

**Comment by ileitch** [comment]
You mean this?

> Side note: Is there a recommended way of handling unused parameters for protocol conformance? As an example, the protocol above exists so we can mock for tests. The implementation of doDelayed looks like this:

Perhaps I'm a bit confused about how you're using this `doDelayed` method. I believe we've established it's just a normal method in an extension to `DispatchQueue`, and that the `doDelayed` declaration in `DispatchQueueProtocol` is redundant, and thus can be removed. Therefore, this isn't a question of protocol conformance, it's simply a method that doesn't use any of its parameters. If that's the case, then the solution is just to provide a variant without the `seconds` parameter:

```swift
public func doDelayed(_ block: @escaping @convention(block) () -> Void) {
    block()
}
```

On the other hand, if `DispatchQueueProtocol` _were_ used as a value type, i.e `let q: DispatchQueueProtocol = ...; q.doDelayed(...)` (though you said it wasn't) then Periphery would identify that the `doDelayed` protocol declaration _is_ used, and would retain the `seconds` parameter if it's used in _any_ of the implementations of `doDelayed`. However, `seconds` would still be reported as unused if _none_ of the implementations use `seconds`, and in that case the signature of the protocol can simply be changed to remove the `seconds` parameter.

**Comment by dalemyers** [comment]
Ok, I'm following you. Thanks!
