### ISSUE TITLE
Symbols only used in method marked with `// periphery:ignore` are reported as `unused`

### ISSUE THREAD

**Issue by sdc-78** [peripheryapp/periphery#209]
Hi again,

I've marked a method with a `// periphery:ignore` comment.
That method is the only one to use another method and a property. These are reported as `unused` by Periphery.

I don't know whether you consider this as a bug.
Maybe you could allow a `// periphery:ignore:recursive` comment to handle this case (if you don't want to alter the current behaviour of `// periphery:ignore`)?

**Comment by ileitch** [comment]
Opted to alter the behavior of the existing comment, since I think this is reasonably expected behavior.
