### ISSUE TITLE
Seeing several false positives (I think)

### ISSUE THREAD

**Issue by rudro** [peripheryapp/periphery#21]
Using periphery to analyze an open-source DI project. Part of it is a command-line MacOS tool. You can get the source here : https://github.com/uber/needle/tree/master/Generator

In that `Generator` directory, please run `swift package generate-xcodeproj --xcconfig-overrides xcode.xcconfig` to create an Xcode project.

Once that's done we can run `../Periphery scan --project /Users/rudro/workspace/needle/Generator/Needle.xcodeproj --schemes needle --targets NeedleFramework` (the capital letter due to me using a local build of periphery).

Some of the warnings are great.

e.g:
`
/Users/rudro/workspace/needle/Generator/Sources/NeedleFramework/Generating/DependencyProviderContentTask.swift:22:8: warning: Struct 'PropertyNotFoundErrorInfo' is unused
`
This is indeed an unused struct.

However, there are many problematic warnings.  Let's start with just one:
`/Users/rudro/workspace/needle/Generator/Sources/NeedleFramework/Generating/DependencyProviderContentTask.swift:37:5: warning: Initializer 'init(providers:)' is unused`

It warns that this init is not used: https://github.com/uber/needle/blob/4ca57ee2bd0c34022c2de2cb0fcbd2a9cb93eb17/Generator/Sources/NeedleFramework/Generating/DependencyProviderContentTask.swift#L37

However, it's used here : https://github.com/uber/needle/blob/4ca57ee2bd0c34022c2de2cb0fcbd2a9cb93eb17/Generator/Sources/NeedleFramework/Generating/DependencyGraphExporter.swift#L79

Could you have a look and let me know if I am missing some command-line params ?  Once I get a response, I'll move down the list to the other issues.

Thanks!

p.s. you can open the project in Xcode to verify that both files are part of the `NeedleFoundation` target.

**Comment by ileitch** [comment]
Since you're analyzing a single framework target, there are no other targets that consume its public interfaces. Therefore you need to tell Periphery to assume that all `public` declarations are in use with `--retain-public`.

**Comment by rudro** [comment]
Neither this class (`DependencyProviderContentTask`) not it's `init` is declared `public` (both are internal). Why is Periphery assuming these are `public` ?

**Comment by rudro** [comment]
Also note, the warning we get is that this init is *unused*, when it's clearly being used. Not that this init is in use.

**Comment by ileitch** [comment]
Periphery doesn't assume they are public, but it does list them as unused because the class/function that references them is also unused. It looks like `Generator` is the main public interface of the framework, and thus the root reference holder of the majority of classes.

Since you didn't use `--retain-public`, and there's no other code that uses `Generator`, Periphery has no way of knowing if it's used or not. That's why when analyzing framework projects, you need to use `--retain-public`.

**Comment by rudro** [comment]
Thanks, this makes sense. I assumed the "in use" was pairwise (if class A used class B, then class B is in use). I was not considering the usage as a chain to the very top.
