### ISSUE TITLE
Segmentation fault when running Periphery 2.3.0 with my project

### ISSUE THREAD

**Issue by sdc-78** [peripheryapp/periphery#232]
Hello,

With Periphery 2.3.0, I get a segmentation fault in the "Indexing..." step with my project.
Everything was OK with Periphery 2.2.2.
Everything is also OK with Periphery 2.3.0 when I build it in debug configuration.
How can I help you to fix that ?

**Comment by ileitch** [comment]
Fixed in 2.3.1.

**Comment by sdc-78** [comment]
It works with 2.3.1.
Thanx
