### ISSUE TITLE
IBActions reported as unused

### ISSUE THREAD

**Issue by Servus7** [peripheryapp/periphery#234]
All IBActions In our project are incorrectly marked as not used. IBInspectable and IBOutlet however are marked only if unused.
What could be the difference resulting in all IBActions being false positives?

**Comment by ileitch** [comment]
Servus 👋 

That certainly shouldn't be happening. We've already test coverage for IBAction: https://github.com/peripheryapp/periphery/blob/master/Tests/XcodeTests/iOSProject/iOSProject/XibViewController.swift#L4-L7 So there must be something a little different about your usage.

Could you take a look again and see if there's any special about the way you're using IBAction perhaps? If not, please provide an example.

**Comment by 5sw** [comment]
I see the same issue if my `@IBAction` is private. Same happens for `@objc`, gets marked as unused as soon as it is private.

**Comment by sdc-78** [comment]
In my project, I don't have false positives for my private @IBAction.

**Comment by ileitch** [comment]
> I see the same issue if my `@IBAction` is private.

I'm also unable to reproduce this by making them private.

> Same happens for `@objc`, gets marked as unused as soon as it is private. Are you talking about methods in general, or only `@IBAction` methods?

Are you using the new `--retain-objc-accessible` option? If so, I believe I've identified a bug with that: https://github.com/peripheryapp/periphery/issues/238

**Comment by Servus7** [comment]
I added `--retain-objc-accessible` and the false positives are gone. Thank You! I'll start removing unused code.
BTW: Our IBActions aren't private

**Comment by ileitch** [comment]
@Servus7 That option is only intended for use with mixed Swift/Objc projects. It shouldn't be used just to fix IBAction false positives. If a class is referenced by a nib, then it's IBActions should also be identified as used.

Do you have any instances of IBAction being reported as unused in a class that also has IBOutlet/Inspectable that _aren't_ being reported as unused? If so, please provide as much code as possible from this class so that I may diagnose.

**Comment by Servus7** [comment]
We were using Resources Bundles and doesn't added them to periphery scan 🤦🏻‍♂️

**Comment by KRUBERLICK** [comment]
@Servus7 could you elaborate more on what exactly did you do to fix the issue? If you still remember, of course :)
