### ISSUE TITLE
Come back of the "returned exit status '74'" issue

### ISSUE THREAD

**Issue by QuentinArnault** [peripheryapp/periphery#241]
I'm experiencing this issue while running this command below from a Bitrise job

`periphery scan`

The error is:

```
Error: Shell command '/usr/bin/env xcodebuild -workspace /Users/vagrant/git/MyWorkspace.xcworkspace -list -json' returned exit status '74':
```

My stack is Xcode 12.1 and Mac OS Catalina.

I enabled verbose mode but do not see any extra information.

My .periphery.xml is 
```
--- # .periphery.yml
disable_update_check: false
format: xcode
# Ignore all external pods
index_exclude: [Some folders...]
index_store_path: null
project: null
#quiet: true
quiet: false
report_exclude: []
retain_assign_only_properties: false
retain_public: false
retain_unused_protocol_func_params: false
schemes:
- MainApp
skip_build: false
strict: false
targets:
- MainApp
- Something
- AnotherTarget

#verbose: false
verbose: true
workspace: ./MyWorkspace.xcworkspace/
xcargs: null
```

Can you help debugging this issue?

**Comment by ileitch** [comment]
Can you try running the xcodebuild command just by itself? It may print some output to help identify the issue.

**Comment by QuentinArnault** [comment]
When I run this command line from a ssh session on Bitrise have

`xcodebuild: error: Could not resolve package dependencies`

But it works on my local machine. It seems that the problem is not link to Periphery.

**Comment by ileitch** [comment]
If that doesn't work, you could also try running `xcodebuild -resolvePackageDependencies` in a step before Periphery.

**Comment by QuentinArnault** [comment]
It's really weird, I have to add this 3 commands before running `Periphery scan` to make it work on Bitrise

```
xcodebuild -resolvePackageDependencies
xcodebuild -workspace /Users/vagrant/git/MyWorkspace.xcworkspace -list -json
xcodebuild -workspace '/Users/vagrant/git/MyWorkspace.xcworkspace' -scheme 'MyScheme' -derivedDataPath '/Users/vagrant/Library/Caches/com.github.peripheryapp/DerivedData-MyWorkspace-MyScheme' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf"
```

If I remove just on of them, I have the `74` error...

**Comment by ileitch** [comment]
Yeah that's very odd indeed. What version of Xcode are you using? Have you tried 12.3?

**Comment by QuentinArnault** [comment]
Tested with 12.3 and have the same result.

**Comment by ileitch** [comment]
I think your best option is to open a bug report on bugs.swift.org. I'm all out of suggestions, and this appears to be an issue with SwiftPM, not Periphery.

**Comment by AndrewSB** [comment]
fwiw I just installed this, and I still get `returned exit status '74'`, even after I run those 3 commands suggested by @QuentinArnault.

**Comment by ileitch** [comment]
@AndrewSB does the xcodebuild command also fail when you run it manually?

**Comment by gchiacchio** [comment]
same here... I have the same issue (Xcode 13.2.1 on M1 mac) and manually running the command returns the JSON for the workspace with the schemes

**Comment by gchiacchio** [comment]
After manually running the xcodebuild command, it just started to work with periphery.
