### ISSUE TITLE
Inconsistent results between runs

### ISSUE THREAD

**Issue by dalemyers** [peripheryapp/periphery#245]
I've been working on a project which takes the results from periphery and adds comments to the correct lines of code so that my team are aware of the issues that are found and we can correct these issues if we are working in the same area. However, I've run into a problem. If I run periphery, add comments, then run it again, I get different results the second time round. 

I control for lines moving around etc. I filter out all results in files that are in multiple targets. I ignore `@objc` annotations. 

I'm finding that even in the raw results, on the first run it can find `N` results in a given file, then `M` results on a second run when `M` != `N`. There's no consistency in it (i.e. it's not always protocols or method parameters, etc.) as far as I can tell, and I've been unable to find a minimal repro. I also can't share our project unfortunately. I can tell you that it is ~1,000,000 lines of code though. If there's any way I can start to narrow down what's going on, I'd love to know so I can provide that info here. 

Sorry that this isn't a nice concrete issue with an easy repro! 

Edit: To clarify, it's <2% of the results that are different.

**Comment by ileitch** [comment]
After adding the comments, does your second run use `--skip-build`?

> I filter out all results in files that are in multiple targets

FYI support for multi-target files was added in 2.3.0.

**Comment by dalemyers** [comment]
Both runs I do specify `--clean-build`. 

And good to know about the multi-target stuff!

**Comment by ileitch** [comment]
> I filter out all results in files that are in multiple targets

How are you doing this? With `--index-exclude` / `--report-exclude` or in your custom script?

> I ignore @objc annotations.

How are you doing this? With the `--retain-objc-annotated` option, or something custom?

How are you adding the comments to your code? SwiftSyntax? Could any of the new comments be inserted incorrectly?
Are the inconsistent results false-positives?
Do you only get inconsistent results after adding new comments, or are they inconsistent without changing anything?

**Comment by dalemyers** [comment]
Sorry, the holidays got in the way here and then it was a frantic week. Will hopefully get back to this next week.

**Comment by ileitch** [comment]
Any luck finding a solution to this?

**Comment by dalemyers** [comment]
Sorry, had a ton of stuff come up. Will likely be at least a month before I get back to this.

**Comment by aisohaikens** [comment]
I see (probably) the same inconsistencies between runs even for this simple example:
```
protocol FooProtocol {
    var a: Int? { get set }
    func doIt()
}

final class Foo: FooProtocol {
    var a: Int?
    func doIt() {
        print(a!)
    }
}

class Bar {
    private var foo: FooProtocol
    
    init(foo: FooProtocol = Foo()) {
        self.foo = foo
    }
    
    func doIt() {
        foo.a = 3
        foo.doIt()
    }
}

let bar = Bar()
bar.doIt()
```
gives me in about 10%-40% of the runs

```
main.swift:2:9: warning: Property 'a' is assigned, but never used
```
This file is a member of the target I pass to --targets
swift version is 5.3.2
I'm using periphery 2.4.3 (latest)

This is the output of 10 consecutive runs:

```
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

main.swift:2:9: warning: Property 'a' is assigned, but never used

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - By default, Periphery does not assume that all public declarations are in use. 
   You can instruct it to do so with the --retain-public option.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

main.swift:2:9: warning: Property 'a' is assigned, but never used

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - By default, Periphery does not assume that all public declarations are in use. 
   You can instruct it to do so with the --retain-public option.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

main.swift:2:9: warning: Property 'a' is assigned, but never used

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - By default, Periphery does not assume that all public declarations are in use. 
   You can instruct it to do so with the --retain-public option.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

main.swift:2:9: warning: Property 'a' is assigned, but never used

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - By default, Periphery does not assume that all public declarations are in use. 
   You can instruct it to do so with the --retain-public option.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
~/tmp/periphery periphery scan
* Inspecting project...
* Building Periphery...
* Indexing...
* Analyzing...

* No unused code detected.
```

**Comment by ileitch** [comment]
Thanks, I've reproduced this bug and I'm looking into it.

**Comment by aisohaikens** [comment]
Thanks for this fast fix!
