### ISSUE TITLE
Error inspecting Siri Message Intent

### ISSUE THREAD

**Issue by AdamPro13** [peripheryapp/periphery#25]
I'm receiving the following error with my project that has a Siri Message Intent extension:
`error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "productType", intValue: nil)], debugDescription: "Cannot initialize PBXProductType from invalid String value com.apple.product-type.app-extension.intents-service", underlyingError: nil))`.

Is this extension type not currently supported?

**Comment by ileitch** [comment]
This is an error from https://github.com/tuist/xcodeproj, you could please open an issue there and link to it?

**Comment by ileitch** [comment]
OK you win, I opened one: https://github.com/tuist/xcodeproj/issues/378

**Comment by ileitch** [comment]
This should be fixed in 1.4.0, could you give it a try?
