### ISSUE TITLE
Optional protocol methods always marked as unused

### ISSUE THREAD

**Issue by decanus** [peripheryapp/periphery#251]
I have optional methods in protocols like this

```swift
@objc protocol GroupsSliderDelegate {
    @objc optional func didTapGroupCreation()
}
```

This function is always marked as unused in the implementations even when calling the delegate protocol with:

```swift
delegate?.didTapGroupCreation?()
```

**Comment by crtgregoric** [comment]
I have observed the same issue in my project.

**Comment by ileitch** [comment]
I need to confirm, though I believe this is related to https://bugs.swift.org/browse/SR-13930
