### ISSUE TITLE
False positives from R.generated.swift

### ISSUE THREAD

**Issue by Bawenang** [peripheryapp/periphery#254]
I'm using https://github.com/mac-cain13/R.swift in my project. I've got tons of false positives from the script that is generated by the library, ie `R.generated.swift`.

**Comment by ileitch** [comment]
Can you please provide a concrete example of a portion of the generated code with a false positive, and the code that references that portion of generated code.

**Comment by ileitch** [comment]
Closing this due to lack of feedback.
