### ISSUE TITLE
Local Swift Packages support

### ISSUE THREAD

**Issue by AvdLee** [peripheryapp/periphery#258]
While running Periphery, I found out that referencing local packages for debugging breaks the setup:

> Error: Cannot calculate full path for file element "Vendor/CoreUIKit/CoreUIKit.xcodeproj" in source root: "."

We're referencing them locally to make them "development packages", so we can modify them easily.

**Comment by ileitch** [comment]
This error is actually coming from [xcodeproj](https://github.com/tuist/xcodeproj). Are you able to confirm that this error is also present when using xcodeproj directly?

**Comment by AvdLee** [comment]
I'm not experienced with `xcodeproj`, what would be the easiest way to reproduce that?

**Comment by ileitch** [comment]
By "package" you mean you're using the SwiftPM?

Or is this just a normal Xcode reference? If so, how is the `PBXFileReference` formed? In your main `project.pbxproj` look for the `PBXFileReference`, it should look something like this:

```
/* Begin PBXFileReference section */
        3CFA119125D197F40037F551 /* iOSProject.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = iOSProject.xcodeproj; path = Tests/XcodeTests/iOSProject/iOSProject.xcodeproj; sourceTree = "<group>"; };
```

**Comment by AvdLee** [comment]
Yes, a Swift Package Manager Package.

This is the file reference:

```
50EED7CC257520B500A6E25D /* CoreUIKit */ = {isa = PBXFileReference; lastKnownFileType = folder; name = CoreUIKit; path = Vendor/CoreUIKit; sourceTree = "<group>"; };
```

And this is how it looks in Xcode:

![image](https://user-images.githubusercontent.com/4329185/107345061-7b9d3780-6ac3-11eb-9e1b-840f38345915.png)

Let me know if you need any additional context.

**Comment by ileitch** [comment]
If this is an SPM package, I don't understand why it's trying to load `CoreUIKit.xcodeproj`. Did you generate this xcodeproj, is there perhaps another reference to it from the workspace?

**Comment by AvdLee** [comment]
@ileitch that was it, you put me on the right direction! Turns out, we used to integrate `CoreUIKit` as an Xcodeproj but we no longer did. However, likely due to merge conflicts, we didn't clean up the project correctly and a reference to the project was still somehow in the project file.

Manually removing those solved our issue!
