### ISSUE TITLE
False positive for initializers that are used via Self

### ISSUE THREAD

**Issue by almazrafi** [peripheryapp/periphery#264]
Example code:

``` swift
public struct Struct {

    public static let `default` = Self(foo: 123, bar: 456)

    public let foo: Int
    public let bar: Int

    private init(foo: Int, bar: Int) {
        self.foo = foo
        self.bar = bar
    }
}
```

Periphery marks initializer as unused:

```
Initializer 'init(foo:bar:)' is unused
```

<img width="679" alt="Xcode4" src="https://user-images.githubusercontent.com/23436967/107128651-67ddaf80-68d0-11eb-9e3d-710b51313d90.png">

Sample project: [PeripherySample.zip](https://github.com/peripheryapp/periphery/files/5937565/PeripherySample.zip)

#### Environment

Periphery: 2.4.1 (via Mint)
Swift: 5.3.2
Xcode: 12.4
macOS: 10.15.7

**Comment by ileitch** [comment]
This is due to a Swift bug, reported here: https://bugs.swift.org/browse/SR-14181
