### ISSUE TITLE
Should unused parameters of the open method be retained by retain-public option?

### ISSUE THREAD

**Issue by almazrafi** [peripheryapp/periphery#270]
Example code:

``` swift
open class Class {
    open func doSomething(with value: Int) { }
}
```

Periphery marks `value` as unused even with the `--retain-public` option:

<img width="677" alt="Снимок экрана 2021-02-07 в 21 22 39" src="https://user-images.githubusercontent.com/23436967/107155658-a6d03b80-698a-11eb-879f-7064f5a20f48.png">

#### Environment

Periphery: 2.4.1 (via Mint)
Swift: 5.3.2
Xcode: 12.4
macOS: 10.15.7

**Comment by ileitch** [comment]
Yes, absolutely. Good catch!
