### ISSUE TITLE
False positive "Property is unused" when protocol has property requirements

### ISSUE THREAD

**Issue by subdan** [peripheryapp/periphery#275]
I found an issue. When a protocol has property requirements periphery marks these properties as unused.

When I run `periphery scan` for the code listed below, I get the following warning:
`AppDelegate.swift:26:9: warning: Property 'someVar' is unused`
This is a false positive because this property is used.

```swift

import UIKit

@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        let someClass: SomeProtocol = SomeClass()
        someClass.someFunc()
        
        return true
    }

}

protocol SomeProtocol {
    var someVar: String! { get set }
    func someFunc()
}

final class SomeClass: SomeProtocol {

    var someVar: String!
    
    func someFunc() {
        print(someVar ?? "")
    }
}

```

**Comment by ileitch** [comment]
Is this warning for `someVar` in the `SomeProtocol` or `SomeClass`? The line 26 number does not match up with your example.

**Comment by subdan** [comment]
Sorry. `SomeProtocol`

```
protocol SomeProtocol {
    var someVar: String { get set } <<<----- warning: Property 'someVar' is unused
    func someFunc()
}
```

**Comment by ileitch** [comment]
In that case the warning is correct, `someVar` is redundant in the protocol because it is never accessed via an existential type, e.g 
```swift
let someClass: SomeProtocol = SomeClass()
print(someClass.someVar)
```
