### ISSUE TITLE
False positive for initializers used with explicit generic parameter

### ISSUE THREAD

**Issue by sdc-78** [peripheryapp/periphery#276]
```swift
public class Foo {
    let bar1: Bar1<Int>
    let bar2: Bar2<Int>
    let bar3: Bar3<Int>
    let bar4: Bar4<Int>

    public init(property: Int) {
        bar1 = Bar1(property: property)
        bar2 = Bar2<Int>(property: property)
        bar3 = Bar3(property: property)
        bar4 = Bar4<Int>(property: property)
    }

    public func foo() {
        print(bar1.property, bar2.property, bar3.property, bar4.property)
    }
}

struct Bar1<T> {
    let property: T
}

struct Bar2<T> {
    let property: T
}

struct Bar3<T> {
    let property: T

    init(property: T) {
        self.property = property
    }
}

struct Bar4<T> {
    let property: T

    init(property: T) { // false positive: Initializer 'init(property:)' is unused
        self.property = property
    }
}
```

In this example:
- `Bar1` and `Bar2` are identical and have an **implicit** initializer,
- `Bar3` and `Bar4` are identical (and not very different from `Bar1` and `Bar2`) and have an **explicit** initializer,
- `Foo` initializer uses `Bar1` and `Bar3` initializers **without** specifying explicitly the generic parameter `T`,
- `Foo` initializer uses `Bar2` and `Bar4` initializers by specifying **explicitly** the generic parameter `T`,
- `Periphery` incorrectly reports `Bar4` initializer as unused.

Environment:
- Periphery 2.4.2 (via CocoaPods)
- Xcode 12.4
- Swift 5.3.2
- macOS 10.15.7

**Comment by ileitch** [comment]
This is due to [SR-7093](https://bugs.swift.org/browse/SR-7093). There's no workaround unfortunately, however we were already retaining all constructors in generic classes to avoid the false positives, so I've done the same for structs.
