### ISSUE TITLE
Don't build project with iOS 14 code

### ISSUE THREAD

**Issue by agrivenniy** [peripheryapp/periphery#280]
Hello. I get the following attempt when trying to use Periphery. If I comment out this code, everything works. If I remove the execution of Periphery from the build phase, this code is built correctly.
<img width="1100" alt="Screenshot 2021-03-11 at 21 01 05" src="https://user-images.githubusercontent.com/80480889/110832947-ec936300-82ac-11eb-9eb2-7fc25731e86d.png">

**Comment by ileitch** [comment]
So you're using Periphery as a step in an Xcode build phase correct? Are you able to run Periphery without error from the command line?

**Comment by agrivenniy** [comment]
Yes, I using Periphery as a step in an Xcode build phase.
If I run it from command line, I got the same problem.
<img width="883" alt="Screenshot 2021-03-13 at 16 58 04" src="https://user-images.githubusercontent.com/80480889/111032730-b7a71d80-841e-11eb-99ac-df8440beca66.png">
<img width="283" alt="Screenshot 2021-03-13 at 17 01 40" src="https://user-images.githubusercontent.com/80480889/111032738-c1c91c00-841e-11eb-8e59-b46822505e55.png">

**Comment by ileitch** [comment]
It looks like you may need to explicitly instruct xcodebuild to build for iOS 14, e.g
```
periphery scan ... -- -destination 'platform="iOS Simulator",name="iPhone 12",OS=14.4'
```

**Comment by ileitch** [comment]
did you manage to resolve this?
