### ISSUE TITLE
Run periphery for iOS-specific Swift Package

### ISSUE THREAD

**Issue by MarcoEidinger** [peripheryapp/periphery#281]
Hi,

I'd like to run periphery against a Swift package that is platform-specific to iOS and therefore should be built with `xcodebuild` and not `swift build` (which is chosen by periphery).

This Swift package does not have an Xcode project file as such cannot be generated with `swift package generate-xcodeproj` as the package uses binary targets.

Building this Swift package works with `xcodebuild -scheme <PackageName> -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build` and therefore I was hoping that something similar like `periphery scan -- -scheme <PackageName> -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build` would work but it doesn't :(

Is using periphery in such a scenario possible otherwise?

**Comment by ileitch** [comment]
Sorry for the late response. I did some digging into this, and it looks like it should be possible to support, though I haven't ha time to finish off the implementation yet.

**Comment by ileitch** [comment]
Sorry I've not looked into this any further. The first time I looked I think it looked like quite a lot of effort to implement. I've only had very limited time for Periphery recently, and I've spent that time focusing on fixing bugs. If this is blocking a lot of people, please speak up so that I can get a good signal how important this is.

**Comment by tamc** [comment]
> If this is blocking a lot of people, please speak up so that I can get a good signal how important this is.

Ideally I'd be able to do this, but it isn't exactly blocking.

**Comment by MarcoEidinger** [comment]
I am not using Periphery due to this limitation. I'd like to see this feature request comes to life but I understand that this might not happen if not enough people are interested in

**Comment by aronhoff** [comment]
`periphery scan -- -sdk iphonesimulator` worked for me. (My workspace and scheme are specified in the .yml file)

**Comment by Sherlouk** [comment]
Thanks @aronhoff, that solution didn't work for me verbatim but it gave me inspiration to try some other build parameters.

I managed to get setup and working with this command:

```
swift run periphery scan --setup -- -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios15.0-simulator"
```

Of course, once setup (and the information is stored in the `.yml` file) then I can simply run `swift periphery scan` and it all works 🎉

**Comment by V8tr** [comment]
Had similar issue, but none of the above worked cuz Periphery was using `swift build` instead of `xcodebuild`. The way I solved it:

Build the SPM package manually via `xcodebuild`:

```swift
xcodebuild -scheme MyScheme -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro' -derivedDataPath "../dd"
```

Then use the combination of `--skip-build` and  `--index-store-path` to target the produced index store:

```swift
periphery scan --skip-build --index-store-path "../dd/Index/DataStore/"
```

**Comment by david-palmer79** [comment]
@V8tr Thank you, for this! Your solution works great.

**Comment by MarcoEidinger** [comment]
@V8tr many thanks to as those instructions also work for me !!

@ileitch I raised a PR to add such explanation to the README.
