### ISSUE TITLE
Add ability to create baseline for code smells

### ISSUE THREAD

**Issue by xanderblinov** [peripheryapp/periphery#283]
After first start of periphery we have a lot of code smells. So it may take a lot of time to fix it all. Could you please provide a "baseline" feature to ignore this warnings  at subsequent reports and fix it later

Example of baseline implementation and using at [Kotlin static analysis tool](https://detekt.github.io/detekt/baseline.html)

**Comment by ileitch** [comment]
13 votes, most of which are also suspiciously Russian sounding 🤣 

Anyway, this really doesn't need to be a feature of Periphery itself. Very easy to achieve the same result using grep:

```
periphery scan --quiet > baseline.txt
periphery scan --quiet | grep -vf baseline.txt
```

**Comment by ileitch** [comment]
Actually, I'm reopening this... it might be nice to have such a feature that isn't susceptible to line/column changes.

**Comment by ileitch** [comment]
Closing again, sorry but I'm unlikely to ever implement this as I've very little time. It's not a bad idea, but it's also very simple to manage yourself using other tools.
