### ISSUE TITLE
Getting Error: parsingFailed running on Xcode 12.3 on version 2.4.3

### ISSUE THREAD

**Issue by jianyaoang** [peripheryapp/periphery#286]
Installed latest version: 2.4.3, and ran command: `periphery scan --workspace "[PATH].xcworkspace" --schemes "SCHEME" --targets "TARGET" --verbose`. Also tried running `periphery scan --workspace "[PATH].xcworkspace.xcworkspace" --schemes "SCHEME" --targets "TARGET" --retain-objc-accessible --format xcode --verbose`, same error produced.

```
[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0
[shell] /usr/bin/env xcodebuild -version
Xcode 12.3
Build version 12C33
[version] 2.4.3
[configuration]
--- # .periphery.yml
build_arguments: []
clean_build: false
disable_update_check: false
format: xcode
index_exclude: []
index_store_path: null
project: null
quiet: false
report_exclude: []
retain_assign_only_properties: false
retain_objc_accessible: false
retain_public: false
retain_unused_protocol_func_params: false
schemes:
- [SCHEME_NAME]
skip_build: false
strict: false
targets:
- [TARGET_NAME]
verbose: true
workspace: [PATH_TO_WORKSPACE].xcworkspace

* Inspecting project...
[xcode:workspace] Loading [PATH_TO_WORKSPACE].xcworkspace
[xcode:project] Loading [PATH_TO_XCODEPROJ].xcodeproj
Error: parsingFailed

```

Anything that I can try or missed out? Thank you!

**Comment by ileitch** [comment]
This is an error from the (https://github.com/tuist/XcodeProj)[XcodeProj] library. I recently just updated it to the latest version in master. Would you be willing to give it a try?

* Clone the Periphery repo
* Run `swift build`
* You can then use the periphery binary at `.build/debug/periphery`

**Comment by jianyaoang** [comment]
@ileitch Thanks for the prompt reply! 

I followed the steps you stated above. Just wanted to clarify, meaning run `.build/debug/periphery .......` instead of `periphery scan .......`? I tried doing that, unfortunately it doesn't work as well. Logs is as below:

```
.build/debug/periphery scan --workspace "[PATH_TO_WORKSPACE].xcworkspace" --schemes "[SCHEME]" --targets "[TARGET]" --retain-objc-accessible --format xcode --verbose

[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0
[shell] /usr/bin/env xcodebuild -version
Xcode 12.3
Build version 12C33
[version] 2.4.3
[configuration]
--- # .periphery.yml
build_arguments: []
clean_build: false
disable_update_check: false
format: xcode
index_exclude: []
index_store_path: null
project: null
quiet: false
report_exclude: []
retain_assign_only_properties: false
retain_assign_only_property_types: []
retain_objc_accessible: true
retain_public: false
retain_unused_protocol_func_params: false
schemes:
- [SCHEME]
skip_build: false
strict: false
targets:
- [TARGET]
verbose: true
workspace: [PATH_TO_WORKSPACE].xcworkspace

* Inspecting project...
[xcode:workspace] Loading [PATH_TO_WORKSPACE].xcworkspace
[xcode:project] Loading[PATH_TO_XCODEPROJ].xcodeproj
Error: parsingFailed
```

**Comment by ileitch** [comment]
Yes, using `.build/debug/periphery` is correct. This error is coming from AEXML, so some XML file in your project cannot be parsed. However I don't know which file that might be, and where in the program it's being called. Therefore we'll need to use lldb to obtain some stack traces.

To start lldb (replace arguments with correct values, make sure `--verbose` is present):

```
lldb -- .build/debug/periphery scan --workspace "[PATH].xcworkspace" --schemes "SCHEME" --targets "TARGET" --verbose
```

At the lldb prompt, type the following (you'll need to type them one by one, copy & paste all at once will not work):

```
br s -E swift
br com add 1
bt
c
DONE
run
```

once that has finished running, please report back with the entire output.

**Comment by ileitch** [comment]
Closing this due to lack of feedback.

**Comment by daniel-tavares-nl** [comment]
@ileitch @jianyaoang 
I found out we had the above issue. 
Essentially XXX.xcodeproj>project.xcworkspace>contents.xcwordspacedata was empty in my case.
Adding the below fixed it.
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "self:XXXX.xcodeproj">
   </FileRef>
</Workspace>
----
``` 
public convenience init(path: Path) throws {
        if !path.exists {
            throw XCWorkspaceError.notFound(path: path)
        }
        let xcworkspaceDataPaths = path.glob("*.xcworkspacedata")
        if xcworkspaceDataPaths.isEmpty {
            self.init()
        } else {
            try self.init(data: XCWorkspaceData(path: xcworkspaceDataPaths.first!))
        }
    }
 ```
 It was hitting an empty data on the above and AEXML couldn't parse empty xml, hence the error

**Comment by ileitch** [comment]
@daniel-tavares-nl Thank you for sharing your solution. Could you please report this issue to the https://github.com/tuist/xcodeproj project? Periphery doesn't read xcwordspacedata files directly.
