### ISSUE TITLE
The addition of CODE_SIGNING_ALLOWED="NO" is breaking the xcodebuild

### ISSUE THREAD

**Issue by David-A-RogersHS2** [peripheryapp/periphery#298]
When I run Periphery, the build of my code fails with
: no identity found
error: Code signing failed.

I copied the build command Periphery is using for my code and removed the CODE_SIGNING_ALLOWED flag and the build runs successfully.

I didn't see a way to tell it not to disallow code signing.

**Comment by ileitch** [comment]
With #299 merged you can now override this setting with the following:
periphery scan .... -- 'CODE_SIGNING_ALLOWED="YES"'
