### ISSUE TITLE
UIViewController sub-subclasses false hit for required init

### ISSUE THREAD

**Issue by simonmoss49** [peripheryapp/periphery#30]
Xcode 10.1, anywhere in the project that I am using a class like this `UIViewController` > `MySubViewController` > `MySubSubViewController` - implementation of `required init?(coder aDecoder: NSCoder)` is falsely flagged as unused in `MySubSubViewController`.

It also appears that any methods called exclusively from within those inits are also falsely flagged.

Run script contains ` --format xcode --no-retain-objc-annotated  `

**Comment by ileitch** [comment]
I'm unable to reproduce this in v2.0 with the following code:

```swift
class ViewControllerOne: UIViewController {
    required init() {
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

class ViewControllerTwo: ViewControllerOne {
    required init() {
        super.init()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

class ViewControllerThree: ViewControllerTwo {
    required init() {
        super.init()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```
