### ISSUE TITLE
When will a new cocoapod be pushed?

### ISSUE THREAD

**Issue by David-A-RogersHS2** [peripheryapp/periphery#302]
Your pull #293 did indeed fix my problem with using Periphery. But, of course, I had to hand-build that. I won't be allowed to check that in. I'll need to wait until there's a cocoapod with that fix in it.

**Comment by ileitch** [comment]
Hopefully this week, I'm still working on a new feature.

**Comment by David-A-RogersHS2** [comment]
Cool. Thanks. Good luck on the new feature.
