### ISSUE TITLE
Integration with Jenkins CI

### ISSUE THREAD

**Issue by nysander** [peripheryapp/periphery#31]
Hello, as I am building full stack solution for keeping high code quality standards of my swift apps and I found your project which I find suitable for my Jenkins CI appliance. 

I wanted to ask if it is possible to add XML formater for example in Checkstyle 4.3 XML format to easily integrate with jenkinsci/warnings-ng-plugin.

**Comment by ileitch** [comment]
Yeah that'd be a great addition, PRs are welcome!

**Comment by nysander** [comment]
Atm my swift knowledge is too little to be able to make pr for this but if nobody else will do it I will try to do it when I learn more

**Comment by nysander** [comment]
here are implementations of check style report in tools I use in my Jenkins CI

IBLinter: https://github.com/IBDecodable/IBLinter/blob/master/Sources/IBLinterKit/Reporters/CheckstyleReporter.swift

SwiftLint: https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Reporters/CheckstyleReporter.swift
