### ISSUE TITLE
False positives for Protocol type aliases

### ISSUE THREAD

**Issue by trant** [peripheryapp/periphery#32]
```swift
typealias PersistenceProtocol = ThreadPersistenceProtocol & MessagePersistenceProtocol

struct Persistence: PersistenceProtocol {
 (...)
}
```

The Persistence struct is being used everywhere but I am still getting warnings for PersistenceProtocol, ThreadPersistenceProtocol, MessagePersistenceProtocol being unused

**Comment by booiiing** [comment]
Isn't this a duplicate of #10?
