### ISSUE TITLE
Computed properties that called by protocol are reported as unused

### ISSUE THREAD

**Issue by yuri-qualtie** [peripheryapp/periphery#320]
We have 2 cases where computed properties are reported as unused. 
We double checked that these properties are used by display in UI 

1. Case 1: Identifiable protocol with `id`

We conform to Identifiable in following way: 
```
 enum SomeEnum: String, Identifiable, CaseIterable {
    public var id: String { rawValue }
    case caseOne
    case caseTwo
}
```
Next in the code we use it as:
```
 ForEach(SomeEnum.allCases) {
    Text($0.rawValue).tag($0)
 }
```

2. Case 2: Computed property implemented in protocol extension or in some class

We have protocol:
```
protocol SomeStringsProtocol {
    var defaultMessage: String { get }
    var message: String { get }
}
```
extension with implementation for `defaultMessage`:
```
extension SomeStringsProtocol {
    var defaultMessage: String { "Default Message" }
}
```
and 2 implementations:
```
class SomeStringsOne: SomeStringsProtocol {
    var message: String { "Message One" }
}

class SomeStringsTwo: SomeStringsProtocol {
    var message: String { "Message Two" }
}
```

we use it as:

```
    var messages: [SomeStringsProtocol] = [SomeStringsOne(), SomeStringsTwo()]

   ForEach(messages.indices, id: \.self) {
      Text(messages[$0].defaultMessage).tag($0)
      Text(messages[$0].message).tag($0)
   }
```

When we run following command:
```
periphery scan --strict --clean-build --disable-redundant-public-analysis
```
We see in results:
```
./ComputedPropertiesTest/ContentView.swift:29:27: warning: 'getter:id' is unused
./ComputedPropertiesTest/ContentView.swift:47:25: warning: 'getter:message' is unused
./ComputedPropertiesTest/ContentView.swift:54:25: warning: 'getter:message' is unused
```

Also we created a test repository to reproduce issues: https://github.com/ruslan-qualtie/ComputedPropertiesTest
You can run following command from project's root: 
```
Pods/Periphery/periphery scan --strict --clean-build --disable-redundant-public-analysis
```

Could you please investigate and provide fix for these issues? Thank you in advance!

**Comment by ileitch** [comment]
Hey Yuri, any declarations with `getter:` in the name should never be shown as a result, this is a bug. What version of Periphery are you using? It's possible this is already fixed in 2.5.0.

**Comment by ileitch** [comment]
I just tried the example project (many thanks for that!), and I'm getting the same results, so this is absolutely still a bug.

**Comment by yuri-qualtie** [comment]
Hey Ian, thank you for quick reply. We are on `Periphery (2.5.0)`.

**Comment by ruslan-qualtie** [comment]
[Test project]( https://github.com/ruslan-qualtie/ComputedPropertiesTestl) updated. Now we are on `Periphery (2.5.1)` with same results.

**Comment by ileitch** [comment]
I've just released a fix for this in 2.5.2.

**Comment by yuri-qualtie** [comment]
@ileitch thank you for quick fix! We will pull new version via cocoa pods today and check

**Comment by ruslan-qualtie** [comment]
Tested. All is OK. Thanks!
