### ISSUE TITLE
false positive NSEntityMigrationPolicy, ValueTransformer 

### ISSUE THREAD

**Issue by mateuszmackowiak** [peripheryapp/periphery#357]
Hi, great work on the project.
But sill have some false positives on classes that are used in core data.
`NSEntityMigrationPolicy` subclasses aren't easy to analyse in therms weather there are used or not.
Basically the are defined in a in `.xcmappingmodel` package in `xcmapping.xml` file and except from that it is impossible to locate it. Xcode also dose not validate the existents of the class and it crashes the app when this specific migration is done. 
It would be a great addition to the periphery project to validate this. 

Also `ValueTransformer` subclasses of are not referred anywhere in code. Just a reference In an xml file `content` in an `.xcdatamodel` package:
`<attribute name="location" attributeType="Transformable" valueTransformerName="App.LocationValueTransformer" customClassName="CoreDataLocation"/>`

Unfortunately I could not possible add the tool as a reliable tool for verifying without this logic because the removal of this files would just crash when running the app.

**Comment by ileitch** [comment]
Hey @mateuszmackowiak, thanks for reporting this. Periphery doesn't currently analyze CoreData files, but I will absolutely implement this very soon.

**Comment by ileitch** [comment]
Implemented in #359 and #360. @mateuszmackowiak would you be willing to give master a try?
