### ISSUE TITLE
false positives for methods in class extension

### ISSUE THREAD

**Issue by David-A-RogersHS2** [peripheryapp/periphery#358]
This small class shows a handful of false positives. Using 2.6.0.

![image](https://user-images.githubusercontent.com/20795729/123137401-883e7e80-d419-11eb-9d49-35e71cba76dc.png)

**Comment by ileitch** [comment]
Are you using `--retain-objc-accessible`? If so, it looks like the entire `TheClass` is unused. It can't be reported as unused because it inherits from `NSObject` via `UIView`.

**Comment by ileitch** [comment]
Closing due to no response.
