### ISSUE TITLE
Could not found extension declaration

### ISSUE THREAD

**Issue by codwam** [peripheryapp/periphery#36]
public enum Alignment : Int {
    
    
    case center
    
    case left
    
    case right
    
    case fill
    
    @available(iOS 11.0, *)
    case leading
    
    @available(iOS 11.0, *)
    case trailing
}

extension Alignment {// This could not found in ScanResult
    func action() {
        print(self.rawValue)
    }
    
    static func staticAction() {
        print(Alignment.self)
    }
}

It effects the `Protocol`, `Enum`, `Struct` etc...

**Comment by ileitch** [comment]
Can you please clarify the problem you're having? I'm not sure what you mean by "This could not found in ScanResult".

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this.
