### ISSUE TITLE
scan error

### ISSUE THREAD

**Issue by angBiu** [peripheryapp/periphery#367]
error: The index store at '/Users/*/Library/Caches/com.github.peripheryapp/DerivedData-7c88ceed-7c88ceed/Index/DataStore' does not contain data for the following targets: *. Either the index store is outdated, or you have requested to scan targets that have not been built.

**Comment by ileitch** [comment]
Can you please provide some more context, what options are you passing to periphery?

**Comment by angBiu** [comment]
i have fix it. Replace the DataStore from the DerivedData.

**Comment by mumuwanglin** [comment]
> i have fix it. Replace the DataStore from the DerivedData.

What do you mean, what should I do

**Comment by iSapozhnik** [comment]
@mumuwanglin I think what @angBiu meant is following. You need to take DataStore folder from your `/Users/<UserName>/Library/Developer/Xcode/DerivedData/<AppName>/Index/DataStore` and copy-paste to `/Users/<UserName>/Library/Caches/com.github.peripheryapp/DerivedData-2de75555-2de75555/Index/DataStore` and then call `periphery scan` again

**Comment by ileitch** [comment]
That's a really bad idea, and you'll likely get weird results. Given that OP didn't provide any more details and can't give any guidance here, but copying the index from another build definitely isn't a solution.

**Comment by iSapozhnik** [comment]
Yeah feels hacky...
