### ISSUE TITLE
How to exclude a folder (including its subfolders)

### ISSUE THREAD

**Issue by haihack** [peripheryapp/periphery#372]
How to exclude a folder (including its subfolders)?

Should I exclude every single of subfolders instead?

**Comment by ileitch** [comment]
Yes I'm afraid you need to specify each subfolder, unfortunately recursive globs `**` aren't supported.

**Comment by ileitch** [comment]
This is now supported in 2.8.0, you can do for example `--index-exclude "Sources/Generated/**/*.swift"`
