### ISSUE TITLE
Allow excluding xib files from index

### ISSUE THREAD

**Issue by monchote** [peripheryapp/periphery#373]
Right now [`index-exclude` only works for swift files](https://github.com/peripheryapp/periphery/issues/212#issuecomment-880853409) but there are instances excluding xib files too can help Periphery detect more unused code as described [here](https://github.com/peripheryapp/periphery/issues/212#issuecomment-880844031).

> I'm working on a project where every UIView or UIViewController has an associated xib file. For example: as the UIView subclass declared in MyView.swift is referenced by MyView.xib, Periphery doesn't mark MyView as unused, even though it never gets instantiated anywhere else in the codebase.
>
>I've tried --index-exclude "*.xib" but it didn't help.

**Comment by ileitch** [comment]
This is now supported in 2.8.0, you can simply do `--index-exclude "**/*.{xib,storyboard}"`.

**Comment by monchote** [comment]
Thanks! I've just tried it and it works exactly as expected 🙏 🙏 🙏

**Comment by ileitch** [comment]
Whoop, thanks for the sponsor 😊
