### ISSUE TITLE
How to specify Destination iOS simulator in .periphery.yml

### ISSUE THREAD

**Issue by paultas** [peripheryapp/periphery#388]
Before I did it this way and it worked

```
xcargs:
  SUPPORTS_MACCATALYST=NO
  -destination 'platform=iOS Simulator,name=iPhone 8'
```

But currently when I run it I see

`warning: .periphery.yml: invalid key 'xcargs'`

What is the new way to do it?

**Comment by paulofierro** [comment]
@paultas I had a similar issue and [learned that you](https://github.com/peripheryapp/periphery/issues/246#issuecomment-748473092) now need to pass the `--` terminator instead of `xcargs`, so this might work for you:
```
periphery scan -- -destination platform=\"iOS Simulator,name=iPhone 8\"
```

I don't know how to add that to the `.periphery.yml` file, or if its supported.

**Comment by ileitch** [comment]
Hey @paultas, the yaml key is now `build_arguments`.

**Comment by nharbo** [comment]
It would be something like:
```
build_arguments:
- -destination platform="iOS Simulator,name=iPhone 14,OS=latest"
```
