### ISSUE TITLE
SourceKit error

### ISSUE THREAD

**Issue by arguiot** [peripheryapp/periphery#39]
When I try to scan my project, here is the error I'm always getting:
```
SourceKit editorOpen request failed for file '/Users/arguiot/GitHub/StudIO/StudIO/Extensions/Compression.swift': Retrieving both the document structure and a syntax tree at the same time is not supported. Use the syntax tree to compute the document structure.
```

**Comment by ileitch** [comment]
Fixed in 1.5.1.

**Comment by arguiot** [comment]
Ok, it's fixed... but now I'm getting this:
```
error: unknownTokenKind("ellipsis")
* Inspecting project configuration...
* Building StudIO...
* Indexing...
```

**Comment by booiiing** [comment]
@arguiot: I got the `unknownTokenKind` error, too. It only happens with XCode 11, though. `xcode-select` back to XCode 10.3 and it worked for me.

**Comment by arguiot** [comment]
Yeah, but the issue is because of Xcode 11 I guess. My app only compiles with Xcode 11, so your trick won’t work for me 🤔
