### ISSUE TITLE
False positive for static string constant

### ISSUE THREAD

**Issue by bottlehall** [peripheryapp/periphery#391]
Definition is:
```swift
struct C {
     // ...
    struct Msg {
        static let CannotDeleteCurrentUnit = "Cannot delete the currently assigned unit"
    }
}
```
Usage is:
```swift
request.setMessage(C.Msg.CannotDeleteCurrentUnit)
```
 `periphery scan` reports:

`... warning: Property 'CannotDeleteCurrentUnit' is unused`

Many others used in identical context are not being reported as unused.

**Comment by ileitch** [comment]
Are you sure the file containing the call `request.setMessage(C.Msg.CannotDeleteCurrentUnit)` is a member of a target that Periphery has indexed? You can run with `--verbose` to see if this file has been indexed.

**Comment by bottlehall** [comment]
Ran with --verbose and the file is being included.

**Comment by ileitch** [comment]
Is the function containing this call unused?

**Comment by bottlehall** [comment]
Ah, sorry, yes, it was temporarily unused.
