### ISSUE TITLE
static property is used in Dictionary for optional value but marked as unused

### ISSUE THREAD

**Issue by naiyu-wang** [peripheryapp/periphery#392]
Hi i have created a struct Key to store all the string keys inside my event class.
And i assign those keys in an existed dictionary when i needed to add additional but also optional info.
As i use it, i got a warning `Property 'xxx' is assigned, but never used.`

```swift
class EventHelper { ... }

extension EventHelper {
  struct Key {
    static let name = "name"
    static let email = "user_email" <<< // Property 'email' is assigned, but never used.
  }
}

extension EventHelper: UserEvent {

  func recordUserEvent() {
   let param = [EventHelper.Key.name: "Apple"]
   record(param: param)
  }

  private func record(param: [String: Any]) {
    var newDict = param
    newDict[EventHelper.Key.email] = User?.email <<< // the Key.email is used here
   sendEvent("userEvent", newDict)
  }

 func sendEvent(_ name: String, param: [String: Any]) {...}

}
```

i had tried several ways to avoid the warning, this one works but will cause another warning from Xcode:
```swift
private func record(param: [String: Any]) {
    var newDict: [String: Any] = [EventHelper.Key.email: User?.email] <<< // Expression implicitly coerced from 'String?' to 'Any'
    newDict.map { param... }
   sendEvent("userEvent", newDict)
  }
```
i prefer to use the original one to fit our coding style and i think it makes more sense. i'm wondering why is the original one not working?

**Comment by ileitch** [comment]
Unfortunately this is caused by a known bug in Swift: https://bugs.swift.org/browse/SR-14162?filter=13600. I plan to investigate fixing this myself soon, though if I do succeed it won't be available until Swift 5.6 is released.
