### ISSUE TITLE
How run it on M1 mac

### ISSUE THREAD

**Issue by tomCompsoft** [peripheryapp/periphery#396]
I can run my project in M1 mac by adding arm64 as Excluded Archutectures

[peview](https://imgur.com/a/5EMFkWh)

but I can run periphery.

I get error:

`warning: None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'IKAWA-Home' from project 'IKAWApp')
warning: None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'Charts' from project 'Charts')
** BUILD FAILED **`

**Comment by ileitch** [comment]
How did you install Periphery?

**Comment by tomCompsoft** [comment]
via CocoaPods

**Comment by ileitch** [comment]
CocoaPods uses a prebuilt binary, which includes arm64 support:
```
$ lipo -info periphery
Architectures in the fat file: periphery are: x86_64 arm64
```

I think the error you're getting is from Xcode, and not Periphery. It's saying that for the target `Charts`, `ARCHS` is `arm64` but also `EXCLUDED_ARCHS` is `arm64`, so effectively there's no architecture available. I suggest you take a closer look at your Xcode configuration.

**Comment by infinigent-solutions** [comment]
@ileitch I installed Periphery using Homebrew. Still it does not run

**Comment by tomCompsoft** [comment]
the solution was:

`arch -x86_64 pod install`

**Comment by infinigent-solutions** [comment]
@tomCompsoft @ileitch Using Cocoapods installation, the script fails on my MacBook Pro M1 system

`periphery scan --workspace MyApp.xcworkspace --schemes MyApp --targets MyApp --format xcode`

**Comment by dromerobarria** [comment]
Any news, same problem with 
` None of the architectures in ARCHS (arm64) are valid.`
