### ISSUE TITLE
[Question] Show type public properties which should be private

### ISSUE THREAD

**Issue by ez-nx** [peripheryapp/periphery#409]
Hi all,
Is there a way with Periphery do detect and show type public properties which could be marked as private (using only inside type).
Thanks.

**Comment by ileitch** [comment]
Periphery does detect [redundant public accessibility](https://github.com/peripheryapp/periphery#redundant-public-accessibility), however it does not tell you whether the declaration should be `internal`, or `private` - that's up to you to decide.

It sounds more like what you're asking for is redundant _internal_ accessibility analysis, which I think should be possible to implement, though I'm not sure it'd be super useful.

**Comment by ileitch** [comment]
Closing this, I think redundant _internal_ accessibility analysis is a little too niche, but I'm more than happy to be convinced otherwise.
