### ISSUE TITLE
Periphery does not run on macOS Catalina

### ISSUE THREAD

**Issue by Sam-Spencer** [peripheryapp/periphery#41]
New security and sandboxing features on macOS Catalina prevent periphery from running on the system. The app must be updated with conformance to the new security protocols in order to be allowed to run.

**Comment by ranunez** [comment]
@Sam-Spencer I've just had to go to Settings -> Security & Privacy, and allow it from there.

**Comment by Sam-Spencer** [comment]
Oof! Whoops, didn't realize that was working now on beta 3 (forgot about it cause it hadn't worked in beta 1). Thank you!
