### ISSUE TITLE
Exclude methods

### ISSUE THREAD

**Issue by jaroslavas** [peripheryapp/periphery#42]
Is it possible to exclude methods or maybe methods that implement a protocol? 
Example:
```
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
```
Most of the time view controller has only one table, so it actually doesn't need the `tableView` parameter.
Or is there any other solution to get rid of such warnings?

**Comment by FloriVoss** [comment]
I think this is a great idea.  

A workaround is to simply replace the unused label with _, i.e. "_ _: UITableView"

**Comment by QuentinBM** [comment]
I would be great to be able to disable analysis for a sequence of lines with something like.
// periphery:disable
..
..
// periphery:enable

**Comment by ileitch** [comment]
This is now supported in version 2.0.1, see https://github.com/peripheryapp/periphery#comment-commands

**Comment by QuentinBM** [comment]
Terrific !!!! Thanks for all this work.
