### ISSUE TITLE
Periphery reports positive when using preprocessor macros

### ISSUE THREAD

**Issue by iressler** [peripheryapp/periphery#421]
If a property is only used in a configuration that periphery doesn't build (e.g. it builds debug by default and not release) periphery will report it as unused.

It is trivial to reproduce, for example here is a sample Swift file and resulting periphery output:
**`ContentView`**:
```Swift
struct ContentView: View {
  private var someText = "release"

  var body: some View {
    #if DEBUG
    // Used in debug builds
    Text("Hello")
    #else
    // Used in release builds
    Text(someText)
    #endif
  }
}
```

**`Periphery output`**:
```sh
$ periphery version
2.8.1
$ periphery scan
* Inspecting project...
* Building Periphery-Preview-Provider-Global-Function...
* Indexing...
* Analyzing...

<repo_path>/Periphery-Preview-Provider-Global-Function/Periphery-Preview-Provider-Global-Function/ContentView.swift:11:15: warning: Property 'someText' is unused
```

I'm pretty sure this is expected, however I couldn't find this documented in the README or any issues. So I wanted to report it to get an answer (or directed to an existing answer) and at least have it documented here, if not added into the README.

**Comment by ileitch** [comment]
Unfortunately this is expected behavior. I've updated the README, thanks for reporting this 👍

**Comment by iressler** [comment]
Thanks for the README update!
