### ISSUE TITLE
Exact path of a file in --report-exclude no longer works

### ISSUE THREAD

**Issue by TomQDRS** [peripheryapp/periphery#425]
Hi there, I believe this is a bug that's been introduced for a little while, but just now I had the time to narrow it down and report it.

**What happens?**

I have a file I want to exclude from the report. That file's location is `../Pod/Classes/Util/Filename.swift`. Adding it to `--report-exclude` via that path doesn't actually exclude it from the report. I verified that the path and file name is correct.

**Is there a workaround?**

To fix the issue, I replace one path component with "**". For example, `../Pod/Classes/**/Filename.swift`. Now the file is properly excluded from the report. This works with any path component.

**What's supposed to happen?**

I would like the file to be excluded with the full path, not replacing any components with "**".

**What Version of Periphery are you using?**

2.8.2

**Comment by ileitch** [comment]
Could you please give some more detail on your project structure? Periphery should be run from the project root, so it's a little odd that you'd be referencing a file from a parent directory.

**Comment by TomQDRS** [comment]
Hi ileitch! Yes, our project structure is a bit unusual because of how we develop certain parts of a bigger application independently from each other. Basically, what is normally worked on as a "project" is just an example setup of the App our code will be a part of, and we develop in another folder called "Pod". The structure is this:

```
root
│   README.md
│   ProjectName.podspec  
│
└───Pod
│   │   .swiftlint.yml
│   │
│   └───Assets
│   └───Classes
│          └───Util
│               │   Filename.swift
│   
└───Example
    │   ProjectName.xcworkspace
    │   ...
```
