### ISSUE TITLE
False positive function call on optional

### ISSUE THREAD

**Issue by FloriVoss** [peripheryapp/periphery#43]
Great tool!  However, I am finding some issues with functions called from optionals...

 if let container: DetailContainerView = parent as? DetailContainerView {
   container.updateToolbar(enable: enable)
 }

updateToolbar(enable: Bool) function on DetailContainerView is marked as unused.

**Comment by ileitch** [comment]
I'm unable to reproduce this using Periphery 1.8.0 and Xcode 12.2. What versions are you using?

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this.
