### ISSUE TITLE
Cannot calculate full path for file element for a locally referenced Xcode Project

### ISSUE THREAD

**Issue by ski081** [peripheryapp/periphery#435]
Hi. We have a large iOS Xcode workplace/project. We have several dynamic frameworks (each are their own Xcode project) referenced in the main project by dragging them into the main project. When I try to run a `scan` command from Terminal, I get the following output for one of the frameworks:

```
Cannot calculate full path for file element "Modules/{module name}/{module name}/{framework project name}.xcodeproj" in source root: "{path to source root}"
```

{module name}, {framework project name}, and {path to source root} have been replaced for privacy reasons, but I have validated that the project file is available at the specified path. I've also tried removing and re-adding the project file (and removing all references to the project from the pbxproj manually before I added it back in). I've tried running the command with `--verbose` enabled as well, but I don't get any more information from the output.

Is there anything else I can try?

**Comment by ileitch** [comment]
This error is coming from Xcodeproj, specifically this line: https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Objects/Files/PBXFileElement.swift#L184. Either your pbxproj contains an invalid reference, or your project is using some structure that Xcodeproj does not understand. Perhaps you could show me some portions of your pbxproj.

Look for the line that references the `.xcodeproj`, it should contain `isa = PBXFileReference` and `sourceTree = "<group>"` - what's the `path` attribute here?

At the start of the line should be an ID, something like `08B779835760A818E59969D1`. Find all other occurrences of this string within the file, please show me those lines, along with some surrounding context. If the ID is within a `children`, there should also be an `isa` a few lines above, along with a `BA1E76638FEE70CBAD8B9592 /* Foo */ = {` line , please provide those too.

**Comment by ski081** [comment]
I was able to get past this by completely removing references to the framework from the project file. I deleted it from the embed section in target build settings and then went through and manually cleaned up all references to it in the project file with a text editor. Thank you! 

I have a follow up question. Please let me know if you'd like me to open a separate issue for this. When I run the `scan` command with my workspace, scheme, and target specified, I get a build error on CodeSign. It looks like it's trying to build to `arm64`. Is there a way I can specify to build for the simulator to skip the codesigning step?

Again, thanks so much for your help!

**Comment by ileitch** [comment]
Yep, you can pass build arguments to `xcodebuild` like this `periphery scan .. -- -foo -bar`
