### ISSUE TITLE
False positive for callAsFunction methods

### ISSUE THREAD

**Issue by pm-dev** [peripheryapp/periphery#438]
https://github.com/apple/swift-evolution/blob/main/proposals/0253-callable.md

Swift 5.2 added callable types:
```
struct Adder {
    var base: Int
    func callAsFunction(_ x: Int) -> Int {
        return base + x
    }
}

let add3 = Adder(base: 3)
add3(10) // => 13
```

Periphery will falsely report `Adder.callAsFunction(_:)` as unused

**Comment by ileitch** [comment]
Hey @pm-dev, I'm unable to reproduce this. Could you please provide a project that reproduces the false positive?

**Comment by pm-dev** [comment]
@ileitch I misinterpreted the error I was seeing. Apologies for the false report! Closing.
