### ISSUE TITLE
Xcode 10.2.1 index request failure

### ISSUE THREAD

**Issue by mdiasdev** [peripheryapp/periphery#44]
Xcode 10.2.1
macOS 10.14.4
periphery 1.5.1

`error: SourceKit index request failed for file [redacted]: [redacted] is not part of the input files`

The error consistently presents on the same file. Please let me know if there's more information I can provide

**Comment by ileitch** [comment]
Is there anything special about the file? Is it a member of multiple targets? I can't really help without the full output from `--verbose`.

**Comment by mdiasdev** [comment]
@ileitch it looks like that was the issue. Is it documented that you need to build all targets a file is included in? Did I miss it?

**Comment by ileitch** [comment]
I don't believe so, but the warning is intended to discourage adding files to multiple targets.

**Comment by mdiasdev** [comment]
Fair enough. Unfortunately, for this project, we need many files in 2 targets...

Either way, this issue can be considered resolved. Thanks for the help!
