### ISSUE TITLE
Xcode Build target fails on "error shell command - exit code '65' "

### ISSUE THREAD

**Issue by faisalazeez** [peripheryapp/periphery#45]
@ileitch  The periphery scan is working via the terminal. However after creating a xcode integration by adding a new target it does work.
I have used the same script that has been populated while running on the terminal.
The run script is as follows:
_`periphery scan --workspace example.xcworkspace --schemes example --targets example --format xcode --no-retain-public --verbose`_

The error am getting is as follows:
```
error: Shell command 'xcodebuild -workspace example.xcworkspace -scheme example -parallelizeTargets -derivedDataPath /Users/domainName/Library/Caches/com.peripheryapp.periphery/DerivedData-0176171cd3316b9abbf823f16dc75ce945d4a250 build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" SWIFT_COMPILATION_MODE="wholemodule" DEBUG_INFORMATION_FORMAT="dwarf"' returned exit status '65':
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/domainName/Library/Caches/com.peripheryapp.periphery/DerivedData-0176171cd3316b9abbf823f16dc75ce945d4a250

Build settings from command line:
    CODE_SIGNING_ALLOWED = "NO"
    DEBUG_INFORMATION_FORMAT = "dwarf"
    ENABLE_BITCODE = "NO"
    SWIFT_COMPILATION_MODE = "wholemodule"
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
```

**Comment by kohtenko** [comment]
@faisalazeez how did you solve the issue? I have pretty much the same happening.

**Comment by kohtenko** [comment]
Ah, running the aggregate target against a real device rather than a simulator is apparently a solution for me. Hope this helps somebody to save some time 👍

**Comment by eugenio79** [comment]
> Ah, running the aggregate target against a real device rather than a simulator is apparently a solution for me. Hope this helps somebody to save some time 👍

Thank you @kohtenko you saved my day. I actually run against `Generic iOS Device` and it worked :)

**Comment by OudomSec** [comment]
I'm facing the same issue, I have tried everything but still showing the same error. Can anyone help me please.

**Comment by ccalderon9** [comment]
I was getting the same error for the terminal (not the target), and my fix was that I needed to call `pod deintegrate` followed by `pod install` since our workspace contains cocoapods
