### ISSUE TITLE
Scan problem

### ISSUE THREAD

**Issue by Zeyyyyyyyy** [peripheryapp/periphery#458]
error: Shell command '/bin/sh -c xcodebuild -workspace '*****' -scheme '****' -parallelizeTargets -derivedDataPath '/Users/***/Library/Caches/com.github.peripheryapp/DerivedData-b4fa63b9-b4fa63b9' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf"' returned exit status '65':

**Comment by Zeyyyyyyyy** [comment]
There is no other error message. Both the terminal and Xocde report this error, and Xcode will report 
“Showing Recent Errors Only
accessing build database "/Users/***e/Library/Caches/com.github.peripheryapp/DerivedData-b4fa63b9-b4fa63b9/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location" error

**Comment by ileitch** [comment]
How are you running Periphery? From an Xcode aggregate target?

**Comment by Zeyyyyyyyy** [comment]
This problem is solved, our project is not suitable for Xocde integration, now want to ask if there is a way I can get specific entries of useless code, such as json format documents, etc.

**Comment by ileitch** [comment]
Periphery currently only identifies unused Swift code, not other format types such as json, images, xib, etc.
