### ISSUE TITLE
Command not working: periphery scan --setup 

### ISSUE THREAD

**Issue by MamtaKukreja** [peripheryapp/periphery#459]
`periphery scan --setup` does not work once the pod is successfully installed.

**Comment by ileitch** [comment]
Can you please provide more details. Are you getting an error message?

**Comment by MamtaKukreja** [comment]
On `pod install`, it shows `Installing Periphery (2.8.6)` and `Pod installation complete!`.
After that, on `periphery scan --setup` it says `zsh: command not found: periphery`

**Comment by baderbenzribia** [comment]
`./Pods/Periphery/periphery scan --setup` may solve your issue.
