### ISSUE TITLE
support to print scan results both on console and to a file

### ISSUE THREAD

**Issue by ayyappa-s** [peripheryapp/periphery#460]
I was trying to use the command line options run scan on our CI and turns out that this is not present. I tried out [tee](https://man7.org/linux/man-pages/man1/tee.1.html) but console stays empty for a really long time as tee prints it only after the commands run is over. 

`periphery scan --workspace Sample.xcworkspace --schemes Sample --targets Sample --format xcode | tee test.log`

any suggestion to solve my problem where I want to see the console logs and at the same time the results to be written on to a file.

**Comment by subdan** [comment]
I recommend to use config file `.periphery.yml` and `periphery scan > periphery.log` instead of `tee`.
