### ISSUE TITLE
False positive reports when Property is accessed in `map`

### ISSUE THREAD

**Issue by alexdong** [peripheryapp/periphery#463]
I have a class called `Moment` and it has a property `isHidden`. `isHidden` is used in a `map` block but `periphery` still warns that it's "assigned, but never used". 

Here is the code: 

```swift
public class Moment: NSManagedObject, Identifiable {
    @NSManaged public var isHidden: Bool
}

/// Customer selects a few into `ids`
ids.map { Moment.get(id: $0) }.map { $0.isHidden = true }
```

When running Periphery 2.0.6, it prints:
`warning: Property 'isHidden' is assigned, but never used`

**Comment by subdan** [comment]
Did you try to change `public` to `private`? It seems that you do not read `isHidden` property in your code.

**Comment by alexdong** [comment]
er, when you say "Do not read", do you mean a `read` (or `get`) instead of a `write` (or `set`) action? Will that matter?

The error message is saying "never used", is it referring to this?  (I used it in constructing a `NSPredictate` but not as a member variable for a read operation.)

**Comment by subdan** [comment]
> do you mean a read (or get)

Yes.

> The error message is saying "never used", is it referring to this?

Yes, you do not read a value of this property. Like `print(moment.isHidden)`

**Comment by alexdong** [comment]
Cool. Thanks.
