### ISSUE TITLE
Report issues in file in reverse order

### ISSUE THREAD

**Issue by pm-dev** [peripheryapp/periphery#466]
A potential enhancement would be specifying a command line option to print issues within a specific file in reverse order.

It's often better to clean up each file starting at the end, so that line numbers always match with what was reported. If you were to start with the first issue which results in removing a line, the line number of following issues will now be off by 1.

**Comment by Amnell** [comment]
Add `| tac` to the end of your command. Like: `periphery scan | tac`

This will reverse the output of the scan. Of course the files would be reported in reverse order as well, but maybe that's not an issue?

**Comment by pm-dev** [comment]
> Add `| tac` to the end of your command. Like: `periphery scan | tac`
> 
> This will reverse the output of the scan. Of course the files would be reported in reverse order as well, but maybe that's not an issue?

Works for my purposes. Thanks @Amnell
