### ISSUE TITLE
False positive with UIApplicationDelegateAdaptor in SwiftUI Lifecycle when split across two lines

### ISSUE THREAD

**Issue by msmollin-community** [peripheryapp/periphery#467]
Per the docs: https://developer.apple.com/documentation/swiftui/uiapplicationdelegateadaptor
```
@main
struct MyApp: App {
    @UIApplicationDelegateAdaptor private var appDelegate: MyAppDelegate

    var body: some Scene { ... }
}
```

> SwiftUI instantiates the delegate and calls the delegate’s methods in response to life cycle events. Define the delegate adaptor only in your App declaration, and only once for a given app. If you declare it more than once, SwiftUI generates a runtime error.

Periphery will mark this as an unused property which, technically is true but the system uses it to load the MyAppDelegate type. I'm gonna mark it as ignored for now in our code but was thinking this is intended by the framework so it might makes sense to just ignore it at the tool level? 

Happy to add it if there's a documented way to do that?

**Comment by msmollin-community** [comment]
Dove into the code a little bit, and it turns out this is actually because our code is structured like:
```
    @UIApplicationDelegateAdaptor 
    private var appDelegate: MyAppDelegate
```
So, more a false positive because line formatting?

**Comment by ileitch** [comment]
I'm unable to reproduce this in 2.10.0. It was most likely caused by a bug in SwiftSyntax that has now been resolved.
