### ISSUE TITLE
IBSegueActions reported as unused

### ISSUE THREAD

**Issue by shuguenot** [peripheryapp/periphery#468]
Should @IBSegueAction be added to the [InterfaceBuilderPropertyRetainer]( https://github.com/peripheryapp/periphery/blob/678ddece2b446c4a243a76cc98c9001cc65e7c65/Sources/PeripheryKit/Analyzer/Visitors/InterfaceBuilderPropertyRetainer.swift#L5) attributes list ~~and [UnusedParameterAnalyzer](https://github.com/peripheryapp/periphery/blob/8a0dd28a67d7b34ab74613496eb8212696b79a7f/Sources/PeripheryKit/Syntax/UnusedParameterAnalyzer.swift#L34)~~ ?

**Comment by pm-dev** [comment]
I've also noticed `@IBAction private func foo()` will be reported as unused when it's referenced from a xib.

**Comment by ileitch** [comment]
@shuguenot Yes that sounds correct, would you mind opening a PR?

**Comment by shuguenot** [comment]
> @shuguenot Yes that sounds correct, would you mind opening a PR?

Is it ok ? thanks
