### ISSUE TITLE
Private IBAction is reported as unused when it's referenced from a Xib

### ISSUE THREAD

**Issue by shuguenot** [peripheryapp/periphery#470]
`@IBAction private func foo()` will be reported as unused when it's referenced from a xib.

_Originally posted by @pm-dev in https://github.com/peripheryapp/periphery/issues/468#issuecomment-1060016213_

**Comment by dwirandytlvk** [comment]
any update related to this?

**Comment by ozgur** [comment]
any update on this @ileitch? It really is not feasible to keep remembering to mark IBAction methods with "periphery:ignore".

**Comment by ileitch** [comment]
@dwirandytlvk @ozgur Periphery does not consider accessibility when retaining references from Xibs. Could you please provide an example project that demonstrates the problem?

**Comment by ileitch** [comment]
Closing due to no response.
