### ISSUE TITLE
Show results for only one file

### ISSUE THREAD

**Issue by alexvbush** [peripheryapp/periphery#472]
Is there a way to analyze the entire codebase but only show the results for only one file? I have a large legacy codebase and it has a ton of unused protocols, properties, and params but I'd like to start my cleanup process one file at a time.

**Comment by alexvbush** [comment]
great tool btw! thank you for making this!

**Comment by ileitch** [comment]
Hey @alexvbush, I think the best approach here is to just filter out the results yourself. You can use json or csv output if you'd like to automate this.
