### ISSUE TITLE
Using StaticInternalSwiftSyntaxParser?

### ISSUE THREAD

**Issue by liamnichols** [peripheryapp/periphery#473]
👋 

I've recently worked on krzysztofzablocki/Sourcery#1037, which took inspiration from realm/SwiftLint#3867 which essentially updates the tools to use [StaticInternalSwiftSyntaxParser](https://github.com/keith/StaticInternalSwiftSyntaxParser) to make the binaries more portable by removing the dependency on a dylib. 

Before taking on any work (since it can get a bit tricky), I wanted to check to see if you'd be keen in taking this direction with Periphery? 

Benefits:

- Portable binary
- No blockers from building with newer toolchains without having to update SwiftSyntax dependency 

Starting with SwiftSyntax for 5.6, the lib_internalSwiftSyntaxParser.dlyb dependency is now a binary dependency in the Package.swift file, which is better than relying on the internal version bundled in Xcode (and linked to that version of Xcode via the rpath), which is a great step in the right direction, but it still has the portability issues described above.

**Comment by ileitch** [comment]
Hey @liamnichols, yes this sounds like a great idea. Thanks for working on this!

**Comment by liamnichols** [comment]
No problem, although I think i've become a bit blocked by [SR-15065](https://bugs.swift.org/browse/SR-15065) or a similar issue.

Running `swift package describe` (which `RetentionTest` requires) errors after introducing a binary target. I'll try to better reproduce the issues and report/update the bug ticket.

**Comment by liamnichols** [comment]
@ileitch: I was a bit on the fence with the approach that I wanted to take here, so now there are two 😄 

- https://github.com/peripheryapp/periphery/pull/476
- https://github.com/peripheryapp/periphery/pull/480

I updated the descriptions with the info, please feel free to digest it whenever you get a chance and let me know what you think 😄 Maybe there is even a better third option hiding somewhere as well

**Comment by liamnichols** [comment]
Closing this now since #480 merged to `master`, thanks!
