### ISSUE TITLE
How to analysis code in Pods project

### ISSUE THREAD

**Issue by ArthurChi** [peripheryapp/periphery#475]
I want to analysis code in Pods project and main Project, I want to know how to do

**Comment by YuryBogdanov** [comment]
https://github.com/peripheryapp/periphery/issues/297

**Comment by ileitch** [comment]
Hey @ArthurChi, please try out the instructions listed in #297 as @YuryBogdanov kindly pointed out. If you run into any problems, please respond here and I will reopen this issue.
