### ISSUE TITLE
SonarQube integrations

### ISSUE THREAD

**Issue by sayler8182** [peripheryapp/periphery#481]
Is there a possibility to integrate this tool with SonarQube ?

**Comment by ileitch** [comment]
Hey @sayler8182, unfortunately I don't have any experience with SonarQube. It [looks like](https://docs.sonarqube.org/latest/analysis/external-issues/) it does have some kind of 3rd party integration ability, but only SwiftLint is listed. It looks like either SonarQube needs to add support for Periphery, or you could try transform Periphery's output into a format similar to SwiftLint.

I'm closing this issue as I don't have any further input, but if Periphery's output is easily transformed into SwiftLint compatible format, please let me know. Maybe we can add a new output format option.

**Comment by thedavidharris** [comment]
Was thinking about this as well as we were looking for a way to "track" this across our large project. Right now there is just the stdout output, but if feels like there could be the ability to output in other formats, the SonarQube generic output format being one of them.
