### ISSUE TITLE
Scan problem

### ISSUE THREAD

**Issue by Sawka01** [peripheryapp/periphery#484]
error: Shell command '/bin/sh -c xcodebuild -workspace '/Users/8744934gmail.com/Downloads/Surf/ios/BurgerKing.xcworkspace' -scheme 'BurgerKing' -parallelizeTargets -derivedDataPath '/Users/8744934gmail.com/Library/Caches/com.github.peripheryapp/DerivedData-9f190bb5-9f190bb5' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf"' returned exit status '65':
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:A7904003-71F6-54B8-A251-AD4494879925 }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:AAAC1120-3949-4E13-ABF2-F89B1B5EFC3B, OS:12.4, name:iPhone 5s }
{ platform:iOS Simulator, id:026CF9FF-205E-4345-AFF4-51D1F9A93192, OS:12.4, name:iPhone 6 }
{ platform:iOS Simulator, id:CB7460A3-91CB-4B91-9997-7DAF8BC61609, OS:12.4, name:iPhone 6 Plus }
{ platform:iOS Simulator, id:86F03AC7-224A-446C-A29F-F5B9444FEAD8, OS:12.4, name:iPhone 6s }
{ platform:iOS Simulator, id:92B19EE8-DF89-4253-949C-8F0EA4C35C6A, OS:12.4, name:iPhone 6s Plus }
{ platform:iOS Simulator, id:38DFBDEA-870B-4760-A104-9DED382ADECB, OS:12.4, name:iPhone 7 }
{ platform:iOS Simulator, id:814293C7-66B9-4433-8AB0-29038709A9B4, OS:12.4, name:iPhone 7 Plus }
{ platform:iOS Simulator, id:039214F8-E559-4AAF-86A5-F6A02F0181A7, OS:12.4, name:iPhone 8 }
{ platform:iOS Simulator, id:8D4CDCC5-9B56-49A4-A28D-5AC73EC5C747, OS:13.0, name:iPhone 8 }
{ platform:iOS Simulator, id:AC29B52A-03BE-4332-9BA7-4454C86D28CB, OS:15.0, name:iPhone 8 }
{ platform:iOS Simulator, id:A719C205-493B-47DA-AF64-7A89A1CC4609, OS:12.4, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:E10DB28F-D278-44D8-BD53-57F5A6BB679A, OS:13.0, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:2CF308D4-AB22-48BB-9F65-BAE51C0B3B90, OS:15.0, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:22C7FBFC-344E-4935-806B-FC44E7C3B955, OS:13.0, name:iPhone 11 }
{ platform:iOS Simulator, id:BEF107FA-2F92-442B-A282-7B8441022EBC, OS:15.0, name:iPhone 11 }
{ platform:iOS Simulator, id:B9A3AAB3-DDD1-462D-A6B9-2B6CDF492D4C, OS:13.0, name:iPhone 11 (iOS 13.0) }
{ platform:iOS Simulator, id:EB17DF71-F5A2-4C02-B909-57EF7AAE0323, OS:13.0, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:B35DC75A-AAAD-4327-A7DF-B6D67B362B97, OS:15.0, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:751F9F0B-E0A1-43E3-84C3-B873E14D37F9, OS:13.0, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:C2C5D063-0846-47A8-AD5C-7AB3BC1C8A28, OS:15.0, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:21EB3B9B-4BE6-44D2-B4E9-B78A64C691DC, OS:15.0, name:iPhone 12 }
{ platform:iOS Simulator, id:B534E9BF-11B5-4E2C-B6F6-B2B04AA541FB, OS:15.0, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:22B5800E-9930-4756-B88A-B8105A523F60, OS:15.0, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:90CD33C1-2ACA-45FB-9812-DF8AD0E5C932, OS:15.0, name:iPhone 12 mini }
{ platform:iOS Simulator, id:EC36EEA4-AC39-43C9-B74F-8E548882C3E5, OS:15.0, name:iPhone 13 }
{ platform:iOS Simulator, id:9E533172-C77B-48BF-8DDF-B160E8900682, OS:15.0, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:0541EC33-B96A-4DC5-8480-390D13D325F6, OS:15.0, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:4F938093-701E-4D6B-A3FB-CE79169C8B38, OS:15.0, name:iPhone 13 mini }
{ platform:iOS Simulator, id:7BD9A3F8-D9AA-4E12-B9A6-6E22029924E6, OS:12.4, name:iPhone SE (1st generation) }
{ platform:iOS Simulator, id:426C1752-2210-48E4-A93D-24AC2EE227E4, OS:13.0, name:iPhone SE (1st generation) }
{ platform:iOS Simulator, id:6FC3D7DE-E29B-4596-8E90-35FFB095E313, OS:15.0, name:iPhone SE (2nd generation) }
{ platform:iOS Simulator, id:BA3B7F32-C6E4-4323-9C56-FACB789DB871, OS:12.4, name:iPhone X }
{ platform:iOS Simulator, id:CCE2095D-16DF-47AB-AF6D-0C09472757A2, OS:12.4, name:iPhone Xs }
{ platform:iOS Simulator, id:60EBAF42-9E93-46DB-BA09-95FF8A524A32, OS:12.4, name:iPhone Xs Max }
{ platform:iOS Simulator, id:155BDB54-5AEC-4EC3-A35E-43F240FD8C8B, OS:12.4, name:iPhone Xʀ }
{ platform:iOS Simulator, id:2F8CB6A8-DB53-49DC-A299-EC7C24BC6C00, OS:15.0, name:iPod touch (7th generation) }
{ platform:iOS Simulator, id:61323C6C-6CB9-4014-9009-42D85A6EFB8A, OS:12.4, name:iPad (5th generation) }
{ platform:iOS Simulator, id:4BD78991-19B7-4FA4-A1DA-C5A58C5B5AFE, OS:12.4, name:iPad (6th generation) }
{ platform:iOS Simulator, id:BF92B30F-A712-48EA-BC12-24D686956B5C, OS:15.0, name:iPad (9th generation) }
{ platform:iOS Simulator, id:3C03A5BF-91FB-4B30-819A-E7F377FEC886, OS:12.4, name:iPad Air }
{ platform:iOS Simulator, id:EAFD6FE2-9375-4B0F-B74E-CE94B5638970, OS:12.4, name:iPad Air (3rd generation) }
{ platform:iOS Simulator, id:40BB5E43-1D9D-445B-895F-C181F2D0222D, OS:13.0, name:iPad Air (3rd generation) }
{ platform:iOS Simulator, id:E746A8E8-9425-4B7D-91EF-4E5F08412F4B, OS:15.0, name:iPad Air (4th generation) }
{ platform:iOS Simulator, id:6DB77453-0B4E-4FF0-8949-0555923C9B18, OS:12.4, name:iPad Air 2 }
{ platform:iOS Simulator, id:EB015951-7F41-42DE-8A7A-4D1CDF90A642, OS:12.4, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:36ED9938-BA36-4326-A1EE-239FC104EDA0, OS:13.0, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:C04DED0B-A4CA-42D2-A1D4-5A5E32124FC4, OS:15.0, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:02FE354D-B3FE-42C6-9AF0-1FF49A72F3EC, OS:12.4, name:iPad Pro (10.5-inch) }
{ platform:iOS Simulator, id:E0CB2746-346C-40FA-8C71-985E4E7FB756, OS:12.4, name:iPad Pro (11-inch) (1st generation) }
{ platform:iOS Simulator, id:0A98AA77-FFED-4BAB-A7AA-327ADF2E4243, OS:13.0, name:iPad Pro (11-inch) (1st generation) }
{ platform:iOS Simulator, id:E4E7171F-B354-4E2E-81AA-09931E0C809E, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:1A4DAFAC-FD6F-41C8-B28B-90AFC069BDE7, OS:12.4, name:iPad Pro (12.9-inch) (1st generation) }
{ platform:iOS Simulator, id:53F13C0B-A786-41BF-8934-3F0219559CED, OS:12.4, name:iPad Pro (12.9-inch) (2nd generation) }
{ platform:iOS Simulator, id:FBA68BD7-BA78-4987-AFD0-AC42B8C6298A, OS:12.4, name:iPad Pro (12.9-inch) (3rd generation) }
{ platform:iOS Simulator, id:76C48C31-8335-4426-ADC3-A9EE453FD98A, OS:13.0, name:iPad Pro (12.9-inch) (3rd generation) }
{ platform:iOS Simulator, id:707F2A2D-C823-4B5E-9AAE-A56904FEEB49, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:5DEA02C1-80A7-496D-BD3F-99FC6C10C13C, OS:15.0, name:iPad mini (6th generation) }
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in parallel
error: unable to attach DB: error: accessing build database "/Users/8744934gmail.com/Library/Caches/com.github.peripheryapp/DerivedData-9f190bb5-9f190bb5/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
** BUILD FAILED **

and when I run Periphery from an Xcode aggregate target, periphery doesn't show unused codes

**Comment by Servus7** [comment]
Had the same problem and this solved it #280

**Comment by ileitch** [comment]
@Sawka01 can you please confirm if #280 resolves your problem?

**Comment by Sawka01** [comment]
No, I resolved this problem with adding index_store_path -> ${PODS_ROOT}/Periphery/periphery scan --index-store-path ${BUILD_ROOT}/../../Index/DataStore
