### ISSUE TITLE
Ignore entire files configured in .periphery.yml

### ISSUE THREAD

**Issue by denizdogan** [peripheryapp/periphery#489]
It would be nice if we could ignore entire files from .periphery.yml, since some tools like [Shark](https://github.com/kaandedeoglu/Shark/) automatically generate source code.

**Comment by ileitch** [comment]
@denizdogan this is already supported, please see [Excluding Files](https://github.com/peripheryapp/periphery#excluding-files) in the README. You can use the `--verbose` flag to see the yaml config.
