### ISSUE TITLE
unable to build a release from the latest master on Xcode 13.3.1

### ISSUE THREAD

**Issue by ayyappa-s** [peripheryapp/periphery#490]
hi I was trying to clone and run `make build_release` it get broken due to duplicate symbols for on Xcode 13.3.1 ?

```
duplicate symbol '_swiftparse_syntax_structure_versioning_identifier' in:
    periphery/.build/apple/Products/Release/SwiftSyntaxParser.o
    /periphery/.build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser

ld: 14 duplicate symbols for architecture arm64
```

**Comment by AF-cgi** [comment]
@ayyappa-s You can try the master branch. It should work. Therefor needs a new release.

**Comment by liamnichols** [comment]
@ileitch, would it be possible to tag a release for this sometime soon? 🙏

**Comment by ayyappa-s** [comment]
just tried with `makebuild_release` latest master (`bf905a03773e33e5717f6a1973e1e50fb6b84238`) same results :( 

duplicate symbol '_swiftparse_diagnostic_get_fixit' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_fixit_count' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_message' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_range' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_range_count' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_severity' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_diagnostic_get_source_loc' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parse_string' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parser_create' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parser_dispose' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parser_set_diagnostic_handler' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parser_set_node_handler' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_parser_set_node_lookup' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser
duplicate symbol '_swiftparse_syntax_structure_versioning_identifier' in:
    .build/apple/Products/Release/SwiftSyntaxParser.o
    .build/apple/Products/Release/lib_InternalSwiftSyntaxParser.framework/lib_InternalSwiftSyntaxParser

ld: 14 duplicate symbols for architecture arm64

**Comment by ayyappa-s** [comment]
looks like i found something. Looks like there is an open issue which could affecting our build https://github.com/apple/swift/issues/58079

took the text below from here - https://github.com/keith/StaticInternalSwiftSyntaxParser
> Note: because of [this bug](https://bugs.swift.org/browse/SR-15802) if you want to depend on this target in SwiftPM and target multiple architectures in a single build, you must only depend on it from top level targets such as a test or executable target.

@ileitch for your kind attention.

**Comment by liamnichols** [comment]
Ah, I never checked the Makefile when working on #473, we can use a workaround similar to this:

https://github.com/krzysztofzablocki/Sourcery/blob/9616fade78c7a79f257c7b9b401a71820b501101/Rakefile#L66-L74

I'll try and work on a patch tomorrow 🤞

**Comment by ayyappa-s** [comment]
thanks @liamnichols :). that would be very helpful

**Comment by liamnichols** [comment]
@ayyappa-s: It's also worth mentioning that `make build_release` is only necessary if you want to build a universal binary (i.e to package for distribution). 

If you want to just build for use locally on your machine, running `swift build -c release` should do the trick (the output can be found at `swift build -c release --show-bin-path`

**Comment by ayyappa-s** [comment]
sure i will use that but i still need it for package distribution, will wait for you :). until then I will use the local way for now. thanks

**Comment by liamnichols** [comment]
Ahh ok, understood 🙂 fix is in https://github.com/peripheryapp/periphery/pull/493 👍

**Comment by ayyappa-s** [comment]
one thing i noticed with the latest periphery build on my local machine is the time taken for the periphery scan is kind of doubled. will check this again and let you know.

**Comment by liamnichols** [comment]
@ayyappa-s: To confirm, how did you compare? Are you able to share a small sample project that we can use to compare together? 

Am I right in assuming that you are seeing this difference between the last official release and building `master`? Do you still see the issue if you use Xcode 13.2.1 to build `periphery` instead of Xcode 13.3?

**Comment by ayyappa-s** [comment]
sure @liamnichols i will see how project can be shared, btw is there a way where we can ask periphery to run in a mode to show why things getting slowed down ? if there is something to diagnose can you please share ?

**Comment by ayyappa-s** [comment]
thanks @ileitch i am closing down this issue for now and open a new one for the time. thanks for the numbers 🙏🏾

**Comment by ileitch** [comment]
Thank you all for handling this. I will get a new release out later today!
