### ISSUE TITLE
periphery shows wrong instance when it's using inside init

### ISSUE THREAD

**Issue by jphong1111** [peripheryapp/periphery#491]
I found a lot of wrong cases which is using inside init(), convenience init()

here is the example

```swift
private let A: Example1
private let B: Example2
private let C: Example3

init(a: Example1, b: Example2, c: Example3) {
   self.a = A
   self.b = B
   self.c = C
}
public convenience init(a: Example1, b: Example2, d: Example4) {
  // C is confirmed by Example3
  // make() is just a function which is declared in class C
   let c = C.make(inputA: a, inputB: b, inputD: d)
   self.init(a: a, b: b, c: c)
}
```

in this case, **c, d** is fine but periphery shows me **a, b** instances are not using inside my codebase

**Comment by ileitch** [comment]
@jphong1111 Can you please provide a small project that reproduces the error? Is Periphery saying the properties are unsued, or assign-only? Does it also report any of the initializers as unused?

**Comment by ileitch** [comment]
Closing this as there's not enough information for me to diagnose the issue. I'll reopen if the requested demo project is provided.
