### ISSUE TITLE
False positive: class extension declaration: when a typeAlias is used in order to specify the extended class

### ISSUE THREAD

**Issue by arixegal** [peripheryapp/periphery#492]
In the following code, a false positive "unused" is reported for the expression "WebViewLinks", even though it is used in the next line

> private typealias WebViewLinks = WhatsNewViewController
> extension WebViewLinks {
> ...
> }

**Comment by ileitch** [comment]
Thanks for reporting, I will investigate soon.

**Comment by ileitch** [comment]
@arixegal Could you please provide a more complete reproduction? Just because `WebViewLinks` is extended doesn't mean it's used necessarily.

**Comment by ileitch** [comment]
Closing due to no response.

**Comment by Tyler-Keith-Thompson** [comment]
I'm seeing the same behavior. The tool is reporting that the type alias is unused (it's private) but it is used...in the extension. It might be fair for the tool to claim the code within the extension isn't being used, but the typealias is being used...to extend the type.

**Comment by ileitch** [comment]
Hey Tyler, could you please provide a more complete example so that I can reproduce this?

**Comment by Tyler-Keith-Thompson** [comment]
Yeah, I'll try to get you a minimally reproducible example in a few hours.

**Comment by ileitch** [comment]
Thank you, I appreciate it!

**Comment by Tyler-Keith-Thompson** [comment]
[PeripheryRepro.zip](https://github.com/peripheryapp/periphery/files/10946175/PeripheryRepro.zip)

Let's see if it'll be cool about that zip file (cause the project is very small)

Output:
```
* Inspecting project...
* Building PeripheryRepro...
* Indexing...
* Analyzing...

/Users/tylerthompson/workspace/PeripheryRepro/PeripheryRepro/ContentView.swift:23:19: warning: Typealias 'MyTypeAlias' is unused

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
```

Code:
```
struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Text("Hello, world!")
        }
        .onAppear(perform: test)
        .padding()
    }
}

private typealias MyTypeAlias = ContentView
extension MyTypeAlias { // typealias decidedly used...right here!
    func test() {
        print("test")
    }
}
```

**Comment by ileitch** [comment]
Many thanks for the repro @Tyler-Keith-Thompson, this is now fixed in `master`.

One could argue that Periphery is technically correct here. Even though the alias is extended, it's not actually used anywhere else, so you could just delete it and extend `ContentView` directly. It's a confusing result either way, so I think it's right that we don't produce it.
