### ISSUE TITLE
Periphery doesn't seem to work with a workspace file.

### ISSUE THREAD

**Issue by david-palmer79** [peripheryapp/periphery#496]
periphery version 2.9.0
MacOS 12.3.1
Xcode 13.0

### Discussed in https://github.com/peripheryapp/periphery/discussions/495

<div type='discussions-op-text'>

<sup>Originally posted by **david-palmer79** May 10, 2022</sup>
I'm trying to use periphery with a workspace. I get the error "Target 'MyApp' does not exist in 'MyApp.workspace'". It is my understanding a workspace doesn't have a target. This is the command I'm trying to run:
```
periphery scan --workspace MyApp.xcworkspace --schemes MyApp --clean-build --retain-public -- "-destination 'platform=iOS Simulator,OS=latest,name=iPhone 11'"
```
I have verified my app builds with the following command:
```
xcodebuild clean build -workspace MyApp.xcworkspace -scheme MyApp -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11'
```
Am I doing something wrong?</div>

**Comment by ileitch** [comment]
You're missing the `--targets` argument. I suggest you try first with `periphery scan --setup`, it'll output the correct command for you.

**Comment by david-palmer79** [comment]
Thank you, for the quick reply. I added the ```--targets``` argument to my original periphery command and I get the same error:
```
error: Target 'MyApp' does not exist in 'package.workspace'.
```
I also ran ```periphery scan --setup``` which fails with:
```
error: Shell command '/usr/bin/env swift build MyApp' returned exit status '1':
error: the library 'foo' requires macos 10.10, but depends on product 'bar' which requires macos 10.15; consider changing the library 'foo' to require macos 10.15 or later, or the product 'bar' to require macos 10.10 or earlier.
```
MyApp is an iOS-only package so it won't build from the command line using ```swift build```, since SPM attempts to build both macOS and iOS platforms, but like i explained in my original post, the following xcodebuild command does correctly build the project:
```
xcodebuild clean build -workspace .swiftpm/xcode/package.xcworkspace -scheme MyApp -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11'
```
SPM kindly provides the .workspace file enabling me to build my workspace from the command line. My expectation is ```periphery``` should be able to scan an app relying on the workspace file in the same manner as ```xcodebuild``` works, using the ```--scheme``` instead of ```--target```.

**Comment by ileitch** [comment]
Unfortunately Periphery doesn't support iOS-only packages yet. Please follow along in #281 for any future updates.
