### ISSUE TITLE
Error Inspecting Project Configuration

### ISSUE THREAD

**Issue by alanzeino** [peripheryapp/periphery#5]
```
error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "defaultConfigurationIsVisible", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
```

I'll try building from source to see what's going on.

**Comment by ileitch** [comment]
That error is most likely coming from https://github.com/tuist/xcodeproj. Version 1.3.0 includes a more recent version of `xcodeproj`, you could try [1.2.3](https://github.com/peripheryapp/releases/releases/tag/1.2.3) and see if the issues remains?

**Comment by rocir** [comment]
I'm having the same issue. I tried with 1.2.3 and the outcome is exactly the same.

**Comment by ileitch** [comment]
@rocir Your issue is the same as https://github.com/peripheryapp/periphery/issues/25

**Comment by ileitch** [comment]
@rocir Please try 1.4.0
@alanzeino Any luck investigating this? You could also try 1.4.0

**Comment by alanzeino** [comment]
Looks like it continues with `1.4.0`

```
$ periphery scan
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Inspecting project configuration...

error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "defaultConfigurationIsVisible", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))

$ periphery version
1.4.0
```

**Comment by ileitch** [comment]
@alanzeino Could you please grep for `defaultConfigurationIsVisible` in your `pbxproj` and paste the output.

**Comment by alanzeino** [comment]
It's set to `0` everywhere:

```
defaultConfigurationIsVisible = 0;
```

I created a new project in Xcode and that's the default there too.

**Comment by ileitch** [comment]
Please try 1.6.0, which contains a much newer version of `xcodeproj`. Please open a new issue if you run into problems.
