### ISSUE TITLE
Scan creates new dir in Caches

### ISSUE THREAD

**Issue by Jasperav** [peripheryapp/periphery#500]
I have ran periphery a few times (just with the regular scan command). It seems it creates a new dir in the Caches dir everytime it does so. I was curious why it behaves like that, because this pollutes my disk space pretty fast (takes a few gb every run). I don't think I can use the skip_build here because I change source files all the time.

**Comment by ileitch** [comment]
The cache directory is based on the project and scheme used. It shouldn't create a new directory unless you change the project or scheme. Is this not what you're seeing?

**Comment by Jasperav** [comment]
@ileitch I just test it, it creates a new dir each and every time I run the --scan command. I already fixed it locally by just removing the cache dir before invoking the command.
