### ISSUE TITLE
Let me check if this tool is sending information to other servers

### ISSUE THREAD

**Issue by ryoooooory** [peripheryapp/periphery#505]
Thank for developing Periphery!
I want to use periphery for one of my clients. Usually when we use other tools they need to be audited, etc. I know periphery only uses compiler information and it does not send any information to any server outside but is there any place this is explicitly written?
Or Would it be possible to get a confirmation in this thread?
Having this information would make things easier here.
Thank you.

**Comment by ileitch** [comment]
That's correct, Periphery performs analysis locally on your machine. The only network requests made is to check for an update, or by swift/xcodebuild. Googling will give you a few ways to check the network requests made by processes.
