### ISSUE TITLE
Notification token unused warning should be ignored by default

### ISSUE THREAD

**Issue by ZeroOnet** [peripheryapp/periphery#509]
I registered a notification handler with a token, I don't need to access it again because Notification Center will remove it automatically if token was destoried.

Code example:
```

class A {
    var token: NSObjectProtocol?

    func addNoti() {
        token = NotificationCenter.default.addObserver(
            forName: UIApplication.didBecomeActiveNotification,
            object: nil,
            queue: .main
        ) { _ in
            // do something
        }
    }
}

```

In periphery 2.9.0, It gives me a warning 「Property 'token' is assigned, but never used」This warning should be ignored by default.

**Comment by ileitch** [comment]
I'm afraid it's not really possible for Periphery to identify that token has special retention semantics in this context. Your only options are to use `--retain-assign-only-property-types NSObjectProtocol` or use a magic comment just for this case. See [Assign-only Properties](https://github.com/peripheryapp/periphery#assign-only-properties) for some more details.
