### ISSUE TITLE
Xcode 11 support

### ISSUE THREAD

**Issue by iwheelbuy** [peripheryapp/periphery#51]
I got `error: unknownTokenKind("ellipsis")`. I believe it is Xcode 11 issue, because 10.3 works fine. And I'm not alone: https://github.com/peripheryapp/periphery/issues/39#issuecomment-508944676

It would be great to have Xcode 11 support? Thanks

**Comment by prrane** [comment]
ditto

**Comment by ileitch** [comment]
Duplicate of #49
