### ISSUE TITLE
Bazel/Buck Support

### ISSUE THREAD

**Issue by dwirandytlvk** [peripheryapp/periphery#513]
Hallo periphery team,

Thank you for building a great tools, but i want to ask about third party build system, since in our team we did not use xcodebuild in our CI, is it possible to support Bazel or Buck?

**Comment by ileitch** [comment]
No not yet, but it's a feature I want to implement soon. I don't think it'd be too difficult.

**Comment by rounak** [comment]
+1 for this request

**Comment by ileitch** [comment]
This is now supported in 2.12.0 - https://github.com/peripheryapp/periphery#build-systems
