### ISSUE TITLE
Xcode 14 Beta 3 Indexing

### ISSUE THREAD

**Issue by crownvic** [peripheryapp/periphery#514]
With Xcode 14 Beta 3, when I'm scanning a project from a terminal (.xcodeproj with SPMed third-party frameworks) I get the following error message:

* Indexing...
error: (IndexStoreError) internalError("index store path does not exist: /Users/nikonov/Library/Caches/com.github.peripheryapp/DerivedData-3993676c-3993676c/Index/DataStore")

I tried to point the index store path to the Xcode's Derived Data folder; Periphery works but shows some incoherent results. For example, I have a view controller SomeVC.swift with a private func updateUI() that's called from the overridden viewWillLayoutSubviews() method. Periphery says that updateUI() is unused.

I suppose that's happening because of Xcode 14 changes.

**Comment by shuguenot** [comment]
Same with Xcode 14 Beta 5 (14A5294e)

**Comment by gsbernstein** [comment]
Same for beta 6

**Comment by ileitch** [comment]
This won’t be fixed until the 14.0 stable release, as we need to wait for SwiftSyntax.

**Comment by adarhef** [comment]
> This won’t be fixed until the 14.0 stable release, as we need to wait for SwiftSyntax.
> […](#)

Shouldn't this PR be the fix?
https://github.com/peripheryapp/periphery/pull/523

Don't really see a reason to wait here

**Comment by adarhef** [comment]
> 

14.0 was officially released, hoping for a fix soon as this issue completely prevents any usage currently

**Comment by spipau** [comment]
Any updates regarding Xcode 14 support yet? Thanks!

**Comment by gsbernstein** [comment]
There's a fix merged but they need to do a new release. [This thread](https://github.com/peripheryapp/periphery/issues/525#issuecomment-1266889103) has a temporary workaround to reenable the index.

**Comment by ileitch** [comment]
This is now fixed in v2.10.0.
