### ISSUE TITLE
Doesn't find the stored index for targets

### ISSUE THREAD

**Issue by JuancarlosExperis** [peripheryapp/periphery#516]
Hello, I get the following error when trying to run `periphery scan`on my project

<img width="1675" alt="Screen Shot 2022-07-26 at 1 47 31 PM" src="https://user-images.githubusercontent.com/84855723/181000887-835da796-7671-4e75-bdcc-823c0bd82ee3.png">

**Comment by shuguenot** [comment]
duplicate of https://github.com/peripheryapp/periphery/issues/514 ?

**Comment by MrJre** [comment]
@shuguenot Similarly #502

**Comment by ileitch** [comment]
Closing as a duplicate of #514
