### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by OldCrab** [peripheryapp/periphery#52]
`error: The element XCSwiftPackageProductDependency is not supported.`
 `* Inspecting project configuration...`

Xcode 11.0

**Comment by ivanvorobei** [comment]
Also need add. Please

**Comment by ileitch** [comment]
Could you please give the xcode11 branch a try?

**Comment by OldCrab** [comment]
./Periphery scan --project "~/Documents/stasis-wallet-ios/STASIS-Wallet.xcodeproj" --schemes STASIS-Stage --targets STASIS-Wallet
* Inspecting project configuration...
* Building STASIS-Stage...
* Indexing...
Fatal error: Duplicate elements of type 'Reference' were found in a Set.
This usually means either that the type violates Hashable's requirements, or
that members of such a set were mutated after insertion.
[1]    23997 illegal hardware instruction  ./Periphery scan --project  --schemes STASIS-Stage --targets STASIS-Wallet

I found this error, and when i tried to run Periphery project in xcode, there was another error: 
* Inspecting project configuration...
error: Shell command 'xcodebuild -project /Users/andreyvasiliev/Documents/stasis-wallet-ios/STASIS-Wallet.xcodeproj -list -json' returned exit status '74':

**Comment by OldCrab** [comment]
If you know how to fix `exit status 74`, I can help to fix this bug

**Comment by txaiwieser** [comment]
I'm also facing these problems, any solution?

**Comment by ileitch** [comment]
Please see here for the status of Periphery: https://github.com/peripheryapp/periphery/issues/66

**Comment by ileitch** [comment]
This should be fixed now in 1.6.0.
