### ISSUE TITLE
Exclude class/struct that inherit from Codable

### ISSUE THREAD

**Issue by dwirandytlvk** [peripheryapp/periphery#520]
Hi there,

I want to ask, is it possible to exclude class that inherit from Codable? 
Since i have so many warning related to unused property but it actually used for parsing property to http parameters

**Comment by ileitch** [comment]
Hey @dwirandytlvk, checkout the [Encodable](https://github.com/peripheryapp/periphery#encodable) section in the readme. Does the `--external-encodable-protocols` option solve your problem?

**Comment by ileitch** [comment]
Closing due to no response. Please reply if this issue should remain open.
