### ISSUE TITLE
Incorrect warning for unused public protocol.

### ISSUE THREAD

**Issue by CraigSiemens** [peripheryapp/periphery#522]
We're incorrectly getting the following warning when building our project
```
Protocol 'Something' is declared public, but not used outside of [Framework Target]
```
## Versions
Periphery: 2.9.0
Xcode: 13.4.1

## Steps to Reproduce
This is the simplest implementation I could reproduce it with.

#### Framework Target
```swift
public let getSomething = { () -> Something in RealThing() }

public protocol Something {
    func doThing()
}

private struct RealThing: Something {
    func doThing() {
        print("Hello, world!")
    }
}
```

#### App Target
```swift
getSomething().doThing()
```

## Other Details
It seems like it's an issue with the property's type being inferred from the closure. If the implementation is changed to have and explicit type, the warning is not shown.

```swift
public let getSomething: () -> Something = { RealThing() }
```

**Comment by ileitch** [comment]
Thanks for reporting, and sorry for the slow resolution.

**Comment by CraigSiemens** [comment]
I believe this is still an issue when the closure uses protocols.  

[b605b6f](https://github.com/peripheryapp/periphery/commit/b605b6ff79aab446976e0c75293cd89a43fcde2f) is testing with classes which may have a different behaviour.

**Comment by ileitch** [comment]
@CraigSiemens I've double-checked, and protocols are also covered by this change. It's actually totally agnostic of the kind of types involved, it matches up the variable declaration based on the source location.
