### ISSUE TITLE
No warning if a swiftui view is used only in previews

### ISSUE THREAD

**Issue by doroshenkoeng** [peripheryapp/periphery#524]
STR:
1 create a new swiftui view

ER - warning: Struct 'SwiftUIView' is unused
AR - No unused code detected

**Comment by ileitch** [comment]
Yes, this is deliberate, but we can change this behavior. I think rather than simply saying the struct is unused, we should have a more clear message specifically for SwiftUI previews.

**Comment by andbi** [comment]
That would be a lifesaver!

**Comment by nhaarman** [comment]
How do people now deal with hundreds of "Warning: Struct 'XXX_Previews' is unused" instances?

**Comment by dyrkabes** [comment]
@nhaarman for us adding a flag `--retain-swift-ui-previews` disabled the warnings. The command looks so then: `periphery scan --retain-swift-ui-previews`
