### ISSUE TITLE
False Positive: `if-let` shorthand in Swift 5.7

### ISSUE THREAD

**Issue by pm-dev** [peripheryapp/periphery#528]
Swift 5.7 introduced an [`if-let` shorthand](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md) which can cause a false positive:
```

struct Test {
    let property: String?
    init(property: String?) {
        self.property = property
    }
    
    func run() {
        if let property {
             print("\(property ?? "<nil>")")
        }
    }
}
```

In this example, periphery would report
```
warning: Property 'property' is assigned, but never used
```

**Comment by SimplyDanny** [comment]
I've filed [this issue](https://github.com/apple/swift/issues/61509) in the Swift project.

@ileitch: You could comment there mentioning Periphery to increase the pressure. 😉

**Comment by ileitch** [comment]
I've implemented a workaround in 2.10.1, which should cover most cases. Global properties are one notable exception though, as I couldn't find a way to achieve that in a reasonably efficient way. I'm working on a fix for the Swift bug, I hope to have that completed soon.

**Comment by Vadim-Yelagin** [comment]
Unfortunately, the fix does not work for `guard let foo else {…`

**Comment by ileitch** [comment]
@Vadim-Yelagin I've pushed a fix guard-let, but I'm not able to reproduce a failure using result builders. For example, this simple example works as expected. Could you please provide a snippet demonstrating the problematic syntax?

```
struct MessageView: View {
    let message: String? = nil

    var body: some View {
        VStack {
            if let message {}
        }
    }
}
```
