### ISSUE TITLE
Periphery should remove the caches after running

### ISSUE THREAD

**Issue by buscarini** [peripheryapp/periphery#530]
I have it set up in jenkins, and I have just discovered that it was using 180GB of disk space which is why I had almost no free space in the machine. It was all in ~/Caches/com.github.peripheryapp

**Comment by ileitch** [comment]
We could add a new `clear-cache` command to handle that. Would you be willing to submit a PR?

**Comment by buscarini** [comment]
I'm pretty busy right now, but if I manage to get some time for this, sure, I would gladly do it. Could you give any pointers to which files would I need to modify?
