### ISSUE TITLE
Feature request: Shorter line output by default or compact mode

### ISSUE THREAD

**Issue by Simulacrotron** [peripheryapp/periphery#531]
I would love if periphery could output less per line.  Perhaps with a `--compact` flag or by dropping some unnecessary output. 

Every line shows the full path to the file, a `warning` label (I've never seen an `error` or any other indicator).  I think it might be easier to scan and parse through large amounts of output if only the relative path is shown and `warning` is dropped.

When called from `/Users/thecurrentusername/Git/SomeLongAppName/Some Long App Name Subfolder`
e.g. 
`/Users/thecurrentusername/Git/SomeLongAppName/Some Long App Name Subfolder/Some Other Long Subfolder/Shared/Data Controllers/SomeFileDataController.swift:11:13: warning: Enum 'SomeFileDataControllerError' is declared public, but not used outside of Some_Long_Target_Name, Some_Other_Long_Target_Name_Extension`

could become:
`../Some Other Long Subfolder/Shared/Data Controllers/SomeFileDataController.swift:11:13: Enum 'SomeFileDataControllerError' is declared public, but not used outside of Some_Long_Target_Name, Some_Other_Long_Target_Name_Extension`

It seems to me that the absolute path and `warning` labels could be dropped entirely.  But if there default case still needs those, adding a flag such as `--compact` would be great.

**Comment by ileitch** [comment]
The default output is parseable by Xcode, hence the use of `warning`. We'd need to implement a new output format for this. Would you be willing to implement this?

**Comment by ileitch** [comment]
2.17.0 added the `--relative-results` option.
