### ISSUE TITLE
Could not find Package.swift in this directory or any of its parent directories.

### ISSUE THREAD

**Issue by amirhosseinpy** [peripheryapp/periphery#532]
Periphery requires `Package.swift `to run when using SPM, but now, Xcode is handling the `Package.swift`.  
I am using Xcode 14.0.1.

**Comment by ileitch** [comment]
Are you saying your project no longer has a `Package.swift` file, yet you're still using SPM? Either this is a new feature in Xcode 14 I'm not aware of, or the location of our `Package.swift` may have changed.

**Comment by amirhosseinpy** [comment]
Yes, Xcode is handling `Package.swift` files now.

**Comment by ileitch** [comment]
Can you please provide a demonstration project that's using SPM without a Package.swift?

**Comment by amirhosseinpy** [comment]
Now, in this address: xcshareddata->swift pm -> Package.resolved
xcode manages dependancies. 
User just need to add a package through project -> Package Dependancies -> + 
all other management handles by xcode and Package.resolved changes.

**Comment by ileitch** [comment]
It doesn't matter if Xcode is using SPM dependencies internally, from Periphery's perspective you're using an Xcode project.  How exactly are you trying to run Periphery?

**Comment by ileitch** [comment]
Closing due to no response.
