### ISSUE TITLE
False positive on private init

### ISSUE THREAD

**Issue by michaellevel** [peripheryapp/periphery#535]
I trimmed down my code to a reproducible example:
```
    struct S {
        init() {}
        private init(private: Bool) {} // Initializer 'init(private:)' is unused
        func usePrivate() -> Self {
            Self(private: true)
        }
    }
```

I do use the struct and the private init by calling the `usePrivate()` function.

**Comment by ileitch** [comment]
Unfortunately, this is a known issue caused by a bug in the Swift compiler. https://github.com/peripheryapp/periphery/issues/264
