### ISSUE TITLE
error: This version of Periphery only supports Swift >= 5.6, you're using Apple Swift version 5.5

### ISSUE THREAD

**Issue by dev-iayush27** [peripheryapp/periphery#539]
I used this command to install Periphery:
```
brew install peripheryapp/periphery/periphery
```

But I am getting error while using this command:
```
periphery scan --setup
```
The error is:
`error: This version of Periphery only supports Swift >= 5.6, you're using Apple Swift version 5.5
`

Please provide brew install command for swift version 5.5

**Comment by ileitch** [comment]
Version 2.9.0 is the last version to support Swift 5.5, I'm not sure if it's possible to install old versions via Homebrew, but you can download the binary directly from the releases page: https://github.com/peripheryapp/periphery/releases/tag/2.9.0
