### ISSUE TITLE
Possible enhancement of listing unavailable initializers and methods

### ISSUE THREAD

**Issue by crownvic** [peripheryapp/periphery#546]
If this problem affects many people, I suggest a flag to disable reporting on unavailable methods and initializers.

For example, I often do all the UI in code, so making available some required initializers doesn't make any sense:

```swift
@available(*, unavailable)
required init?(coder: NSCoder) {
    fatalError()
}
```
Periphery reports this as such:
_warning: Initializer 'init(coder:)' is unused_

The output is hard to read because I have tons of these inits in a project. A command-line flag to disable reporting of such methods would be great.

**Comment by ileitch** [comment]
This is a great suggestion, thank you. I will try to implement this soon.

**Comment by ileitch** [comment]
Hmm, I'm actually unable to reproduce these warnings. These initializers should be retained because they relate to the function defined in `UIViewController`, even if they're not used directly in your codebase. Could you please provide a more complete example demonstrating the warning?

Also, what version of Periphery and Swift are you using?

**Comment by crownvic** [comment]
> Also, what version of Periphery and Swift are you using?

Hello, Ian, and happy New Year!

Actually, I thought you fixed this in the latest Periphery version since all the warnings disappeared.

**This environment doesn't show any warnings:**

[version] 2.10.3
[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
[shell] /usr/bin/env xcodebuild -version
Xcode 14.2
Build version 14C18

**Comment by ileitch** [comment]
Happy new year to you too!

I'm honestly not sure if this is something I fixed or Apple did. But either way, I'm glad it's fixed 😃

**Comment by Kaspik** [comment]
I'm not sure what we are doing wrong but we can see those false positives on our project.
<img width="1130" alt="Image" src="https://github.com/user-attachments/assets/cbed69be-b6a8-4097-a62d-c25cb96bb82f" />
