### ISSUE TITLE
False positive: Assigned but never used. Shortened Guard statement (Swift 5.7)

### ISSUE THREAD

**Issue by patryk-sredzinski** [peripheryapp/periphery#549]
In example provided below Periphery claims that delegate is not used which is not true.

```swift
import Foundation

protocol SampleDelegate: AnyObject {
    func doSomething()
}

protocol SampleClass {
    func setDelegate(_ delegate: SampleDelegate?)
    func run()
}

class SampleClassImpl {
    weak var delegate: SampleDelegate? // ⚠️ Property 'delegate' is assigned, but never used
}

extension SampleClassImpl: SampleClass {
    func setDelegate(_ delegate: SampleDelegate?) {
        self.delegate = delegate
    }
    
    func run() {
        guard let delegate else { return } // ◀️ Delegate is used here, but not recognized by Periphery
        delegate.doSomething()
    }
}
```

Changing the line:
```swift
guard let delegate else { return }
```
to:
```swift
guard let delegate = delegate else { return }
```
solves the issue, although It would be nice Periphery supports new shortened if let and guard let that came out in Swift 5.7.

**Comment by ileitch** [comment]
What version are you using? 2.10.2 contains a workaround for shorthand let syntax.

**Comment by patryk-sredzinski** [comment]
I am using the 2.10.2.

I was trying to make a simpler case with this shortened guard case, and it worked well. Using protocols for a class like on the example causes the false positive.

**Comment by ileitch** [comment]
Gotcha, I'll take a look into this. Thanks for reporting!

**Comment by patryk-sredzinski** [comment]
@ileitch Have you got a chance to take a look into this? Do you need my assistance? Do you want me to provide you more sample codes?

**Comment by ileitch** [comment]
@patryk-sredzinski I'm unable to reproduce the warnings you're seeing using your sample code. Could you please double-check your example and Periphery version?

**Comment by patryk-sredzinski** [comment]
Sure, will take a look tomorrow.

**Comment by patryk-sredzinski** [comment]
@ileitch You were right.
2.10.1 -> 2.10.3

It was failing on 2.10.1, but works properly on 2.10.3
Thanks

**Comment by ileitch** [comment]
@kimi-work can you please provide an example of the failure you're seeing?

**Comment by Servus7** [comment]
@kimi-work using 2.12.0 i'm able to reproduce it after changing to shorthand optional binding.
But only for computed properties declared in extensions.
