### ISSUE TITLE
Projects not found within a workspace if placed within a folder group

### ISSUE THREAD

**Issue by christianklotz** [peripheryapp/periphery#55]
Projects are not found within a workspace if they're inside a container group backed by a folder.

`.xcworkspace`
- **Parent Project:** `Periphery Bug Report.xcodeproj`
- **Group:** `Modules`
    - **Nested Project:** `Nested Framework Module.xcodeproj`

## Steps to reproduce

1. Download [periphery-bug-nested-projects.zip](https://github.com/peripheryapp/periphery/files/3749064/periphery-bug-nested-projects.zip)
1. Unarchive ZIP file
1. Run `periphery scan` within the uncompressed same folder (containing `Periphery Bug Report.xcworkspace`)

## Expected result

`periphery` to pick up all targets across both projects:
- `Periphery Bug Report/Periphery Bug Report.xcodeproj`
- `Modules/Nested Framework Module/Nested Framework Module.xcodeproj`

## Actual result

`periphery` fails with an error, not finding `Nested Framework Module.xcodeproj`.

```log
warning: No such project exists at '/periphery-bug-nested-projects/Nested Framework Module/Nested Framework Module.xcodeproj', referenced by /periphery-bug-nested-projects/Periphery Bug Report.xcworkspace/'.
```

The path is incorrect, missing the `Modules` group container location as part of the full path to the project. Instead it should look as follows:

```patch
- /periphery-bug-nested-projects/Nested Framework Module/Nested Framework Module.xcodeproj
+ /periphery-bug-nested-projects/Modules/Nested Framework Module/Nested Framework Module.xcodeproj
```

**Comment by gfpoliva** [comment]
Are you getting this error? `The project doesn't contain a .pbxproj`

**Comment by christianklotz** [comment]
Not as far as I can tell, it’s the `warning: No such project exists …` as described above without any further detail

**Comment by yasirmturk** [comment]
`The project doesn't contain a .pbxproj file at path` and <path> is root of that directory where it should be <path>/<xyz>.xcproj/

**Comment by HardysLarry** [comment]
I still have this problem. My folder structure is this one: 
```
MyProject <folder>
- MyProject.xcworkspace
- Package1 <folder>
- PackageN <folder>
- MyProject <folder>
-- MyProject.xcodeproj
```

Executing a "periphery scan" in the top folder is working fine.
However, I cannot succeed in creating the build phase so that periphery is executed, getting always that "doesn't contain a .pbxproj".
