### ISSUE TITLE
unsafe build flags

### ISSUE THREAD

**Issue by rarias84** [peripheryapp/periphery#552]
Using any version I receive
error: the target 'PeripheryKit' in product 'periphery' contains unsafe build flags
error: the target 'PeripheryKit' in product 'DangerSwiftPeriphery' contains unsafe build flags

.package(url: "https://github.com/taji-taji/DangerSwiftPeriphery.git", from: "1.3.0")
.product(name: "DangerSwiftPeriphery", package: "DangerSwiftPeriphery")

**Comment by ipodishima** [comment]
I have the same issue

**Comment by rarias84** [comment]
any solution?

**Comment by ileitch** [comment]
This is fixed in `master` and will be released soon.

**Comment by ileitch** [comment]
This is fixed in 2.10.3, please run `swift package update periphery`.
