### ISSUE TITLE
False positive for UIAlertAction handler

### ISSUE THREAD

**Issue by michalnowak061** [peripheryapp/periphery#577]
Hi, in this case `handleAlertAction` is marked as unused but looks like it's being used. Can you check this?

```
 let action = UIAlertAction(
      title: "",
      style: .default,
      handler: handleAlertAction
)
  
func handleAlertAction(_ action: UIAlertAction) {}
```

version: 2.12.0
Xcode: 14.2

Thank you for this useful tool. Kind regards :)

**Comment by ileitch** [comment]
Hi @michalnowak061, this example isn't complete enough for me the diagnose the issue. Could you please create an Xcode project demonstrating the issue?

**Comment by ileitch** [comment]
Closing due to no response.
