### ISSUE TITLE
Either the index store is outdated

### ISSUE THREAD

**Issue by 673697831** [peripheryapp/periphery#579]
### Discussed in https://github.com/peripheryapp/periphery/discussions/407

<div type='discussions-op-text'>

<sup>Originally posted by **trungld123** September 30, 2021</sup>
"The index store at '/Users/Abc/Library/Caches/com.github.peripheryapp/DerivedData-a4afb026-5ddbe9bd/Index/DataStore' does not contain data for the following targets: "abcApp". Either the index store is outdated, or you have requested to scan targets that have not been built."
i dont know error when run "periphery scan --setup" at terminal command line</div>

**Comment by dvilceanu-ae** [comment]
periphery scan --clean-build helped

**Comment by dvilceanu-ae** [comment]
I am facing the same issue.
Is there a solution?

**Comment by ileitch** [comment]
What version are you using? Can you please double-check that the target mentioned in the error is indeed built by your chosen scheme?

**Comment by danielepantaleone** [comment]
I'm facing the same issue. Any update on this?

**Comment by ileitch** [comment]
@danielepantaleone 
> What version are you using? Can you please double-check that the target mentioned in the error is indeed built by your chosen scheme?

**Comment by LevinIvan** [comment]
I have the same problem :(

**Comment by LevinIvan** [comment]
I have the same problem. How can I solution this problem?

**Comment by danielepantaleone** [comment]
> @danielepantaleone
> 
> > What version are you using? Can you please double-check that the target mentioned in the error is indeed built by your chosen scheme?

I'm using version **2.12.1**. It's actually quite strange because it doesn't fail every time. I have periphery running using a SonarQube plugin (https://github.com/insideapp-oss/sonar-apple) and sometime periphery analysis complete successfully (3 out of 5 analysis are failures though)

**Comment by andrsem** [comment]
I was able to reproduce this issue for a multiplatform SwiftUI app. Version 2.12.3. 

Create a new Swift file, go to Build Phases > Compile Sources, and then deselect "Allow any platform" and "macOS" in the Filters column so that only "iOS" is selected. I hope this helps.

**Comment by bastianmorath** [comment]
I have the exact same problem.
