### ISSUE TITLE
Need help to use XCode 11 branch

### ISSUE THREAD

**Issue by DracoRubi** [peripheryapp/periphery#58]
I've installed periphery via homebrew, and its usage is pretty straightforward, just open the terminal and execute `periphery scan`. But due to the XCode 11 issues, I can't do that.

So, I'm trying to use the XCode 11 branch, to see if I can work with that, but I don't even know how to start. Quoting from [this](https://github.com/peripheryapp/periphery/issues/49#issuecomment-558989867) thread: 
> If I run PeripheryKit or Periphery-Package scheme, nothing seems to happen, and if I run periphery scheme, it crashes with:
> ```
> dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
> Reason: image not found
> ```
> So yeah, I'm still clueless ^^''
> Should I open another thread to avoid going offtopic here?

My question is: How exactly can I use the XCode 11 branch to scan my project?

**Comment by ileitch** [comment]
The xcode project is only used for running tests. Since periphery is a command-line app, you must run it from the command line. Checkout `scripts/scan`.

**Comment by DracoRubi** [comment]
Running `/.../Documents/periphery/scripts/scan` --workspace [worspace-directory] --target [my-target] --scheme [my-scheme] only makes it to complain:
`make: *** No rule to make target `build'.  Stop.`

I have the feeling that I'm missing something really dumb, but I'm not used to Mac nor using the Terminal.

**Comment by ileitch** [comment]
`cd` to the `periphery` directory first, then run `scripts/scan`.

**Comment by DracoRubi** [comment]
In the periphery directory, `scripts/scan --workspace [worspace-directory] --target [my-target] --scheme [my-scheme]` results in:
```
error: You must supply either the --workspace or --project option, not both. If your project uses an .xcworkspace to integrate multiple projects, then supply the --workspace option. Otherwise, supply the --project option.
```

**Comment by ileitch** [comment]
`scripts/scan` is just a helper for analyzing Periphery itself, look at the script contents to see how it calls the binary.

**Comment by DracoRubi** [comment]
Finally, managed it to work! Thanks a lot!!
