### ISSUE TITLE
Exclude recently changed lines 

### ISSUE THREAD

**Issue by erkekin** [peripheryapp/periphery#582]
In my team we don't want to use `//periphery: ignore` given we believe we will forget removing comments in the future. That's why we came to agree that periphery may provide an API to exclude outputting lines which has recently changed.

in order to ignore the lines which has been modified in the last week, we can call

`periphery scan --exclude-lines-modified-before 7`

so that teams which don't want to use comments in their code can benefit from the API.

**Comment by ileitch** [comment]
Ideally, this would be solved by detecting superfluous ignore comments (#427). To that end, I don't think this is something I will implement, as it ties Periphery to a particular SCM (git, I assume).

With a little script, you should be able to implement this quite easily yourself by post-processing the out.

**Comment by erkekin** [comment]
nice, thank you
