### ISSUE TITLE
report_exclude not working after upgrade to 2.12.2

### ISSUE THREAD

**Issue by Servus7** [peripheryapp/periphery#595]
We're using periphery on a regular basis and upgraded to 2.12.2 today. As stated in the title, `report_exclude` is no longer working and we get hundreds of warnings now.
- Previous version was 2.12.1.
- `.periphery.yaml` is used for configuration

**Comment by ileitch** [comment]
Can you please provide the patterns you're using?

**Comment by Servus7** [comment]
```
# Excludes
report_exclude:
- ../**/Generated/*.swift
- Tests/Spry/**/*
- Tests/**/*Spy.swift
```

**Comment by ileitch** [comment]
Are they all not working, or perhaps only the one with the leading ..? I'm curious why you need to reference a directory above your project root?

**Comment by Servus7** [comment]
None of them is working.
We're using Cocoapods. Root only contains tests and an example app. The plugin we develop is one directory above due to company guidelines.

**Comment by ileitch** [comment]
Which directory are you running it from? Is it fixed if you change directory?

**Comment by Servus7** [comment]
It's running from the Example directory.
```
├── App.podspec
├── Example
│   ├── App
│   │   └── AppDelegate.swift
│   ├── App.xcodeproj
│   ├── App.xcworkspace
│   ├── Podfile
│   ├── Pods
│   ├── Resources
│   ├── Tests
│   │   ├── Spry
│   │   │   └── *.swift
│   │   └── Unit Tests
│   │       └── *.swift
│   ├── build.xcconfig
│   └── swiftgen.yml
├── Example.xcodeproj
│   ├── project.xcworkspace
│   ├── xcshareddata
│   └── xcuserdata
├── Pod
│   ├── Classes
│   │   ├── *.swift
│   │   ├── *.storyboard
│   │   └── *.xib
│   └── Generated
│       └── *.swift
├── Podfile.lock
├── README.md
└── _Pods.xcodeproj -> Example/Pods/Pods.xcodeproj
```

**Comment by Servus7** [comment]
Thank you for your fast response.
But how do we test master? Using Cocoapods I can fetch master but it's missing the executable like a release.

**Comment by bryanmontz** [comment]
Sorry, but I also don't know how to install from a commit. I use homebrew to install periphery. Are there instructions for that somewhere?

**Comment by ileitch** [comment]
Sorry, I should have mentioned it. It's pretty simple:

1. Clone this repo
2. run `swift build`
3. The `periphery` binary should exist at `.build/debug/periphery`

**Comment by Servus7** [comment]
Definitely pretty simple.

I can confirm your fix is working.

But I had to change one path from `Tests/Spry/**/*.swift` to `Tests/Spry/*.swift`. Seems like `/**/` is no more working if there are no nested directories.

**Comment by ileitch** [comment]
Thanks for trying it out, 2.12.3 has been released. It's unfortunate the behavior isn't exactly the same, but it's well worth it for the performance improvement.
