### ISSUE TITLE
Recognising used variables as unused

### ISSUE THREAD

**Issue by NagarajBasarkod** [peripheryapp/periphery#596]
Variables are declared in super class, but used in subclasses or used as typecasted in other classes are treated as unused.

ex: 
```
class Water {
var color: String?
}

class Resources {
  func naturalResource() {
    let waterOptional = water()
    if let water = waterOptional {
      water.color = "Clear"
    }
  }
}
```
according to periphery, color is an unused variable in class Water

**Comment by ileitch** [comment]
Thank you @NagarajBasarkod. It would be extremely helpful if you provide a sample project so that I can reproduce the issue. Thanks!

**Comment by ileitch** [comment]
Closing due to lack of sample project to reproduce the problem.
