### ISSUE TITLE
How to resolve "Units have conflicting build targets" error?

### ISSUE THREAD

**Issue by igz** [peripheryapp/periphery#597]
We have some types that are used both on our main iOS app target and its Apple Watch extension. These types are not grouped into their own module/framework. This results in a "Units have conflicting build targets" error, which I assume is due to the architectures being different. Is there a recommended way to avoid this conflict, short of duplicating code, creating modules, or creating a new target?

```
Found conflicting index store units for [path-to-file] in module 'WatchCompanion_Extension'. The units have conflicting build targets: arm64-apple-ios14.0-simulator, arm64-apple-watchos6.2-simulator, i386-apple-watchos6.2-simulator, x86_64-apple-watchos6.2-simulator.
```

**Comment by ileitch** [comment]
Hey @igz,

Are you using the `--index-store-path` option to provide a store built by Xcode? If so, you can let Periphery perform the build instead, in which case it'll use a different DerivedData path, and only generate units for a single target triple.

If not, I'm not sure how you would have gotten into this situation other than explicitly running Periphery with multiple times with different `-- -destination=....` arguments. You can use the `--clean-build` flag to fix this.

Ideally, Periphery should be able to figure out which units to use and avoid this error entirely, but I've not looked into that yet.

**Comment by igz** [comment]
Thanks for that. I've tried both ways, actually. I tried the Periphery build first, and added the `--index-store-path` to try and troubleshoot, to no avail. I just tried both again with `--clean-build`, and am still getting the error.

Do you think this could be due to including source files in multiple modules (in this case, the main app and watch extension)?

**Comment by ayyappa-s** [comment]
I am also facing similar issue although I am leaving the build process with periphery completel. my judgement is this started coming only after specifying additional build parameters let me show you the command which I used. 

> periphery scan --clean-build --verbose -- -sdk iphonesimulator -arch arm64

also kindly note on the derived data folder here `<>/Library/Caches/com.github.peripheryapp/DerivedData-72ff7eee-e0a9d8bf-86df88ee/Index.noindex/DataStore/v5/units` there are two <sourcefilename>.0-<randomhash> files in the past it used be just one file. please guide what's missing here. using version `2.21.1`

**Comment by ldakhoa** [comment]
I'm also facing this issue, I've tried scanning single targets and schemes. Then iOS and watchOS targets and schemes, but still getting the error.
```
Found conflicting index store units for 'Path/To/My/Project/' in module 'Common'. This units have conflicting build targets: arm64-apple-watchos6.0-simulator, i386-apple-watchos6.0-simular, x86_64-apple-ios14.0-simulator, x84_64-apple-watchos6.0-simulator
```
I have also tried using `--index-store-path` and `--clean-build` but have had no luck. Using version `2.12.2`

**Comment by thedavidharris** [comment]
> Do you think this could be due to including source files in multiple modules (in this case, the main app and watch extension)?

This is what's occuring: the same file is present in a framework compiled for iOS but also a watchOS app, since those are two different bundles, and periphery finds the same source file in both. Unsure on the workaround for this.

**Comment by ileitch** [comment]
Does specifying a simulator destination prevent compilation of the watchOS support?

An example project that reproduces the problem would be very helpful.

**Comment by willnix86** [comment]
Any more updates on this? We're facing this issue in a workspace where we need to build both "production" and 
test targets because otherwise we get false "unused" warnings

**Comment by iletai** [comment]
> Hey @igz,
> 
> Are you using the `--index-store-path` option to provide a store built by Xcode? If so, you can let Periphery perform the build instead, in which case it'll use a different DerivedData path, and only generate units for a single target triple.
> 
> If not, I'm not sure how you would have gotten into this situation other than explicitly running Periphery with multiple times with different `-- -destination=....` arguments. You can use the `--clean-build` flag to fix this.
> 
> Ideally, Periphery should be able to figure out which units to use and avoid this error entirely, but I've not looked into that yet.

If using `--index-store-path` we not fix when this issues occurs?

**Comment by jpeckner** [comment]
Hey all- I was facing this exact issue (Periphery 2.12.3 / Xcode 14.3), and fortunately was able to fix it using [this answer](https://github.com/peripheryapp/periphery/issues/579#issuecomment-1491838908) as a hint. The error I was getting was `Found conflicting index store units for '<filepath_redacted>' in module 'Shared'` (`Shared` is an Xcode project in my own repo, not linked via a dependency manager). So in `Shared`, I went to Build Phases --> Compile Sources, and changed every single file from "Allow any platform" to just iOS.

I have to run Periphery with `--clean-build` to avoid the error (didn't have to do that in the past), but I can live with that.

<img width="1556" alt="Screenshot 2023-04-25 at 9 57 14 AM" src="https://user-images.githubusercontent.com/19365492/234350681-62a65b75-d10b-4939-b827-97e7e4987418.png">

**Comment by CraigSiemens** [comment]
We ran into this similar error as well. In our case it was caused by our aggregate target adding our app as a target and use the index store produced by Xcode. It seems like Xcode can modify the index store or leaving it in a wierd state that periphery can't handle.

Our goal was to allow sharing the incremental builds between our app scheme and the aggregate target scheme so that the build time could be nearly instant when switching schemes. It'd also allow Xcode to properly show warnings and errors from building the app instead of periphery wrapping the errors so they aren't quite presented the same way.

**Comment by ileitch** [comment]
Sorry for the long wait, but I'm finally getting around to fixing this. Could a couple of you please give the attacthed beta build a try? It _should_ just work 🤞, no need to change any parameters. 

[periphery.zip](https://github.com/peripheryapp/periphery/files/11927296/periphery.zip)

**Comment by ptxmac** [comment]
I just tested the beta on a project that previously failed and I'm happy to report that it works now!
🎉

**Comment by ileitch** [comment]
Awesome, thanks for trying it out @ptxmac. If you don't mind, could you please give it another test with this build? 
[periphery.zip](https://github.com/peripheryapp/periphery/files/11929174/periphery.zip)

**Comment by ptxmac** [comment]
Done, that works too

**Comment by igz** [comment]
Thanks @ileitch! A little late to the party, but I'm confirming the beta and latest release fix my reported issue as advertised.
