### ISSUE TITLE
Why not generate the build log using a dry run?

### ISSUE THREAD

**Issue by michaeleisel** [peripheryapp/periphery#60]
Xcodebuild supports dry runs with the `-n` flag. That seems like it'd speed things up

**Comment by ileitch** [comment]
Dry runs aren't accurate unfortunately. This is the response I got from an Apple engineer:

> Unfortunately a "dry run" of a build is kind of a conceptually-broken thing to do, since a build can discover new work that it needs to perform during the build, so a "dry run" may output incomplete or incorrect information about what work would be done.
