### ISSUE TITLE
 Cannot calculate full path for file element "RichTextRenderer/RichTextRenderer.xcodeproj" in source root

### ISSUE THREAD

**Issue by arthopar** [peripheryapp/periphery#601]
The issue occurs for all pods.
ENV. Xcode 14, Cocoapod version 1.11.2

 periphery scan --workspace MyProject.xcworkspace --schemes MyProject --targets MyProject
* Inspecting project...
error: (PBXProjError) Cannot calculate full path for file element "RichTextRenderer/RichTextRenderer.xcodeproj" in source root: "/Users/myname/MyProject"

**Comment by ileitch** [comment]
This is an issue with [XcodeProj](https://github.com/tuist/XcodeProj). Unfortunately I'm unable to help without a sample project that demonstrates the issue. Are you able to provide one?

**Comment by ileitch** [comment]
Closing due to no response.
