### ISSUE TITLE
False Positive for class initializer with protocol type.

### ISSUE THREAD

**Issue by chauhan130** [peripheryapp/periphery#608]
Thank you for this beautiful library! 👏
 
I discovered a false positive that I would draw your attention to:

```warning: Initializer 'init(p:)' is unused```

Example:
```
protocol P {
}

class C1: P {
  init()
}

class C2 {
  init(p: P)
}

let c1 = C1()
let c2 = C2(p: c1) // <-- Unused warning.
```

periphery version: 2.12.3

**Comment by ileitch** [comment]
@chauhan130 I'm unable to reproduce this, can you please provide a sample Xcode project that reproduces the problem? Thanks.

**Comment by ileitch** [comment]
Closing due to no response.
