### ISSUE TITLE
The package product 'SwiftSyntax' requires minimum platform version 13.0 for the iOS platform, but this target supports 11.0

### ISSUE THREAD

**Issue by ayumakesit** [peripheryapp/periphery#613]
Hi guys,

after installing periphery I get the following error message in Xcode:
![image](https://github.com/peripheryapp/periphery/assets/24713764/4789e9a9-2005-4fe1-b6d8-6c85c4584427)

I first installed periphery via homebrew and then added the package via the Xcode UI.
After that I executed the command "periphery scan --setup" which was successful at first.

Any help is appreciated.
Thank you!

**Comment by ileitch** [comment]
@ayumakesit Sorry but Periphery isn't currently supported via SwiftPM, it was incorrect for it to be listed in the README. Please use one of the other intallation methods.
