### ISSUE TITLE
Get index store from xcodebuild 

### ISSUE THREAD

**Issue by ShamrinIgor** [peripheryapp/periphery#618]
Hello! Is it possible to get index store from xcodebuild CLI? I would like to get index store after build step on CI, and after that use periphery with `--skip-build` flag. I use this command to build project on CI:
```
xcrun xcodebuild archive -archivePath "$PWD/.ci_build/MyProjectxcarchive" -scheme MyProject -configuration Debug -destination "generic/platform=iOS" -project "$PWD/MyProject.xcodeproj" -derivedDataPath "$PWD/.ci_build/derived_data"
```
However, in derived_data I have't `Index/DataStore` folder. 

I also tried passing `COMPILER_INDEX_STORE_ENABLE = YES` as swift compiler flag, but the result was the same.

**Comment by ileitch** [comment]
I'm not aware of an automated to get the index store path, unfortunately. Perhaps the index store is implicitly disabled for archive builds?
