### ISSUE TITLE
IndexStoreError

### ISSUE THREAD

**Issue by NikKovIos** [peripheryapp/periphery#627]
Xcode Version 14.2 (14C18)
periphery: 2.14.1 (via brew)

```
* Building MyTarget...
[shell] /usr/bin/env xcodebuild -workspace /Users/user/r/MyTarget/MyTarget.xcworkspace -showBuildSettings -scheme MyTarget build test
[shell] /bin/sh -c xcodebuild -workspace '/Users/user/r/MyTarget/MyTarget.xcworkspace' -scheme 'MyTarget' -parallelizeTargets -derivedDataPath '/Users/user/Library/Caches/com.github.peripheryapp/DerivedData-880b40b0-9e43f80c' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf"
* Indexing...
error: (IndexStoreError) internalError("index store path does not exist: /Users/user/Library/Caches/com.github.peripheryapp/DerivedData-880b40b0-9e43f80c/Index/DataStore")
```

error: (IndexStoreError) internalError("**index store path does not exist**: /Users/user/Library/Caches/com.github.peripheryapp/DerivedData-880b40b0-9e43f80c/Index/DataStore")

What should I do to fix that?

**Comment by ileitch** [comment]
@NikKovIos can you please double check you're using the correct version? The `xcodebuild` command is missing the `COMPILER_INDEX_STORE_ENABLE=YES` option that was [added in 2.12.2](https://github.com/peripheryapp/periphery/commit/e1d66e63772561c945644da21d20c46fb0bfc359).

**Comment by ileitch** [comment]
@fpt-duytn20 Can you please copy the output when running Periphery with the `--verbose` option.
