### ISSUE TITLE
2.15.0 error: dyld[2808]: Symbol not found: (_$s10Foundation10NSNotFoundSivg)

### ISSUE THREAD

**Issue by noveogithub** [peripheryapp/periphery#633]
When running version 2.15.0 via terminal I get the following error:
```
dyld[2808]: Symbol not found: (_$s10Foundation10NSNotFoundSivg)
  Referenced from: '../periphery'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'
```

2.14.1 works fine except multi-platform indexing.

Can you help me please?

**Comment by keith** [comment]
This likely means the deployment target is too high

**Comment by noveogithub** [comment]
@keith iOS 13, strange that it's too high. I don't understand why the issue is only with 2.15.0

**Comment by ileitch** [comment]
@noveogithub Are you using macOS 12? 2.15.0 is built for 13+.

**Comment by noveogithub** [comment]
Right! My bad! Thank you!

**Comment by noveogithub** [comment]
Right! My bad! Thank you!

**Comment by ileitch** [comment]
Sorry about that, let me update the changelog to make that clear.
