### ISSUE TITLE
Error when using periphery 2.15.0 without Swift 5.8

### ISSUE THREAD

**Issue by amleszk** [peripheryapp/periphery#636]
I think this error is caused by not having the latest Xcode. using version 2.14.1 instead fixes the problem. Maybe a more friendly error can be reported instead

```
dyld[620]: Symbol not found: (_$s10Foundation10NSNotFoundSivg)
  Referenced from: '/usr/local/Caskroom/periphery/2.15.0/periphery'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'
```

**Comment by ileitch** [comment]
This is likely caused by using macOS 12, which is no longer supported as of 2.15.0
