### ISSUE TITLE
supports Swift >= 5.8

### ISSUE THREAD

**Issue by siddheshredkar** [peripheryapp/periphery#637]
error: This version of Periphery only supports Swift >= 5.8, you're using swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0.

**Comment by ileitch** [comment]
Is there something unclear about this error message?

**Comment by siddheshredkar** [comment]
try to run -> periphery scan --setup 
on M2 -> getting this error

**Comment by ileitch** [comment]
Please read the error message.

**Comment by siddheshredkar** [comment]
@ileitch As error saying supports Swift >= 5.8 , have upgrade Xcode Version 14.3.1 (14E300c) , which supports swift 5.8
and resolved the above error
