### ISSUE TITLE
CodeClimate reporter doesn't generate relative paths

### ISSUE THREAD

**Issue by shuguenot** [peripheryapp/periphery#638]
Command : `.bin/periphery scan --format codeclimate --clean-build --strict`

Output : 
```
[
  {
    "fingerprint" : "s:3App17AccountControllerC013accountSearchC033_06524B757E79842A7D554428D31064B3LLAA0beC0CSgvp",
    "location" : {
      "path" : "\/Users\/admin\/Developer\/ios\/Project\/App\/Sources\/Classes\/Accounts\/AccountController.swift",
      "lines" : {
        "begin" : 17
      }
    },
    "severity" : "major",
    "description" : "Property 'accountSearchController' is assigned, but never used"
  }
]
```

Current directory is the project root directory, where .periphery.yml is located : `/Users\/admin\/Developer\/ios\/Project`

We expect the json[].location.path to be relative : `\/App\/Sources\/Classes\/Accounts\/AccountController.swift`

**Comment by shuguenot** [comment]
Additionally, the path doesn't need to be escaped and could be "path" : "/Project/App/Sources..."

**Comment by ileitch** [comment]
@shuguenot none of the output formats use relative paths, so this working as expected. Chaning that would likely cause issues for people, I think we'd need to introduce a new `--relative-output-paths` option or similar.

**Comment by ileitch** [comment]
Escaping issues fixed here: https://github.com/peripheryapp/periphery/commit/cd5e1207d9f4554157a2470c3975df432eebc4cc

**Comment by shuguenot** [comment]
> @shuguenot none of the output formats use relative paths, so this is working as expected. Chaning that would likely cause issues for people, I think we'd need to introduce a new `--relative-output-paths` option or similar.

This option would be great indeed !
