### ISSUE TITLE
False positive: Public extension of generic protocol

### ISSUE THREAD

**Issue by drekka** [peripheryapp/periphery#648]
Periphery: 2.15.0

First off guys, let me say that having worked on many large and messy legacy enterprise projects, having a tool such as Periphery to hunt dead code is really cool.

Now onto the issue I think I've found :-)

If I have a public extension of a protocol with a generic declaration it appears that Periphery is not picking up that a function inherits `public` access. 

Here's some sample code I added to a project to illustrate the issue. This is in a SPM module that's part of a larger project.

```swift
// Simple protocol extension is fine.
public protocol Protocol {}

public extension Protocol {
    func foo() {}
}

// Protocol with associated type extension is fine.
public protocol AssociatedTypeProtocol {
    associatedtype Value
}

public extension AssociatedTypeProtocol where Value == Int {
    func foo() {}
}

// Protocol with generic argument throws warning.
public protocol GenericProtocol<Value> {
    associatedtype Value
}

public extension GenericProtocol<Int> {
    func foo() {} // Unexpected 'Function 'foo()' is unused' warning.
}
``` 

As you can see, a function added to a simple protocol, or a protocol with an associated type is detected as being public because the protocol is public. However the protocol with the associated type set by a generic argument triggers a warning on the function, indicating it is unused when in fact it is public and should not trigger.

As this is a SPM module I built in (Xcode 14.3.1) from the command line like this:

```
xcodebuild -scheme Toolbox -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 12' -derivedDataPath '.build' -skipPackagePluginValidation clean build
```

I then ran periphery like this:

```
derekclarkson@Drax Modules % periphery scan --skip-build --index-store-path '.build/Index.noindex/DataStore/' --retain-public --targets Toolbox
* Inspecting project...
* Indexing...
* Analyzing...

/Users/derekclarkson/projects/my-project/Modules/Sources/Toolbox/ProtocolExtensionIssue.swift:66:10: warning: Function 'foo()' is unused

* Seeing false positives?
 - Periphery only analyzes files that are members of the targets you specify.
   References to declarations identified as unused may reside in files that are members of other targets, e.g test targets.
 - Periphery is a very precise tool, false positives often turn out to be correct after further investigation.
 - If it really is a false positive, please report it - https://github.com/peripheryapp/periphery/issues.
```

Whilst probably an edge case, it is throwing up warnings in a number of places in our code where we're adding extensions to both project protocols and Swift provided protocols such as `Sequence<Int>`, etc.

**Comment by ileitch** [comment]
Hey @drekka, thanks for the kind words. Do you also have the code demonstrating how `foo()` is called?
