### ISSUE TITLE
DataStore folder not found

### ISSUE THREAD

**Issue by DDDDDDDOU** [peripheryapp/periphery#649]
I build my project with cmd:
`xcodebuild archive -workspace "${WORKSPACE_PATH}" \
-scheme "${PROJECT_SCHEME}" -configuration "${PPOJECT_CONFIGURATION}" -archivePath "${IPA_OUTPUT_DIR}/${PROJECT_NAME}" -derivedDataPath "${BUILD_PATH}" clean build -quiet`

I specified derivedDataPath, but only found files below
<img width="601" alt="image" src="https://github.com/peripheryapp/periphery/assets/48237560/766f8f79-5064-4c6e-9e11-87c20345f23f">

how can I found the folder "DataStore" in this case? I have no idea 😭

**Comment by ileitch** [comment]
You're generating an archive, so not index store is produced. Try adding `COMPILER_INDEX_STORE_ENABLE=YES` to the command.

**Comment by DDDDDDDOU** [comment]
Thanks！It works！

**Comment by DDDDDDDOU** [comment]
> You're generating an archive, so not index store is produced. Try adding `COMPILER_INDEX_STORE_ENABLE=YES` to the command.

Thanks！It works！

**Comment by ShamrinIgor** [comment]
@DDDDDDDOU Could please you show me what the derived Data folder looks like after archive with the `COMPILER_INDEX_STORE_ENABLE=YES` option? I tried to run `xcodebuild archive` with this option, but the DataStore was not created.
