### ISSUE TITLE
XCLocalSwiftPackageReference is not supported

### ISSUE THREAD

**Issue by phoenisis** [peripheryapp/periphery#653]
Hi, I'm having an issue with Xcode 15 Beta 8 on macOS 14.0. 
I'm getting the error message: `(PBXObjectError) The element XCLocalSwiftPackageReference is not supported.`

<img width="870" alt="Capture d’écran 2023-09-11 à 11 07 24" src="https://github.com/peripheryapp/periphery/assets/3032945/26606374-733e-43bc-a82e-7ebe31bf0710">

**Comment by ileitch** [comment]
Can you please try 2.15.1?

**Comment by phoenisis** [comment]
Hi, I'm having the exact same issue with the 2.15.1 version 😢. If you have any clues on how to fix it or add some verbose logs to provide more information, I'd be glad


<img width="817" alt="Capture d’écran 2023-09-18 à 08 59 47" src="https://github.com/peripheryapp/periphery/assets/3032945/70458410-be49-472e-ac3d-eb3068f3be79">

**Comment by ileitch** [comment]
It looks like `https://github.com/tuist/XcodeProj` doesn't support `XCLocalSwiftPackageReference` in its latest version. Can you please open a bug report there. Unfortunately, there's nothing I can do about this error in Periphery itself.
