### ISSUE TITLE
Xcode 15 support?

### ISSUE THREAD

**Issue by jonnyijapan** [peripheryapp/periphery#654]
I'm getting this error when running periphery on a project saved using Xcode 15 beta.

> error: Shell command '/bin/sh -c xcodebuild -project '/Users/me/repo/myproject.xcodeproj' -scheme 'myproject' -parallelizeTargets -derivedDataPath '/Users/me/Library/Caches/com.github.peripheryapp/DerivedData-2577365d-f0c77734-f0c77734' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf" COMPILER_INDEX_STORE_ENABLE="YES"' returned exit status '65':

Would the problem be the Xcode 15 beta use?
If so, when can Xcode 15 support be released?

**Comment by jonnyijapan** [comment]
Nevermind, I could fix this by running this first

> sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer

**Comment by jonnyijapan** [comment]
Would there perhaps be a way of specifying which Xcode to use to the `periphery scan ...` command?

**Comment by ileitch** [comment]
No there isn't, using `xcode-select` is the correct appoach.
