### ISSUE TITLE
Not sure how to set this up: Workspace + SPM packages scan

### ISSUE THREAD

**Issue by drekka** [peripheryapp/periphery#655]
So I have a project that is a combination of a workspace that builds an iOS application and a number of SPM modules that it uses. Most of the code is actually in the modules and the main application in the workspace is relatively thin.

What I'd like to achieve is a scan that locates any dead code, public or otherwise, scanning right from the bottom most SPM module right up to the application so I can easily remove it. The structure looks something like this:

```
Project.xcworkspace
Applications/
    Application/
        Sources
            Application.swift
 Modules
    Package.swift
    Package.resolved
    Sources
        Module1
            Something1.swift
        Module2
            Something2.swift
        ...
```

The workspace has a scheme called "Application" and a target called "Application" with Xcode doing all the necessary grunt work to make the SPM modules available to the application.

I've found that if I build in Xcode I can scan all the modules using

```
periphery scan --skip-build --index-store-path <path-to-datastore-in-derived-data>
```

However that doesn't scan the Application files and therefore there's a few false positives.

I've been trying to figure out if I can do something like this:

```
periphery scan --workspace Project.xcworkspace --schemes Application --targets Application
```

But it only picks up the Application code and doesn't recognise the modules.

So is there a way to get a complete scan in this case?

**Comment by rogerluan** [comment]
This could be related: https://github.com/peripheryapp/periphery/issues/626

**Comment by ileitch** [comment]
Yep, closing in favor of #626.
