### ISSUE TITLE
Periphery security question

### ISSUE THREAD

**Issue by tommylau-exe** [peripheryapp/periphery#657]
Hey folks! I just wanted to get confirmation that Periphery does **not** send any source code over the internet or to any 3rd party. Would someone be able to definitively confirm that for me?

I looked through the source a bit, and [the only network request I see appears to just check that your version of Periphery is up-to-date](https://github.com/peripheryapp/periphery/blob/f78ce9084e07e8d0c09f531e9885e0d5af36794e/Sources/Frontend/UpdateChecker.swift#L41). I also didn't find any related info in the Readme, so I just wanted to double-check.

**Comment by ileitch** [comment]
Hey Tom, Periphery performs analysis entirely on your local machine. As you found already, the only network request made is to check for updates.

Periphery does invoke xcodebuild/Swift to compile the project, so it's possible that some requests are made during the build phase (run scripts, etc), but none of those are made directly by Periphery.

As the author, this is a definitive answer.

**Comment by tommylau-exe** [comment]
Awesome, thanks for the quick response Ian! Love the project 😄
