### ISSUE TITLE
Error: XCLocalSwiftPackageReference is not supported

### ISSUE THREAD

**Issue by tommylau-exe** [peripheryapp/periphery#660]
# Steps

- Create an XCode 15 project with a local package dependency
- Run `periphery scan --setup` (or just `periphery scan`)

# Expectation

Periphery scans the project successfully.

# Issue

`error: (PBXObjectError) The element XCLocalSwiftPackageReference is not supported.` is logged in the terminal, and the scan is cancelled.

---

This seems to be related to some discussions in #626. Seems to be a feature request for tuist/XcodeProj, and there's already an in-progress PR: https://github.com/tuist/XcodeProj/pull/799

**Comment by ileitch** [comment]
Thanks for the heads up. I'll release a new version once XcodeProj does.

**Comment by alinfarcas12** [comment]
XcodeProj just released a new version. 😄

**Comment by geraldWilliam** [comment]
PR here: https://github.com/peripheryapp/periphery/pull/677

**Comment by geraldWilliam** [comment]
PR #677 was closed without merging. Checks failed and before I could figure out why, `master` was updated so its Package.resolved now has XcodeProj 8.16.0.

**Comment by geraldWilliam** [comment]
`periphery scan` still results in the PBXObjectError with version 2.17.1 installed from Homebrew. But if I check out the master branch and build with the debug configuration and then run that on a project with Local Packages, I don't get an error. Is there some special configuration that needs to happen for the Homebrew distribution to get updated dependencies?

**Comment by KacperCzapp** [comment]
I'm having the same issue (I created a local package to store my own macros), can you please provide an update on this?

**Comment by alinfarcas12** [comment]
Still not fixed

**Comment by sisoje** [comment]
is it possible that its not fixed yet?

**Comment by sisoje** [comment]
> I'm having the same issue (I created a local package to store my own macros), can you please provide an update on this?

hehe, I did that too :)

**Comment by Sundea** [comment]
Have this issue too. Any updates on this?

**Comment by geraldWilliam** [comment]
Hi all, I think we just need a new release but I'm not able to create one. Package.resolved in the latest release specifies XcodeProj version 8.15.0. It's 8.16.0 on the master branch and if I'm not mistaken, that's the XcodeProj version that fixes this issue. @ileitch Will you have time to cut a release soon?

**Comment by AF-cgi** [comment]
Any updates?

**Comment by ileitch** [comment]
Fixed in 2.18.0.
