### ISSUE TITLE
Shell command '/usr/bin/env xcodebuild - returned exit status '74'

### ISSUE THREAD

**Issue by njnkumar** [peripheryapp/periphery#670]
Hi Team , 

Im unable to scan the project after the successful setup . getting this xcodebuild command error 

error: Shell command '/usr/bin/env xcodebuild -project #project Path# -showBuildSettings -json -target #pjct target#' returned exit status '74':

**Comment by ileitch** [comment]
You can run that command manually to see the error.

**Comment by njnkumar** [comment]
im new to this can you please help me with how to run manually

**Comment by ileitch** [comment]
Just run this on the command line `xcodebuild -project #project Path# -showBuildSettings -json -target #pjct target#`

**Comment by im-jersh** [comment]
i'm also encountering the exact same issue but only on my CI runners. running periphery locally does not produce the same error.
