### ISSUE TITLE
Detect unused imports

### ISSUE THREAD

**Issue by CraigSiemens** [peripheryapp/periphery#678]
After running periphery to find and remove unused code, it's possible that the all the code that needed an import has been removed from the file, so the import could be removed as well.

It'd be nice if periphery could warn on any imports that are unused by the code in the file.

Cleaning up this unused code has a couple benefits.
- This helps the file clearly state to the reader which modules it uses.
- For projects with multiple modules, it'd help with determining whether module `A` still needs module `B` as a dependency. Removing the unneeded dependency generally leads to improved build time by allowing `A` to start building before or in parallel with module `B`.
- This is just a guess, but I could see the file building faster as well depending on what the compiler needs to load as a result of seeing an import in preparation for compiling the rest of the file.

**Comment by ileitch** [comment]
This is now implemented in `master`, although it's still experimental. I've identified a few cases that produce false positives that may be impossible to work around.

**Comment by ileitch** [comment]
Thanks for trying it out! This feature only works with your own projects' targets, as it needs to identify uses of @_exported, which isn't possible if Periphery doesn't have access to the source code.
