### ISSUE TITLE
`location` missing line number and column since 17.0

### ISSUE THREAD

**Issue by erikkerber** [peripheryapp/periphery#680]
It looks like the `outputPath` function introduced for the relative path feature is dropping the line/column from the description and thus output:

https://github.com/peripheryapp/periphery/commit/df4568b6697ef2831c9a2255dfc9a62365501f10#diff-309afde6b1bec106fcd91d6d2ba6a23a05ec1669104e177019257d7cf5639468L18-R26

**16.0**

```
"/Users/ekerber/Developer/slack/slack-objc/App/Extensions/BroadcastUpload/Source/ScreenBroadcastSampleHandler.swift:12:7"
```

**17.0**

```
"/Users/ekerber/Developer/slack/slack-objc/App/Extensions/BroadcastUpload/Source/ScreenBroadcastSampleHandler.swift"
```

**Comment by erikkerber** [comment]
In other words if you look at the diff alone I believe you can see the repro

The old `description` included the line/column. It was changed to operate only on the `location` and the `description` is no longer used.

**Comment by geraldWilliam** [comment]
https://github.com/peripheryapp/periphery/pull/681
