### ISSUE TITLE
Can't run it as Build Script

### ISSUE THREAD

**Issue by bennyyy999** [peripheryapp/periphery#698]
After installing it with Homebrew and setting it up, it works inside the terminal without problems when doing `periphery --scan`, but inside the Build Script (`periphery scan --format xcode`) I always get: `Command PhaseScriptExecution failed with a nonzero exit code`.

I also tried to use the method from Krzysztof course with:
```
cd "${SRC_DIR}"
/opt/homebrew/bin/periphery scan --format xcode
```
But this throws me this error:
```
error: Sandbox: periphery(19699) deny(1) file-read-data /Users/X/.periphery.yml (in target 'Periphery' from project 'X')
error: (NSError) Error Domain=NSCocoaErrorDomain Code=257 "The file “.periphery.yml” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/X/.periphery.yml, NSUnderlyingError=0x60000274c690 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

What am I doing wrong here?

**Comment by bryanmontz** [comment]
This should solve that:
https://thisdevbrain.com/swiftlint-permission-issue/

**Comment by bennyyy999** [comment]
@bryanmontz you a legend!
