### ISSUE TITLE
False positive: NSPrincipalClass key is ignored

### ISSUE THREAD

**Issue by Cykelero** [peripheryapp/periphery#712]
# Summary
Setting a custom principal class (as declared in the Info.plist file under the `NSPrincipalClass` key) is not recognized by Periphery.
This means it can report the class as being unused, even though the class is instantiated by the system on app launch.

# Reproducing

- Create a new Storyboard/Swift app
- Create a `UIApplication` or `NSApplication` subclass
- In the project's build settings, set “Principal Class” to your class (in the `ModuleName.ClassName` form)
- Run periphery: it reports the class as unused

**Comment by ileitch** [comment]
This was fixed in 2.18.0. What version are you using?

**Comment by Cykelero** [comment]
You're right, I can't reproduce this issue with 2.18.0. I must have been using an older version at the time—sorry!
