### ISSUE TITLE
failure on passing in multiple targets

### ISSUE THREAD

**Issue by pgorrindo** [peripheryapp/periphery#718]
# error description
Hi, curious if anyone else is seeing this? Our Periphery implementation has been working fine for some time. But recently, have noticed that it fails when passing in multiple Xcode targets for a given Xcode project file, but doesn't error when passing in only one target. Current versions of both Periphery (via Homebrew) and Xcode. Our implementation is that we use a script in our CI to call Periphery from the command line, with a Periphery scheme in our Xcode project, as follows:

# periphery invocation that works

`periphery scan --verbose --format xcode --targets "App1" --schemes Periphery`

the above invocation works, but is only passing in only one target ("App1"). our normal use of Periphery, which has been working for quite some time (years) passes in three targets, below.

# periphery invocation that now (newly) fails

same command as above, but now with multiple targets (which previously worked) but now fails:

`periphery scan --verbose --format xcode --targets "App1,App1Widget,App2" --schemes Periphery`

## output of the `verbose` command above

for reference, the output of the failing command above is:

```
[version] 2.18.0
[shell] /usr/local/bin/zsh -lc env
[shell] /usr/bin/env swift -version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
[shell] /usr/bin/env xcodebuild -version
Xcode 15.2
Build version 15C500b
[configuration:begin]
index_exclude:
- '**/docs/*'
project: App.xcodeproj
schemes:
- Periphery
targets:
- App1,App1Widget,App2
verbose: true
[configuration:end]
* Inspecting project...
[xcode:project] Loading /Users/phil/dev/apps/xcode/App.xcodeproj
error: Target 'App1,App1Widget,App2' does not exist in 'App.xcodeproj'.
```

Note that I've confirmed that when I run `xcodebuild -list` that the correct schemes and targets are seen by `xcodebuild ` -- they do exist in the Xcode project and are accessible by `xcodebuild`. 

# attempted fixes

I've tried passing `--clean-build` in with the above commands, but no change.

I've tried `periphery clear-cache`, but no change. 

I've tried formatting the `--targets "App1,App1Widget,App2"` arguments with whitespace, i.e. `--targets "App1, App1Widget, App2"`, but no change. 

# help please?

Any insight? Thanks in advance!

**Comment by rokridi** [comment]
Hello @pgorrindo 👋 
Any update on this ? Did you find out how to format the `targets` parameter in case you pass multiple targets ?

**Comment by pgorrindo** [comment]
nope, no update @rokridi -- still the same situation as described above. 

@ileitch any thoughts?

**Comment by scottasoutherland** [comment]
Not sure why, but you now pass them with spaces instead of commas. I.e. `--targets App1 App1Widget App2 --schemes Periphery`

**Comment by ileitch** [comment]
Scott is correct, we now use the native format of `swift-argument-parser`. This was mentioned as a breaking change in the 2.18.0 release notes: https://github.com/peripheryapp/periphery/blob/master/CHANGELOG.md#2180-2024-01-21

**Comment by pgorrindo** [comment]
Zounds, sorry that I missed that! Thanks @ileitch - resolved for me now!
