### ISSUE TITLE
False Positives with `Hashable`

### ISSUE THREAD

**Issue by iv-mexx** [peripheryapp/periphery#721]
Hi, I think I'm getting these false positives with a Strict thats `Hashable` in Periphery `2.18.0`

```swift
  private struct LootToggleIdentifier: Hashable {
    let categoryName: String
    let typeName: String
    let usages: Set<Usage>
    let categories: Set<Category>
  }
```

![Screenshot 2024-03-11 at 10 27 24](https://github.com/peripheryapp/periphery/assets/3407787/971454ff-e747-4f29-b560-298eb6ca193a)

Its true, `categoryName` and `typeName` are never read explicitly, but they are factored into automatically synthesized hash function ( https://developer.apple.com/documentation/swift/hashable#Conforming-to-the-Hashable-Protocol )

**Comment by ileitch** [comment]
This isn't a false positive, Periphery correctly identifies that the property isn't read from anywhere else in your code. No tool can determine that these properties are used only for altering the hash value. You can either implement `hash(into:)` or use a [comment command](https://github.com/peripheryapp/periphery?tab=readme-ov-file#comment-commands) to retain these properties.
