### ISSUE TITLE
I think I found a false positive.  

### ISSUE THREAD

**Issue by scott-lydon** [peripheryapp/periphery#727]
If you create an initializer for arrays 

```swift
extension Array where Element == Int { 

    init(myNewInit: String) { 
        self = [1]
    }
}

let test = [Int](myNewInit: "This isn't picked up")
```
Apart from that, thank you for all your great work!

**Comment by ileitch** [comment]
Unfortunately, this is a known issue caused by a bug in the Swift compiler: https://github.com/peripheryapp/periphery/issues/1
