### ISSUE TITLE
SwiftSyntax parser library isn't compatible

### ISSUE THREAD

**Issue by danleechina** [peripheryapp/periphery#74]
Does anyone see this error using Xcode 11.

**Comment by JasonJotted** [comment]
I see it too. Did you ever get it resolved?

**Comment by ileitch** [comment]
The latest version is using SwiftSyntax for Swift 5.1, 5.2 support is still in the works. Can you try with Xcode 11.3?

**Comment by gogovan-anthonychan** [comment]
Have the same issue for Xcode 11.4, but it works on Xcode 11.3

**Comment by 36v** [comment]
I get the same error using Xcode 11.4.

**Comment by Dfmarulanda** [comment]
Same

**Comment by ileitch** [comment]
Fixed in 1.7.0.
