### ISSUE TITLE
Periphery doesn't retain unused imports in retained files

### ISSUE THREAD

**Issue by aim2120** [peripheryapp/periphery#748]
Since unused imports have become the default behavior with periphery, I've found that files that are marked as retained have started to have "unused" symbols. These are due to unused imports not being properly removed for retained files. I haven't checked if this is also the case for when comments are used to retain parts of files, but I imagine it's probably the same behavior.

This seems like a bug, unless someone can indicate that this is intended behavior.

I'm more than happy to open a PR with a fix.

**Comment by ileitch** [comment]
Thanks for reporting!
