### ISSUE TITLE
Local Swift package not found after upgrading from 2.20.0 to 2.21.0

### ISSUE THREAD

**Issue by neilsardesai** [peripheryapp/periphery#756]
Hello,
I just tried updating from Periphery 2.20.0 to 2.21.0, and the same command that used to work before is now erroring:

`periphery scan --project 'PROJECT NAME.xcodeproj' --schemes 'MAIN APP' --targets 'MAIN APP' 'MAINAPPUI' 'MAIN APP TESTS' --retain-public --skip-schemes-validation --format Xcode`

`* Inspecting project...
error: Target 'MAINAPPUI' does not exist in 'PROJECT NAME.xcodeproj'.`

`MAINAPPUI` is a local Swift package consumed by `MAIN APP`. I wonder if this issue might be related to recent changes around handling of local Swift packages? (https://github.com/peripheryapp/periphery/commit/c0846a6019304587d3c351b3cfb80cd0f20d18c8)

**Comment by ileitch** [comment]
Is the local package listed in Package Dependencies in your project settings?

**Comment by neilsardesai** [comment]
Hey Ian, no the local package isn’t listed in Package Dependencie

**Comment by ileitch** [comment]
Adding it should fix the issue

**Comment by neilsardesai** [comment]
That did the trick. Thanks! I’ll go ahead and close this as resolved

**Comment by icecoffin** [comment]
What about the test targets of the local packages? Previously, they were listed when running `periphery scan --setup`, but not anymore.
