### ISSUE TITLE
Scan all targets in addition to specific ones

### ISSUE THREAD

**Issue by rofle100lvl** [peripheryapp/periphery#757]
I'm currently using periphery for my project, and I've noticed that it lacks the ability to automatically scan all targets that are connected to a scheme. This functionality would be invaluable for comprehensive analysis, especially in larger projects where multiple targets need to be checked.

Could there be an option added to scan all targets associated with a particular scheme? This would greatly enhance usability for users who wish to conduct a thorough cleanup of their entire project.

**Comment by ileitch** [comment]
This is being addressed in the [v3](https://github.com/peripheryapp/periphery/tree/v3) branch.
