### ISSUE TITLE
Baseline usage help

### ISSUE THREAD

**Issue by aiKrice** [peripheryapp/periphery#759]
Hello @manicmaniac, first of all, great job !
I'm trying the baseline feature but I don't understand how it works. I generate my baseline like this:

```bash
periphery scan --project Shopmium.xcodeproj --schemes ShopmiumSandbox --targets Shopmium 
--index-store-path ~/Library/Developer/Xcode/DerivedData/Shopmium-hjwfjrzwnoolqiatozxkypaeyhsh/Index.noindex/DataStore 
--write-baseline baseline --format json
```
It work fine, I can see my baseline file full of my warnings

Now I want to apply it 
I ran :
```bash
periphery scan --project Shopmium.xcodeproj --schemes ShopmiumSandbox --targets Shopmium 
--index-store-path ~/Library/Developer/Xcode/DerivedData/Shopmium-hjwfjrzwnoolqiatozxkypaeyhsh/Index.noindex/DataStore
 --baseline baseline --format json
```

But it doesn't do anything. Am I wrong ?

**Comment by manicmaniac** [comment]
@aiKrice 
> Hello @manicmaniac, first of all, great job !

Oh, I'm not the author of this product 😅 

@ileitch deserves the praise.

**Comment by aiKrice** [comment]
Oh GG to @ileitch . My point is still valid anyway 👍

**Comment by aiKrice** [comment]
Nudge @ileitch :)

**Comment by ileitch** [comment]
Why are you using the `--index-store` option? Does the generated baseline file contain anything?
