### ISSUE TITLE
Embedded Swift packages are not recognised anymore in 2.21.0 version

### ISSUE THREAD

**Issue by amseddi** [peripheryapp/periphery#768]
To demonstrate this issue, I created a new project with an embedded Swift package:
![image](https://github.com/peripheryapp/periphery/assets/1511694/5c84be33-e094-4e79-b1a8-2653b2d121b7)

The embedded Swift package used to be recognised and could be analysed.
Please find the output of the `scan --setup command` below:

Using periphery@2.21.0
```sh
➜  PeripherySPMIssue mint run periphery scan --setup
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Inspecting project...

Select build targets to analyze:
? Delimit choices with a single space, e.g: 1 2 3, or 'all' to select all options
1 PeripherySPMIssue
> 
```

Using periphery@2.20.0
```sh
➜  PeripherySPMIssue mint run periphery scan --setup
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Inspecting project...

Select build targets to analyze:
? Delimit choices with a single space, e.g: 1 2 3, or 'all' to select all options
1 EmbeddedPackage.EmbeddedPackage
2 PeripherySPMIssue
> 
```

**Comment by ileitch** [comment]
Can you check that these packages are also listed as package dependencies in the project settings?

**Comment by amseddi** [comment]
> Can you check that these packages are also listed as package dependencies in the project settings?

It was not listed at first. And when I added it to the projects settings, the embedded package was included in the results of the `scan` command:
```bash
➜  PeripherySPMIssue mint run periphery scan --setup           
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Inspecting project...

Select build targets to analyze:
? Delimit choices with a single space, e.g: 1 2 3, or 'all' to select all options
1 EmbeddedPackage.EmbeddedPackage
2 PeripherySPMIssue

```

Does this mean we mean we will need to add all local packages to the dependencies in the project settings?

**Comment by ileitch** [comment]
It does, yes.

**Comment by ileitch** [comment]
@Servus7 Is there any way you can restructure your project to workaround this? This sounds more like an Xcode issue. SPM support prior to 2.21.0 was very much a hack. It was implemented befofe Xcode's pbxproj explicitly declared SPM dependencies. 2.21.0 now only uses the explicit SPM dependecies declared in the pbxproj, which requires local packages to be added via the Xcode UI.
