### ISSUE TITLE
Baseline parameter gets added to xcodebuild

### ISSUE THREAD

**Issue by nhaarman** [peripheryapp/periphery#775]
When running `periphery scan --baseline periphery_baseline.txt`, the command fails with the following message:

```
error: Shell command '/bin/sh -c xcodebuild -workspace '***' -scheme '***' -parallelizeTargets -derivedDataPath '***' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf" COMPILER_INDEX_STORE_ENABLE="YES" INDEX_ENABLE_DATA_STORE="YES" periphery_baseline.txt' returned exit status '65':
2024-07-26 13:04:58.701 xcodebuild[42961:4206843] Writing error result bundle to /var/folders/nl/l3g15bk94pbfdsz5gfjpbsc40000gn/T/ResultBundle_2024-26-07_13-04-0058.xcresult
xcodebuild: error: Unknown build action 'periphery_baseline.txt'.
```

**Comment by ileitch** [comment]
I'm unable to reproduce this. I suspect you're either not using the correct version of Periphery, or the command you've stated is not the actual command your are executing. The only way in wich stated error would be possible is if you were doing the following `periphery scan -- periphery_baseline.txt`.
