### ISSUE TITLE
Release v1.7.0

### ISSUE THREAD

**Issue by kateinoigakukun** [peripheryapp/periphery#80]
The latest released version 1.6.0 can't be built with Xcode11.4. This issue was already fixed, thanks @ileitch

So I want to release next version periphery, could you tell me how to do that? or could you write down release flow like https://github.com/IBDecodable/IBLinter/blob/master/docs/Release.md ?

to: @ileitch

**Comment by Dfmarulanda** [comment]
any update on this?

**Comment by ileitch** [comment]
Hey sorry, I didn't have time today. I'll release 1.7.0 tomorrow. I need to work on the release process, currently it's only possible for me to do it.

**Comment by ileitch** [comment]
Done

**Comment by Dfmarulanda** [comment]
#81 after upgrade
