### ISSUE TITLE
Periphery version 3.0.0 b2 fails.

### ISSUE THREAD

**Issue by rsyncOSX** [peripheryapp/periphery#800]
Version 2.21.0 works, but version 3.0.0.beta2 fails.. See error below

GitHub repository is: https://github.com/rsyncOSX/RsyncUI
Xcode 16 beta 6, `SWIFT_VERSION = 6` and `SWIFT_STRICT_CONCURRENCY = complete` set in Xcode

## Output from version 2.21.0 

/opt/homebrew/bin/periphery scan
* Inspecting project...
* Building RsyncUI...
* Indexing...
* Analyzing...

* No unused code detected.

* Update Available
Version 3.0.0.beta2 is now available, you are using version 2.21.0.
Release notes: https://github.com/peripheryapp/periphery/releases/tag/3.0.0.beta2
To disable update checks pass the --disable-update-check option to the scan command.

## Output from version 3.0.0.beta2

* Executing command:
periphery scan

* Inspecting project...
* Building RsyncUI...
<code>
error: Shell command '/bin/sh -c xcodebuild -project '/Users/thomas/GitHub/RsyncUI/RsyncUI.xcodeproj' -scheme 'RsyncUI' -parallelizeTargets -derivedDataPath '/Users/thomas/Library/Caches/com.github.peripheryapp/DerivedData-a23bd836-c0f3ea92-c0f3ea92' -quiet build-for-testing CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf" COMPILER_INDEX_STORE_ENABLE="YES" INDEX_ENABLE_DATA_STORE="YES"' returned exit status '65':
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006030-0014245C22D0001C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006030-0014245C22D0001C, name:My Mac }
{ platform:macOS, name:Any Mac }
error: Build input file cannot be found: '/Users/thomas/Library/Caches/com.github.peripheryapp/DerivedData-a23bd836-c0f3ea92-c0f3ea92/Build/Products/Debug/RsyncUIUITests-Runner.app/Contents/PlugIns/RsyncUIUITests.xctest/Contents/MacOS/RsyncUIUITests'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'RsyncUIUITests' from project 'RsyncUI')
error: Build input file cannot be found: '/Users/thomas/Library/Caches/com.github.peripheryapp/DerivedData-a23bd836-c0f3ea92-c0f3ea92/Build/Products/Debug/RsyncUI.app/Contents/PlugIns/RsyncUITests.xctest/Contents/MacOS/RsyncUITests'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'RsyncUITests' from project 'RsyncUI')
note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'RsyncUI' from project 'RsyncUI')
** TEST BUILD FAILED **
</code>

**Comment by ileitch** [comment]
Thanks for trying out the beta. I think the issue is the non-conditional use of `build-for-testing`. I likely need to bring back some 2.x logic.

**Comment by rsyncOSX** [comment]
And periphery is a great app, thanks for making it... Without I could not clean my sources...

**Comment by ileitch** [comment]
It appears the issue is that your project contains 2 unused test targets without any sources. Deleting them fixes the issue.

**Comment by rsyncOSX** [comment]
Thanks, deleted the two test targets.. Version 3.0.0 b4 works as expected :-) no errors (and no unused code)...
