### ISSUE TITLE
Implement SwiftLint in Continuous Integration - Discussion

### ISSUE THREAD

**Issue by mildm8nnered** [peripheryapp/periphery#803]
Opening this as a place to hang discussion.

Makefile entry should be easy enough, perhaps

```
swiftlint:
        swiftlint --quiet
```

but SwiftLint will exit with 0 on any successful run, whether violations are detected or not, so possibly we'll want a wrapper script with an exit value

There's also the question of how SwiftLint should be installed/assumptions about paths on the CI machines. For example, homebrew installs SwiftLint at `/opt/homebrew/bin/swiftlint`, which may (or may not) be on the CI user's path.

See for example, https://github.com/realm/SwiftLint#installation

**Comment by ileitch** [comment]
Implemented in https://github.com/peripheryapp/periphery/pull/806 using [mise](https://github.com/jdx/mise).
