### ISSUE TITLE
Scan raises an error in line 55 but file has only 38 lines

### ISSUE THREAD

**Issue by sergiocaserowl** [peripheryapp/periphery#812]
Hello!

I'm facing this issue with periphery, basically, in the analysis I see:

```json
{
  "modifiers": [],
  "attributes": [],
  "accessibility": "internal",
  "ids": [
    "s:1118NavigationColorBarV"
  ],
  "name": "NavigationColorBar",
  "hints": [
    "unused"
  ],
  "location": "*****/utils/ViewModifiers.swift:55:8",
  "modules": [
    "******"
  ],
  "kind": "struct"
}
```

But... this is the file:

```swift
//
//  ViewModifiers.swift
// 
//
//  Created by **** on 27/10/22.
//

import SwiftUI

#if canImport(UIKit)
extension View {
    func hideKeyboard() {
        UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)
    }
}
#endif

extension View {
    func cornerRadius(_ radius: CGFloat, corners: UIRectCorner) -> some View {
        clipShape( RoundedCorner(radius: radius, corners: corners) )
    }
}

struct RoundedCorner: Shape {
    
    var radius: CGFloat = .infinity
    var corners: UIRectCorner = .allCorners
    
    func path(in rect: CGRect) -> Path {
        let path = UIBezierPath(
            roundedRect: rect,
            byRoundingCorners: corners,
            cornerRadii: CGSize(width: radius, height: radius)
        )
        return Path(path.cgPath)
    }
}
```

**Comment by ileitch** [comment]
Is this issue consistently reproduced? Does `--clean-build` fix it`? Which files declares `NavigationColorBar`?

**Comment by sergiocasero** [comment]
> Is this issue consistently reproduced? Does `--clean-build` fix it? Which file declares `NavigationColorBar`?

Hello! Sorry Github didn't notified me. If I run with --clean-build, I get the same output. I have to say I'm using periphery from sonar-apple plugin, which executes exactly this command: ```periphery scan --skip-build --format json --quiet```

**Comment by sergiocaserowl** [comment]
> Is this issue consistently reproduced? Does `--clean-build` fix it? Which file declares `NavigationColorBar`?

Hello! Sorry Github didn't notified me. If I run with --clean-build, I get the same output. I have to say I'm using periphery from sonar-apple plugin, which executes exactly this command: ```periphery scan --skip-build --format json --quiet```

**Comment by ileitch** [comment]
Your index store is likely out-of-date compared to the local source files. I don't have any experience with Sonar, so I'm unable to help further. Maybe the author of https://github.com/insideapp-oss/sonar-apple is able to help.
