### ISSUE TITLE
MacOS 15 officially in release candidate phase

### ISSUE THREAD

**Issue by bryan1anderson** [peripheryapp/periphery#813]
error: (DecodingError) keyNotFound(CodingKeys(stringValue: "compatibilityVersion", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"compatibilityVersion\", intValue: nil) (\"compatibilityVersion\").", underlyingError: nil))

get this when running

**Comment by ileitch** [comment]
This error is originating from Xcodeproj, the issue is being tracked here: https://github.com/tuist/XcodeProj/issues/837

**Comment by bastianmorath** [comment]
@ileitch  I think you need to update the Xcodeproj dependency to at least version [8.24.2](https://github.com/tuist/XcodeProj/releases/tag/8.24.2) in order to include the fix.

**Comment by bastianmorath** [comment]
@ileitch  I created a PR for this: https://github.com/peripheryapp/periphery/pull/832

**Comment by ileitch** [comment]
I just released 2.21.2 to fix this.
