### ISSUE TITLE
Xcode 16 error: (PBXObjectError) The element PBXFileSystemSynchronizedBuildFileExceptionSet is not supported.

### ISSUE THREAD

**Issue by dhruvd-grappus** [peripheryapp/periphery#818]
periphery :  `2.21.0`

Xcode : `16.0`

<img width="713" alt="Screenshot 2024-09-18 at 12 05 48 PM" src="https://github.com/user-attachments/assets/6dfba955-76d2-4555-b49f-2b27fc2877d2">

**Comment by ileitch** [comment]
I'm waiting for https://github.com/tuist/XcodeProj/issues/837 to be fixed and then I will make a new release.

**Comment by dhruvd-grappus** [comment]
@ileitch any update on this ? seems like that issue is closed

**Comment by ileitch** [comment]
It should be resolved in 2.21.1
