### ISSUE TITLE
(PBXObjectError) The element PBXFileSystemSynchronizedRootGroup is not supported

### ISSUE THREAD

**Issue by AllDmeat** [peripheryapp/periphery#819]
I've tried setup Periphery for newly created project with no luck.

macOS: 15.0
Xcode: 16.0
Xcode project: created using Xcode 16.0
Periphery version: 2.21.0

`periphery scan` result:
```
* Inspecting project...
error: (PBXObjectError) The element PBXFileSystemSynchronizedRootGroup is not supported.
```

Sometimes that gives me other result:
```
* Inspecting project...
error: (DecodingError) keyNotFound(CodingKeys(stringValue: "compatibilityVersion", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"compatibilityVersion\", intValue: nil) (\"compatibilityVersion\").", underlyingError: nil))
```
Demo project: [PeripheryExample.zip](https://github.com/user-attachments/files/17049084/PeripheryExample.zip)

**Comment by ileitch** [comment]
I'm waiting for https://github.com/tuist/XcodeProj/issues/837 to be fixed and then I will make a new release.
