### ISSUE TITLE
preferredProjectObjectVersion error

### ISSUE THREAD

**Issue by uxhaitham** [peripheryapp/periphery#830]
getting the following error when trying to scan a project

`error: (DecodingError) typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "preferredProjectObjectVersion", intValue: nil)], debugDescription: "Expected to decode Int but found a string instead.", underlyingError: nil))`

when I checked the preferredProjectObjectVersion of my project, it is not a string, its an integer
the project was created using Xcode 16.0

I manually changed preferredProjectObjectVersion from 77 to 52 for testing
its still throwing the same error

**Comment by ileitch** [comment]
I just released 2.21.2 to fix this.
