### ISSUE TITLE
Build project failed on "ld" command after running "Periphery scan"

### ISSUE THREAD

**Issue by vikihleblya** [peripheryapp/periphery#89]
XCode 11.3.1 (11C505)

I installed Periphery via Pods, moved to main directory and run `Pods/Periphery/periphery scan`
After that I got this error. 
```
** BUILD FAILED **


The following build commands failed:
	Ld /Users/viktorgrigorev/Library/Caches/com.peripheryapp.periphery/DerivedData-0e0943a26bb15624fa2b5d1c7216df51ba6aad32/Build/Products/Debug-iphoneos/MainApp.app/MainApp normal arm64
(1 failure)
```
I use Kotlin/Native in my project, but I believe that not connected to build failure.
I've tried delete DerivedData and clean project, but nothing happened. 
I would be appreciated to any suggestions! Thanks!

**Comment by ileitch** [comment]
Run again in verbose mode, look for the xcodebuild command, copy that and run it to make sure that your project builds without Periphery involved.

**Comment by vikihleblya** [comment]
I figured it out. 
**Explanation:** 
I use Kotlin/Native and these line of code chooses needed preset for building
```
final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos")    \
                                 ? presets.iosArm64 : presets.iosX64
```
So, I changed my app scheme from **Debug** to **Release** and by that I changed preset too. And it works fine now! 
Sorry for bothering!
