### ISSUE TITLE
.SwiftFileLis couldn’t be opened

### ISSUE THREAD

**Issue by kushak** [peripheryapp/periphery#94]
* Inspecting project configuration...
* Building MyScheme...
* Indexing...
Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “MyTarget.SwiftFileList” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/user/Library/Caches/com.peripheryapp.periphery/DerivedData-db98bf13abd1bf4f27f15313819bb3721c37ebda/Build/Intermediates.noindex/cc.build/Debug-iphoneos/MyTarget.build/Objects-normal/arm64/MyProj.SwiftFileList, NSUnderlyingError=0x7f800f1837c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

macOS 10.15.4
xcode 11.4.1

What to do for resolved this error?

**Comment by LBarranco** [comment]
I have the same issue. Did anyone find out how to solve it?

Thx!

**Comment by idoNaveh** [comment]
I had the same problem. It looks like the problem related to the target name. In my case, I remove spaces and special characters from the target name and now it's working.

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this.
