### ISSUE TITLE
Failed to scan project on Xcode 11.4.1 (11E503a)

### ISSUE THREAD

**Issue by SerhiiMiskiv** [peripheryapp/periphery#97]
Got an issue while scanning project.
I was using these commands:

"
* Executing command:
periphery scan \
  --workspace "/Users....xcworkspace/" \
  --schemes "..." \
  --targets "..." \
  --retain-public
"

And the final output is:
"
* Inspecting project configuration...
* Building PinataQA...
* Indexing...
sourcekit: [1:connection-event-handler:14595: 0.0000] Connection interruptsourcekit: [1:updateSemanticEditorDelay:14595: 0.0004] disabling semantic editor for 10 secondssourcekit: [1:pingService:14595: 0.0005] pinging servicesourcekit: [1:ping-event-handler:14595: 0.0082] service restoredError: SourceKit cursorInfo request failed for file '/Users/serj.miskiv/Desktop/PinataFarm/ios/PinataFarm/Sources/Views/ContentTypeSelectionView.swift': Connection interrupted
"

**Comment by dessmith** [comment]
This is exactly what I'm getting

**Comment by daveluong** [comment]
I'm getting "Error: parsingFailed" on Xcode 11.5
https://github.com/peripheryapp/periphery/issues/99

**Comment by SerhiiMiskiv** [comment]
@ileitch @a2 @kateinoigakukun can anyone help me with this ?

**Comment by chosa91** [comment]
Same here on Xcode 11.6 
```
sourcekit: [1:connection-event-handler:12803: 0.0000] Connection interruptsourcekit: [1:updateSemanticEditorDelay:12803: 0.0004] disabling semantic editor for 10 secondssourcekit: [1:pingService:12803: 0.0005] pinging servicesourcekit: [1:ping-event-handler:12803: 0.0212] service restoredError: SourceKit cursorInfo request failed for file '/Users/myuser/dev/MyApp/MyApp/Migration/KeychainMigrator.swift': Connection interrupted
```

**Comment by ileitch** [comment]
Please try again with version 2.0.1 and open a new issue if you're still seeing this.
