### ISSUE TITLE
When I try with 1.5.1 I get this issue with `periphery scan`

### ISSUE THREAD

**Issue by kpavankotesh** [peripheryapp/periphery#98]
When I try with 1.5.1 I get this:

```
The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/username/Library/Caches/com.peripheryapp.periphery/DerivedData-1e3535f7fd97fa35db8532fd156bdc8960d22b8f/Build/Intermediates.noindex/APPNAME.build/Debug\ Production-iphoneos/APPNAME.build/Script-B75B5BFE4FBDDA75299A3A15.sh
(1 failure)
```

_Originally posted by @kpavankotesh in https://github.com/peripheryapp/periphery/issues/37#issuecomment-636625970_

**Comment by ileitch** [comment]
This likely isn't the actual build error, the log probably has an actual error somewhere further up in the output, searching for `error:` should find it.
